/*
This file was generated by Nickk's TextDraw editor script
Nickk888 is the author of the NTD script
*/

//Variables
new Text:HUDTD;
new Text:HUDTD1;
new Text:HUDTD2;
new Text:HUDTD3;
new Text:IDTD;
new Text:IDTD1;
new Text:CashTD1;
new Text:CashTD;
new Text:JobTD;
new Text:VoiceChatTD;
new Text:HUDTD4;
new Text:HUDTD5;
new Text:HUDTD6;
new Text:HUDTD7;
new PlayerText:HeathTD[MAX_PLAYERS];
new PlayerText:ArmorTD[MAX_PLAYERS];
new PlayerText:HungerTD[MAX_PLAYERS];
new PlayerText:ThirstTD[MAX_PLAYERS];
new PlayerBar:ArmorBar[MAX_PLAYERS];
new PlayerBar:HealthBar[MAX_PLAYERS];
new PlayerBar:HungerBar[MAX_PLAYERS];
new PlayerBar:ThirstBar[MAX_PLAYERS];

//Textdraws
HUDTD = TextDrawCreate(555.000000, 126.000000, "_");
TextDrawFont(HUDTD, 1);
TextDrawLetterSize(HUDTD, 2.674999, 1.499998);
TextDrawTextSize(HUDTD, 338.000000, 101.500000);
TextDrawSetOutline(HUDTD, 1);
TextDrawSetShadow(HUDTD, 0);
TextDrawAlignment(HUDTD, 2);
TextDrawColor(HUDTD, -1);
TextDrawBackgroundColor(HUDTD, 255);
TextDrawBoxColor(HUDTD, 135);
TextDrawUseBox(HUDTD, 1);
TextDrawSetProportional(HUDTD, 1);
TextDrawSetSelectable(HUDTD, 0);

HUDTD1 = TextDrawCreate(579.000000, 126.000000, "_");
TextDrawFont(HUDTD1, 1);
TextDrawLetterSize(HUDTD1, 0.495833, 1.500000);
TextDrawTextSize(HUDTD1, 557.500000, 29.000000);
TextDrawSetOutline(HUDTD1, 1);
TextDrawSetShadow(HUDTD1, 0);
TextDrawAlignment(HUDTD1, 1);
TextDrawColor(HUDTD1, 16711935);
TextDrawBackgroundColor(HUDTD1, 255);
TextDrawBoxColor(HUDTD1, -764862721);
TextDrawUseBox(HUDTD1, 1);
TextDrawSetProportional(HUDTD1, 1);
TextDrawSetSelectable(HUDTD1, 0);

HUDTD2 = TextDrawCreate(517.000000, 126.000000, "_");
TextDrawFont(HUDTD2, 1);
TextDrawLetterSize(HUDTD2, 0.462500, 1.500000);
TextDrawTextSize(HUDTD2, 496.500000, 29.500000);
TextDrawSetOutline(HUDTD2, 1);
TextDrawSetShadow(HUDTD2, 0);
TextDrawAlignment(HUDTD2, 1);
TextDrawColor(HUDTD2, 9109759);
TextDrawBackgroundColor(HUDTD2, 255);
TextDrawBoxColor(HUDTD2, 2094792959);
TextDrawUseBox(HUDTD2, 1);
TextDrawSetProportional(HUDTD2, 1);
TextDrawSetSelectable(HUDTD2, 0);

HUDTD3 = TextDrawCreate(133.000000, 429.000000, "_");
TextDrawFont(HUDTD3, 1);
TextDrawLetterSize(HUDTD3, 5.412494, 1.049999);
TextDrawTextSize(HUDTD3, 452.500000, 255.000000);
TextDrawSetOutline(HUDTD3, 1);
TextDrawSetShadow(HUDTD3, 0);
TextDrawAlignment(HUDTD3, 2);
TextDrawColor(HUDTD3, -1);
TextDrawBackgroundColor(HUDTD3, 255);
TextDrawBoxColor(HUDTD3, 135);
TextDrawUseBox(HUDTD3, 1);
TextDrawSetProportional(HUDTD3, 1);
TextDrawSetSelectable(HUDTD3, 0);

IDTD = TextDrawCreate(569.000000, 126.000000, "ID:");
TextDrawFont(IDTD, 1);
TextDrawLetterSize(IDTD, 0.329166, 1.450002);
TextDrawTextSize(IDTD, 317.500000, 73.500000);
TextDrawSetOutline(IDTD, 0);
TextDrawSetShadow(IDTD, 0);
TextDrawAlignment(IDTD, 2);
TextDrawColor(IDTD, -1);
TextDrawBackgroundColor(IDTD, 255);
TextDrawBoxColor(IDTD, 135);
TextDrawUseBox(IDTD, 0);
TextDrawSetProportional(IDTD, 1);
TextDrawSetSelectable(IDTD, 0);

IDTD1 = TextDrawCreate(590.000000, 127.000000, "100");
TextDrawFont(IDTD1, 1);
TextDrawLetterSize(IDTD1, 0.183333, 1.300003);
TextDrawTextSize(IDTD1, 298.500000, 75.000000);
TextDrawSetOutline(IDTD1, 0);
TextDrawSetShadow(IDTD1, 0);
TextDrawAlignment(IDTD1, 2);
TextDrawColor(IDTD1, -1);
TextDrawBackgroundColor(IDTD1, 255);
TextDrawBoxColor(IDTD1, 135);
TextDrawUseBox(IDTD1, 0);
TextDrawSetProportional(IDTD1, 1);
TextDrawSetSelectable(IDTD1, 0);

CashTD1 = TextDrawCreate(507.000000, 126.000000, "$");
TextDrawFont(CashTD1, 1);
TextDrawLetterSize(CashTD1, 0.420833, 1.500002);
TextDrawTextSize(CashTD1, 317.500000, 73.500000);
TextDrawSetOutline(CashTD1, 0);
TextDrawSetShadow(CashTD1, 0);
TextDrawAlignment(CashTD1, 2);
TextDrawColor(CashTD1, -1);
TextDrawBackgroundColor(CashTD1, 255);
TextDrawBoxColor(CashTD1, 135);
TextDrawUseBox(CashTD1, 0);
TextDrawSetProportional(CashTD1, 1);
TextDrawSetSelectable(CashTD1, 0);

CashTD = TextDrawCreate(538.000000, 127.000000, "1,999,999");
TextDrawFont(CashTD, 1);
TextDrawLetterSize(CashTD, 0.183333, 1.300003);
TextDrawTextSize(CashTD, 298.500000, 75.000000);
TextDrawSetOutline(CashTD, 0);
TextDrawSetShadow(CashTD, 0);
TextDrawAlignment(CashTD, 2);
TextDrawColor(CashTD, -1);
TextDrawBackgroundColor(CashTD, 255);
TextDrawBoxColor(CashTD, 135);
TextDrawUseBox(CashTD, 0);
TextDrawSetProportional(CashTD, 1);
TextDrawSetSelectable(CashTD, 0);

JobTD = TextDrawCreate(549.000000, 106.000000, "MECHANIC:_BOSS");
TextDrawFont(JobTD, 1);
TextDrawLetterSize(JobTD, 0.391666, 1.550002);
TextDrawTextSize(JobTD, 324.000000, 78.000000);
TextDrawSetOutline(JobTD, 0);
TextDrawSetShadow(JobTD, 0);
TextDrawAlignment(JobTD, 2);
TextDrawColor(JobTD, -1);
TextDrawBackgroundColor(JobTD, 255);
TextDrawBoxColor(JobTD, 135);
TextDrawUseBox(JobTD, 0);
TextDrawSetProportional(JobTD, 1);
TextDrawSetSelectable(JobTD, 0);

VoiceChatTD = TextDrawCreate(83.000000, 323.000000, "~b~VOICE:_~w~NORMAL");
TextDrawFont(VoiceChatTD, 2);
TextDrawLetterSize(VoiceChatTD, 0.233333, 1.950002);
TextDrawTextSize(VoiceChatTD, 298.500000, 75.000000);
TextDrawSetOutline(VoiceChatTD, 0);
TextDrawSetShadow(VoiceChatTD, 0);
TextDrawAlignment(VoiceChatTD, 2);
TextDrawColor(VoiceChatTD, 1097458175);
TextDrawBackgroundColor(VoiceChatTD, 255);
TextDrawBoxColor(VoiceChatTD, 135);
TextDrawUseBox(VoiceChatTD, 0);
TextDrawSetProportional(VoiceChatTD, 1);
TextDrawSetSelectable(VoiceChatTD, 0);

HUDTD4 = TextDrawCreate(6.000000, 428.000000, "HUD:radar_girlfriend");
TextDrawFont(HUDTD4, 4);
TextDrawLetterSize(HUDTD4, 0.600000, 2.000000);
TextDrawTextSize(HUDTD4, 14.000000, 11.500000);
TextDrawSetOutline(HUDTD4, 1);
TextDrawSetShadow(HUDTD4, 0);
TextDrawAlignment(HUDTD4, 1);
TextDrawColor(HUDTD4, -1);
TextDrawBackgroundColor(HUDTD4, -1);
TextDrawBoxColor(HUDTD4, -206);
TextDrawUseBox(HUDTD4, 1);
TextDrawSetProportional(HUDTD4, 1);
TextDrawSetSelectable(HUDTD4, 0);

HUDTD5 = TextDrawCreate(83.000000, 428.000000, "HUD:radar_tshirt");
TextDrawFont(HUDTD5, 4);
TextDrawLetterSize(HUDTD5, 0.600000, 2.000000);
TextDrawTextSize(HUDTD5, 14.000000, 11.500000);
TextDrawSetOutline(HUDTD5, 1);
TextDrawSetShadow(HUDTD5, 0);
TextDrawAlignment(HUDTD5, 1);
TextDrawColor(HUDTD5, -1);
TextDrawBackgroundColor(HUDTD5, -1);
TextDrawBoxColor(HUDTD5, -206);
TextDrawUseBox(HUDTD5, 1);
TextDrawSetProportional(HUDTD5, 1);
TextDrawSetSelectable(HUDTD5, 0);

HUDTD6 = TextDrawCreate(160.000000, 428.000000, "HUD:radar_datefood");
TextDrawFont(HUDTD6, 4);
TextDrawLetterSize(HUDTD6, 0.600000, 2.000000);
TextDrawTextSize(HUDTD6, 14.000000, 11.500000);
TextDrawSetOutline(HUDTD6, 1);
TextDrawSetShadow(HUDTD6, 0);
TextDrawAlignment(HUDTD6, 1);
TextDrawColor(HUDTD6, -1);
TextDrawBackgroundColor(HUDTD6, -1);
TextDrawBoxColor(HUDTD6, -206);
TextDrawUseBox(HUDTD6, 1);
TextDrawSetProportional(HUDTD6, 1);
TextDrawSetSelectable(HUDTD6, 0);

HUDTD7 = TextDrawCreate(213.000000, 428.000000, "HUD:radar_diner");
TextDrawFont(HUDTD7, 4);
TextDrawLetterSize(HUDTD7, 0.600000, 2.000000);
TextDrawTextSize(HUDTD7, 14.000000, 11.500000);
TextDrawSetOutline(HUDTD7, 1);
TextDrawSetShadow(HUDTD7, 0);
TextDrawAlignment(HUDTD7, 1);
TextDrawColor(HUDTD7, -1);
TextDrawBackgroundColor(HUDTD7, -1);
TextDrawBoxColor(HUDTD7, -206);
TextDrawUseBox(HUDTD7, 1);
TextDrawSetProportional(HUDTD7, 1);
TextDrawSetSelectable(HUDTD7, 0);


//Player Textdraws
HeathTD[playerid] = CreatePlayerTextDraw(playerid, 13.000000, 439.000000, "100");
PlayerTextDrawFont(playerid, HeathTD[playerid], 2);
PlayerTextDrawLetterSize(playerid, HeathTD[playerid], 0.241666, 0.899999);
PlayerTextDrawTextSize(playerid, HeathTD[playerid], 400.000000, 17.000000);
PlayerTextDrawSetOutline(playerid, HeathTD[playerid], 1);
PlayerTextDrawSetShadow(playerid, HeathTD[playerid], 0);
PlayerTextDrawAlignment(playerid, HeathTD[playerid], 2);
PlayerTextDrawColor(playerid, HeathTD[playerid], -1);
PlayerTextDrawBackgroundColor(playerid, HeathTD[playerid], 255);
PlayerTextDrawBoxColor(playerid, HeathTD[playerid], 50);
PlayerTextDrawUseBox(playerid, HeathTD[playerid], 0);
PlayerTextDrawSetProportional(playerid, HeathTD[playerid], 1);
PlayerTextDrawSetSelectable(playerid, HeathTD[playerid], 0);

ArmorTD[playerid] = CreatePlayerTextDraw(playerid, 91.000000, 439.000000, "100");
PlayerTextDrawFont(playerid, ArmorTD[playerid], 2);
PlayerTextDrawLetterSize(playerid, ArmorTD[playerid], 0.241666, 0.899999);
PlayerTextDrawTextSize(playerid, ArmorTD[playerid], 400.000000, 17.000000);
PlayerTextDrawSetOutline(playerid, ArmorTD[playerid], 1);
PlayerTextDrawSetShadow(playerid, ArmorTD[playerid], 0);
PlayerTextDrawAlignment(playerid, ArmorTD[playerid], 2);
PlayerTextDrawColor(playerid, ArmorTD[playerid], -1);
PlayerTextDrawBackgroundColor(playerid, ArmorTD[playerid], 255);
PlayerTextDrawBoxColor(playerid, ArmorTD[playerid], 50);
PlayerTextDrawUseBox(playerid, ArmorTD[playerid], 0);
PlayerTextDrawSetProportional(playerid, ArmorTD[playerid], 1);
PlayerTextDrawSetSelectable(playerid, ArmorTD[playerid], 0);

HungerTD[playerid] = CreatePlayerTextDraw(playerid, 168.000000, 439.000000, "100");
PlayerTextDrawFont(playerid, HungerTD[playerid], 2);
PlayerTextDrawLetterSize(playerid, HungerTD[playerid], 0.241666, 0.899999);
PlayerTextDrawTextSize(playerid, HungerTD[playerid], 400.000000, 17.000000);
PlayerTextDrawSetOutline(playerid, HungerTD[playerid], 1);
PlayerTextDrawSetShadow(playerid, HungerTD[playerid], 0);
PlayerTextDrawAlignment(playerid, HungerTD[playerid], 2);
PlayerTextDrawColor(playerid, HungerTD[playerid], -1);
PlayerTextDrawBackgroundColor(playerid, HungerTD[playerid], 255);
PlayerTextDrawBoxColor(playerid, HungerTD[playerid], 50);
PlayerTextDrawUseBox(playerid, HungerTD[playerid], 0);
PlayerTextDrawSetProportional(playerid, HungerTD[playerid], 1);
PlayerTextDrawSetSelectable(playerid, HungerTD[playerid], 0);

ThirstTD[playerid] = CreatePlayerTextDraw(playerid, 221.000000, 439.000000, "100");
PlayerTextDrawFont(playerid, ThirstTD[playerid], 2);
PlayerTextDrawLetterSize(playerid, ThirstTD[playerid], 0.241666, 0.899999);
PlayerTextDrawTextSize(playerid, ThirstTD[playerid], 400.000000, 17.000000);
PlayerTextDrawSetOutline(playerid, ThirstTD[playerid], 1);
PlayerTextDrawSetShadow(playerid, ThirstTD[playerid], 0);
PlayerTextDrawAlignment(playerid, ThirstTD[playerid], 2);
PlayerTextDrawColor(playerid, ThirstTD[playerid], -1);
PlayerTextDrawBackgroundColor(playerid, ThirstTD[playerid], 255);
PlayerTextDrawBoxColor(playerid, ThirstTD[playerid], 50);
PlayerTextDrawUseBox(playerid, ThirstTD[playerid], 0);
PlayerTextDrawSetProportional(playerid, ThirstTD[playerid], 1);
PlayerTextDrawSetSelectable(playerid, ThirstTD[playerid], 0);


/*Player Progress Bars
Requires "progress2" include by Southclaws
Download: https://github.com/Southclaws/progress2/releases */
ArmorBar[playerid] = CreatePlayerProgressBar(playerid, 101.000000, 429.000000, 59.500000, 10.000000, -1, 100.000000, 0);
SetPlayerProgressBarValue(playerid, ArmorBar[playerid], 50.000000);

HealthBar[playerid] = CreatePlayerProgressBar(playerid, 24.000000, 429.000000, 59.500000, 10.000000, -1962934017, 100.000000, 0);
SetPlayerProgressBarValue(playerid, HealthBar[playerid], 50.000000);

HungerBar[playerid] = CreatePlayerProgressBar(playerid, 178.000000, 429.000000, 36.000000, 10.500000, -764862721, 100.000000, 0);
SetPlayerProgressBarValue(playerid, HungerBar[playerid], 50.000000);

ThirstBar[playerid] = CreatePlayerProgressBar(playerid, 230.000000, 429.000000, 36.000000, 10.500000, 1687547391, 100.000000, 0);
SetPlayerProgressBarValue(playerid, ThirstBar[playerid], 50.000000);

