/*
This file was generated by Nickk's TextDraw editor script
Nickk888 is the author of the NTD script
*/

#include <a_samp>

new PlayerText:PlayerTD[MAX_PLAYERS][35];
new PlayerText:Bar_darah[MAX_PLAYERS];
new PlayerText:Bar_Armor[MAX_PLAYERS];
new PlayerText:Bar_Makan[MAX_PLAYERS];
new PlayerText:Bar_Harus[MAX_PLAYERS];
new PlayerText:Bar_Stres[MAX_PLAYERS];

public OnFilterScriptInit()
{
	return 1;
}

public OnFilterScriptExit()
{
	return 1;
}

public OnPlayerConnect(playerid)
{
	PlayerTD[playerid][0] = CreatePlayerTextDraw(playerid, 13.000000, 430.000000, "ld_dual:white");
	PlayerTextDrawFont(playerid, PlayerTD[playerid][0], 4);
	PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][0], 0.600000, 2.000000);
	PlayerTextDrawTextSize(playerid, PlayerTD[playerid][0], 11.500000, 13.500000);
	PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][0], 1);
	PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][0], 0);
	PlayerTextDrawAlignment(playerid, PlayerTD[playerid][0], 1);
	PlayerTextDrawColor(playerid, PlayerTD[playerid][0], -1962934017);
	PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][0], 255);
	PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][0], 50);
	PlayerTextDrawUseBox(playerid, PlayerTD[playerid][0], 1);
	PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][0], 1);
	PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][0], 0);

	PlayerTD[playerid][1] = CreatePlayerTextDraw(playerid, 12.000000, 425.000000, "ld_beat:chit");
	PlayerTextDrawFont(playerid, PlayerTD[playerid][1], 4);
	PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][1], 0.600000, 2.000000);
	PlayerTextDrawTextSize(playerid, PlayerTD[playerid][1], 4.500000, 12.500000);
	PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][1], 1);
	PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][1], 0);
	PlayerTextDrawAlignment(playerid, PlayerTD[playerid][1], 1);
	PlayerTextDrawColor(playerid, PlayerTD[playerid][1], -1962934017);
	PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][1], 255);
	PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][1], 50);
	PlayerTextDrawUseBox(playerid, PlayerTD[playerid][1], 1);
	PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][1], 1);
	PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][1], 0);

	PlayerTD[playerid][2] = CreatePlayerTextDraw(playerid, 12.000000, 435.000000, "ld_beat:chit");
	PlayerTextDrawFont(playerid, PlayerTD[playerid][2], 4);
	PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][2], 0.600000, 2.000000);
	PlayerTextDrawTextSize(playerid, PlayerTD[playerid][2], 4.500000, 12.500000);
	PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][2], 1);
	PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][2], 0);
	PlayerTextDrawAlignment(playerid, PlayerTD[playerid][2], 1);
	PlayerTextDrawColor(playerid, PlayerTD[playerid][2], -1962934017);
	PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][2], 255);
	PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][2], 50);
	PlayerTextDrawUseBox(playerid, PlayerTD[playerid][2], 1);
	PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][2], 1);
	PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][2], 0);

	PlayerTD[playerid][3] = CreatePlayerTextDraw(playerid, 21.000000, 435.000000, "ld_beat:chit");
	PlayerTextDrawFont(playerid, PlayerTD[playerid][3], 4);
	PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][3], 0.600000, 2.000000);
	PlayerTextDrawTextSize(playerid, PlayerTD[playerid][3], 4.500000, 12.500000);
	PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][3], 1);
	PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][3], 0);
	PlayerTextDrawAlignment(playerid, PlayerTD[playerid][3], 1);
	PlayerTextDrawColor(playerid, PlayerTD[playerid][3], -1962934017);
	PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][3], 255);
	PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][3], 50);
	PlayerTextDrawUseBox(playerid, PlayerTD[playerid][3], 1);
	PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][3], 1);
	PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][3], 0);

	PlayerTD[playerid][4] = CreatePlayerTextDraw(playerid, 21.000000, 424.000000, "ld_beat:chit");
	PlayerTextDrawFont(playerid, PlayerTD[playerid][4], 4);
	PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][4], 0.600000, 2.000000);
	PlayerTextDrawTextSize(playerid, PlayerTD[playerid][4], 4.500000, 15.000000);
	PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][4], 1);
	PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][4], 0);
	PlayerTextDrawAlignment(playerid, PlayerTD[playerid][4], 1);
	PlayerTextDrawColor(playerid, PlayerTD[playerid][4], -1962934017);
	PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][4], 255);
	PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][4], 50);
	PlayerTextDrawUseBox(playerid, PlayerTD[playerid][4], 1);
	PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][4], 1);
	PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][4], 0);

	PlayerTD[playerid][5] = CreatePlayerTextDraw(playerid, 14.000000, 446.000000, "ld_dual:white");
	PlayerTextDrawFont(playerid, PlayerTD[playerid][5], 4);
	PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][5], 0.600000, 2.000000);
	PlayerTextDrawTextSize(playerid, PlayerTD[playerid][5], 9.000000, -19.000000);
	PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][5], 1);
	PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][5], 0);
	PlayerTextDrawAlignment(playerid, PlayerTD[playerid][5], 1);
	PlayerTextDrawColor(playerid, PlayerTD[playerid][5], -1962934017);
	PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][5], 255);
	PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][5], 50);
	PlayerTextDrawUseBox(playerid, PlayerTD[playerid][5], 1);
	PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][5], 1);
	PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][5], 0);

	Bar_darah[playerid] = CreatePlayerTextDraw(playerid, 14.000000, 445.000000, "ld_dual:white");
	PlayerTextDrawFont(playerid, Bar_darah[playerid], 4);
	PlayerTextDrawLetterSize(playerid, Bar_darah[playerid], 0.600000, 2.000000);
	PlayerTextDrawTextSize(playerid, Bar_darah[playerid], 9.500000, -17.500000);
	PlayerTextDrawSetOutline(playerid, Bar_darah[playerid], 1);
	PlayerTextDrawSetShadow(playerid, Bar_darah[playerid], 0);
	PlayerTextDrawAlignment(playerid, Bar_darah[playerid], 1);
	PlayerTextDrawColor(playerid, Bar_darah[playerid], -16776961);
	PlayerTextDrawBackgroundColor(playerid, Bar_darah[playerid], 255);
	PlayerTextDrawBoxColor(playerid, Bar_darah[playerid], 50);
	PlayerTextDrawUseBox(playerid, Bar_darah[playerid], 1);
	PlayerTextDrawSetProportional(playerid, Bar_darah[playerid], 1);
	PlayerTextDrawSetSelectable(playerid, Bar_darah[playerid], 0);

	PlayerTD[playerid][6] = CreatePlayerTextDraw(playerid, 27.000000, 430.000000, "ld_dual:white");
	PlayerTextDrawFont(playerid, PlayerTD[playerid][6], 4);
	PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][6], 0.600000, 2.000000);
	PlayerTextDrawTextSize(playerid, PlayerTD[playerid][6], 11.500000, 13.500000);
	PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][6], 1);
	PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][6], 0);
	PlayerTextDrawAlignment(playerid, PlayerTD[playerid][6], 1);
	PlayerTextDrawColor(playerid, PlayerTD[playerid][6], -1061109505);
	PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][6], 255);
	PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][6], 50);
	PlayerTextDrawUseBox(playerid, PlayerTD[playerid][6], 1);
	PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][6], 1);
	PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][6], 0);

	PlayerTD[playerid][7] = CreatePlayerTextDraw(playerid, 26.000000, 425.000000, "ld_beat:chit");
	PlayerTextDrawFont(playerid, PlayerTD[playerid][7], 4);
	PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][7], 0.600000, 2.000000);
	PlayerTextDrawTextSize(playerid, PlayerTD[playerid][7], 4.500000, 12.500000);
	PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][7], 1);
	PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][7], 0);
	PlayerTextDrawAlignment(playerid, PlayerTD[playerid][7], 1);
	PlayerTextDrawColor(playerid, PlayerTD[playerid][7], -1061109505);
	PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][7], 255);
	PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][7], 50);
	PlayerTextDrawUseBox(playerid, PlayerTD[playerid][7], 1);
	PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][7], 1);
	PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][7], 0);

	PlayerTD[playerid][8] = CreatePlayerTextDraw(playerid, 26.000000, 435.000000, "ld_beat:chit");
	PlayerTextDrawFont(playerid, PlayerTD[playerid][8], 4);
	PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][8], 0.600000, 2.000000);
	PlayerTextDrawTextSize(playerid, PlayerTD[playerid][8], 4.500000, 12.500000);
	PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][8], 1);
	PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][8], 0);
	PlayerTextDrawAlignment(playerid, PlayerTD[playerid][8], 1);
	PlayerTextDrawColor(playerid, PlayerTD[playerid][8], -1061109505);
	PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][8], 255);
	PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][8], 50);
	PlayerTextDrawUseBox(playerid, PlayerTD[playerid][8], 1);
	PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][8], 1);
	PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][8], 0);

	PlayerTD[playerid][9] = CreatePlayerTextDraw(playerid, 35.000000, 435.000000, "ld_beat:chit");
	PlayerTextDrawFont(playerid, PlayerTD[playerid][9], 4);
	PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][9], 0.600000, 2.000000);
	PlayerTextDrawTextSize(playerid, PlayerTD[playerid][9], 4.500000, 12.500000);
	PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][9], 1);
	PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][9], 0);
	PlayerTextDrawAlignment(playerid, PlayerTD[playerid][9], 1);
	PlayerTextDrawColor(playerid, PlayerTD[playerid][9], -1061109505);
	PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][9], 255);
	PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][9], 50);
	PlayerTextDrawUseBox(playerid, PlayerTD[playerid][9], 1);
	PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][9], 1);
	PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][9], 0);

	PlayerTD[playerid][10] = CreatePlayerTextDraw(playerid, 35.000000, 424.000000, "ld_beat:chit");
	PlayerTextDrawFont(playerid, PlayerTD[playerid][10], 4);
	PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][10], 0.600000, 2.000000);
	PlayerTextDrawTextSize(playerid, PlayerTD[playerid][10], 4.500000, 15.000000);
	PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][10], 1);
	PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][10], 0);
	PlayerTextDrawAlignment(playerid, PlayerTD[playerid][10], 1);
	PlayerTextDrawColor(playerid, PlayerTD[playerid][10], -1061109505);
	PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][10], 255);
	PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][10], 50);
	PlayerTextDrawUseBox(playerid, PlayerTD[playerid][10], 1);
	PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][10], 1);
	PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][10], 0);

	PlayerTD[playerid][11] = CreatePlayerTextDraw(playerid, 28.000000, 446.000000, "ld_dual:white");
	PlayerTextDrawFont(playerid, PlayerTD[playerid][11], 4);
	PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][11], 0.600000, 2.000000);
	PlayerTextDrawTextSize(playerid, PlayerTD[playerid][11], 9.000000, -19.000000);
	PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][11], 1);
	PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][11], 0);
	PlayerTextDrawAlignment(playerid, PlayerTD[playerid][11], 1);
	PlayerTextDrawColor(playerid, PlayerTD[playerid][11], -1061109505);
	PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][11], 255);
	PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][11], 50);
	PlayerTextDrawUseBox(playerid, PlayerTD[playerid][11], 1);
	PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][11], 1);
	PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][11], 0);

	Bar_Armor[playerid] = CreatePlayerTextDraw(playerid, 28.000000, 445.000000, "ld_dual:white");
	PlayerTextDrawFont(playerid, Bar_Armor[playerid], 4);
	PlayerTextDrawLetterSize(playerid, Bar_Armor[playerid], 0.600000, 2.000000);
	PlayerTextDrawTextSize(playerid, Bar_Armor[playerid], 9.500000, -17.500000);
	PlayerTextDrawSetOutline(playerid, Bar_Armor[playerid], 1);
	PlayerTextDrawSetShadow(playerid, Bar_Armor[playerid], 0);
	PlayerTextDrawAlignment(playerid, Bar_Armor[playerid], 1);
	PlayerTextDrawColor(playerid, Bar_Armor[playerid], -1);
	PlayerTextDrawBackgroundColor(playerid, Bar_Armor[playerid], 255);
	PlayerTextDrawBoxColor(playerid, Bar_Armor[playerid], 50);
	PlayerTextDrawUseBox(playerid, Bar_Armor[playerid], 1);
	PlayerTextDrawSetProportional(playerid, Bar_Armor[playerid], 1);
	PlayerTextDrawSetSelectable(playerid, Bar_Armor[playerid], 0);

	PlayerTD[playerid][12] = CreatePlayerTextDraw(playerid, 42.000000, 430.000000, "ld_dual:white");
	PlayerTextDrawFont(playerid, PlayerTD[playerid][12], 4);
	PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][12], 0.600000, 2.000000);
	PlayerTextDrawTextSize(playerid, PlayerTD[playerid][12], 11.500000, 13.500000);
	PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][12], 1);
	PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][12], 0);
	PlayerTextDrawAlignment(playerid, PlayerTD[playerid][12], 1);
	PlayerTextDrawColor(playerid, PlayerTD[playerid][12], 9109759);
	PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][12], 255);
	PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][12], 50);
	PlayerTextDrawUseBox(playerid, PlayerTD[playerid][12], 1);
	PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][12], 1);
	PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][12], 0);

	PlayerTD[playerid][13] = CreatePlayerTextDraw(playerid, 41.000000, 425.000000, "ld_beat:chit");
	PlayerTextDrawFont(playerid, PlayerTD[playerid][13], 4);
	PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][13], 0.600000, 2.000000);
	PlayerTextDrawTextSize(playerid, PlayerTD[playerid][13], 4.500000, 12.500000);
	PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][13], 1);
	PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][13], 0);
	PlayerTextDrawAlignment(playerid, PlayerTD[playerid][13], 1);
	PlayerTextDrawColor(playerid, PlayerTD[playerid][13], 9109759);
	PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][13], 255);
	PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][13], 50);
	PlayerTextDrawUseBox(playerid, PlayerTD[playerid][13], 1);
	PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][13], 1);
	PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][13], 0);

	PlayerTD[playerid][14] = CreatePlayerTextDraw(playerid, 41.000000, 435.000000, "ld_beat:chit");
	PlayerTextDrawFont(playerid, PlayerTD[playerid][14], 4);
	PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][14], 0.600000, 2.000000);
	PlayerTextDrawTextSize(playerid, PlayerTD[playerid][14], 4.500000, 12.500000);
	PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][14], 1);
	PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][14], 0);
	PlayerTextDrawAlignment(playerid, PlayerTD[playerid][14], 1);
	PlayerTextDrawColor(playerid, PlayerTD[playerid][14], 9109759);
	PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][14], 255);
	PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][14], 50);
	PlayerTextDrawUseBox(playerid, PlayerTD[playerid][14], 1);
	PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][14], 1);
	PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][14], 0);

	PlayerTD[playerid][15] = CreatePlayerTextDraw(playerid, 50.000000, 435.000000, "ld_beat:chit");
	PlayerTextDrawFont(playerid, PlayerTD[playerid][15], 4);
	PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][15], 0.600000, 2.000000);
	PlayerTextDrawTextSize(playerid, PlayerTD[playerid][15], 4.500000, 12.500000);
	PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][15], 1);
	PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][15], 0);
	PlayerTextDrawAlignment(playerid, PlayerTD[playerid][15], 1);
	PlayerTextDrawColor(playerid, PlayerTD[playerid][15], 9109759);
	PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][15], 255);
	PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][15], 50);
	PlayerTextDrawUseBox(playerid, PlayerTD[playerid][15], 1);
	PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][15], 1);
	PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][15], 0);

	PlayerTD[playerid][16] = CreatePlayerTextDraw(playerid, 50.000000, 424.000000, "ld_beat:chit");
	PlayerTextDrawFont(playerid, PlayerTD[playerid][16], 4);
	PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][16], 0.600000, 2.000000);
	PlayerTextDrawTextSize(playerid, PlayerTD[playerid][16], 4.500000, 15.000000);
	PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][16], 1);
	PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][16], 0);
	PlayerTextDrawAlignment(playerid, PlayerTD[playerid][16], 1);
	PlayerTextDrawColor(playerid, PlayerTD[playerid][16], 9109759);
	PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][16], 255);
	PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][16], 50);
	PlayerTextDrawUseBox(playerid, PlayerTD[playerid][16], 1);
	PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][16], 1);
	PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][16], 0);

	PlayerTD[playerid][17] = CreatePlayerTextDraw(playerid, 43.000000, 446.000000, "ld_dual:white");
	PlayerTextDrawFont(playerid, PlayerTD[playerid][17], 4);
	PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][17], 0.600000, 2.000000);
	PlayerTextDrawTextSize(playerid, PlayerTD[playerid][17], 9.500000, -20.000000);
	PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][17], 1);
	PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][17], 0);
	PlayerTextDrawAlignment(playerid, PlayerTD[playerid][17], 1);
	PlayerTextDrawColor(playerid, PlayerTD[playerid][17], 9109759);
	PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][17], 255);
	PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][17], 50);
	PlayerTextDrawUseBox(playerid, PlayerTD[playerid][17], 1);
	PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][17], 1);
	PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][17], 0);

	Bar_Makan[playerid] = CreatePlayerTextDraw(playerid, 43.000000, 445.000000, "ld_dual:white");
	PlayerTextDrawFont(playerid, Bar_Makan[playerid], 4);
	PlayerTextDrawLetterSize(playerid, Bar_Makan[playerid], 0.600000, 2.000000);
	PlayerTextDrawTextSize(playerid, Bar_Makan[playerid], 9.500000, -17.500000);
	PlayerTextDrawSetOutline(playerid, Bar_Makan[playerid], 1);
	PlayerTextDrawSetShadow(playerid, Bar_Makan[playerid], 0);
	PlayerTextDrawAlignment(playerid, Bar_Makan[playerid], 1);
	PlayerTextDrawColor(playerid, Bar_Makan[playerid], 16711935);
	PlayerTextDrawBackgroundColor(playerid, Bar_Makan[playerid], 255);
	PlayerTextDrawBoxColor(playerid, Bar_Makan[playerid], 50);
	PlayerTextDrawUseBox(playerid, Bar_Makan[playerid], 1);
	PlayerTextDrawSetProportional(playerid, Bar_Makan[playerid], 1);
	PlayerTextDrawSetSelectable(playerid, Bar_Makan[playerid], 0);

	PlayerTD[playerid][18] = CreatePlayerTextDraw(playerid, 57.000000, 430.000000, "ld_dual:white");
	PlayerTextDrawFont(playerid, PlayerTD[playerid][18], 4);
	PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][18], 0.600000, 2.000000);
	PlayerTextDrawTextSize(playerid, PlayerTD[playerid][18], 11.500000, 13.500000);
	PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][18], 1);
	PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][18], 0);
	PlayerTextDrawAlignment(playerid, PlayerTD[playerid][18], 1);
	PlayerTextDrawColor(playerid, PlayerTD[playerid][18], 35839);
	PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][18], 255);
	PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][18], 50);
	PlayerTextDrawUseBox(playerid, PlayerTD[playerid][18], 1);
	PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][18], 1);
	PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][18], 0);

	PlayerTD[playerid][19] = CreatePlayerTextDraw(playerid, 56.000000, 425.000000, "ld_beat:chit");
	PlayerTextDrawFont(playerid, PlayerTD[playerid][19], 4);
	PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][19], 0.600000, 2.000000);
	PlayerTextDrawTextSize(playerid, PlayerTD[playerid][19], 4.500000, 12.500000);
	PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][19], 1);
	PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][19], 0);
	PlayerTextDrawAlignment(playerid, PlayerTD[playerid][19], 1);
	PlayerTextDrawColor(playerid, PlayerTD[playerid][19], 35839);
	PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][19], 255);
	PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][19], 50);
	PlayerTextDrawUseBox(playerid, PlayerTD[playerid][19], 1);
	PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][19], 1);
	PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][19], 0);

	PlayerTD[playerid][20] = CreatePlayerTextDraw(playerid, 56.000000, 435.000000, "ld_beat:chit");
	PlayerTextDrawFont(playerid, PlayerTD[playerid][20], 4);
	PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][20], 0.600000, 2.000000);
	PlayerTextDrawTextSize(playerid, PlayerTD[playerid][20], 4.500000, 12.500000);
	PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][20], 1);
	PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][20], 0);
	PlayerTextDrawAlignment(playerid, PlayerTD[playerid][20], 1);
	PlayerTextDrawColor(playerid, PlayerTD[playerid][20], 35839);
	PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][20], 255);
	PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][20], 50);
	PlayerTextDrawUseBox(playerid, PlayerTD[playerid][20], 1);
	PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][20], 1);
	PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][20], 0);

	PlayerTD[playerid][21] = CreatePlayerTextDraw(playerid, 65.000000, 424.000000, "ld_beat:chit");
	PlayerTextDrawFont(playerid, PlayerTD[playerid][21], 4);
	PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][21], 0.600000, 2.000000);
	PlayerTextDrawTextSize(playerid, PlayerTD[playerid][21], 4.500000, 15.000000);
	PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][21], 1);
	PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][21], 0);
	PlayerTextDrawAlignment(playerid, PlayerTD[playerid][21], 1);
	PlayerTextDrawColor(playerid, PlayerTD[playerid][21], 35839);
	PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][21], 255);
	PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][21], 50);
	PlayerTextDrawUseBox(playerid, PlayerTD[playerid][21], 1);
	PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][21], 1);
	PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][21], 0);

	PlayerTD[playerid][22] = CreatePlayerTextDraw(playerid, 65.000000, 435.000000, "ld_beat:chit");
	PlayerTextDrawFont(playerid, PlayerTD[playerid][22], 4);
	PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][22], 0.600000, 2.000000);
	PlayerTextDrawTextSize(playerid, PlayerTD[playerid][22], 4.500000, 12.500000);
	PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][22], 1);
	PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][22], 0);
	PlayerTextDrawAlignment(playerid, PlayerTD[playerid][22], 1);
	PlayerTextDrawColor(playerid, PlayerTD[playerid][22], 35839);
	PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][22], 255);
	PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][22], 50);
	PlayerTextDrawUseBox(playerid, PlayerTD[playerid][22], 1);
	PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][22], 1);
	PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][22], 0);

	PlayerTD[playerid][23] = CreatePlayerTextDraw(playerid, 58.000000, 446.000000, "ld_dual:white");
	PlayerTextDrawFont(playerid, PlayerTD[playerid][23], 4);
	PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][23], 0.600000, 2.000000);
	PlayerTextDrawTextSize(playerid, PlayerTD[playerid][23], 9.500000, -20.000000);
	PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][23], 1);
	PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][23], 0);
	PlayerTextDrawAlignment(playerid, PlayerTD[playerid][23], 1);
	PlayerTextDrawColor(playerid, PlayerTD[playerid][23], 35839);
	PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][23], 255);
	PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][23], 50);
	PlayerTextDrawUseBox(playerid, PlayerTD[playerid][23], 1);
	PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][23], 1);
	PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][23], 0);

	Bar_Harus[playerid] = CreatePlayerTextDraw(playerid, 58.000000, 445.000000, "ld_dual:white");
	PlayerTextDrawFont(playerid, Bar_Harus[playerid], 4);
	PlayerTextDrawLetterSize(playerid, Bar_Harus[playerid], 0.600000, 2.000000);
	PlayerTextDrawTextSize(playerid, Bar_Harus[playerid], 9.500000, -17.500000);
	PlayerTextDrawSetOutline(playerid, Bar_Harus[playerid], 1);
	PlayerTextDrawSetShadow(playerid, Bar_Harus[playerid], 0);
	PlayerTextDrawAlignment(playerid, Bar_Harus[playerid], 1);
	PlayerTextDrawColor(playerid, Bar_Harus[playerid], 65535);
	PlayerTextDrawBackgroundColor(playerid, Bar_Harus[playerid], 255);
	PlayerTextDrawBoxColor(playerid, Bar_Harus[playerid], 50);
	PlayerTextDrawUseBox(playerid, Bar_Harus[playerid], 1);
	PlayerTextDrawSetProportional(playerid, Bar_Harus[playerid], 1);
	PlayerTextDrawSetSelectable(playerid, Bar_Harus[playerid], 0);

	PlayerTD[playerid][24] = CreatePlayerTextDraw(playerid, 72.000000, 430.000000, "ld_dual:white");
	PlayerTextDrawFont(playerid, PlayerTD[playerid][24], 4);
	PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][24], 0.600000, 2.000000);
	PlayerTextDrawTextSize(playerid, PlayerTD[playerid][24], 11.500000, 13.500000);
	PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][24], 1);
	PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][24], 0);
	PlayerTextDrawAlignment(playerid, PlayerTD[playerid][24], 1);
	PlayerTextDrawColor(playerid, PlayerTD[playerid][24], -764862721);
	PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][24], 255);
	PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][24], 50);
	PlayerTextDrawUseBox(playerid, PlayerTD[playerid][24], 1);
	PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][24], 1);
	PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][24], 0);

	PlayerTD[playerid][25] = CreatePlayerTextDraw(playerid, 71.000000, 425.000000, "ld_beat:chit");
	PlayerTextDrawFont(playerid, PlayerTD[playerid][25], 4);
	PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][25], 0.600000, 2.000000);
	PlayerTextDrawTextSize(playerid, PlayerTD[playerid][25], 4.500000, 12.500000);
	PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][25], 1);
	PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][25], 0);
	PlayerTextDrawAlignment(playerid, PlayerTD[playerid][25], 1);
	PlayerTextDrawColor(playerid, PlayerTD[playerid][25], -764862721);
	PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][25], 255);
	PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][25], 50);
	PlayerTextDrawUseBox(playerid, PlayerTD[playerid][25], 1);
	PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][25], 1);
	PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][25], 0);

	PlayerTD[playerid][26] = CreatePlayerTextDraw(playerid, 71.000000, 435.000000, "ld_beat:chit");
	PlayerTextDrawFont(playerid, PlayerTD[playerid][26], 4);
	PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][26], 0.600000, 2.000000);
	PlayerTextDrawTextSize(playerid, PlayerTD[playerid][26], 4.500000, 12.500000);
	PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][26], 1);
	PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][26], 0);
	PlayerTextDrawAlignment(playerid, PlayerTD[playerid][26], 1);
	PlayerTextDrawColor(playerid, PlayerTD[playerid][26], -764862721);
	PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][26], 255);
	PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][26], 50);
	PlayerTextDrawUseBox(playerid, PlayerTD[playerid][26], 1);
	PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][26], 1);
	PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][26], 0);

	PlayerTD[playerid][27] = CreatePlayerTextDraw(playerid, 80.000000, 424.000000, "ld_beat:chit");
	PlayerTextDrawFont(playerid, PlayerTD[playerid][27], 4);
	PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][27], 0.600000, 2.000000);
	PlayerTextDrawTextSize(playerid, PlayerTD[playerid][27], 4.500000, 15.000000);
	PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][27], 1);
	PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][27], 0);
	PlayerTextDrawAlignment(playerid, PlayerTD[playerid][27], 1);
	PlayerTextDrawColor(playerid, PlayerTD[playerid][27], -764862721);
	PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][27], 255);
	PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][27], 50);
	PlayerTextDrawUseBox(playerid, PlayerTD[playerid][27], 1);
	PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][27], 1);
	PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][27], 0);

	PlayerTD[playerid][28] = CreatePlayerTextDraw(playerid, 80.000000, 435.000000, "ld_beat:chit");
	PlayerTextDrawFont(playerid, PlayerTD[playerid][28], 4);
	PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][28], 0.600000, 2.000000);
	PlayerTextDrawTextSize(playerid, PlayerTD[playerid][28], 4.500000, 12.500000);
	PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][28], 1);
	PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][28], 0);
	PlayerTextDrawAlignment(playerid, PlayerTD[playerid][28], 1);
	PlayerTextDrawColor(playerid, PlayerTD[playerid][28], -764862721);
	PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][28], 255);
	PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][28], 50);
	PlayerTextDrawUseBox(playerid, PlayerTD[playerid][28], 1);
	PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][28], 1);
	PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][28], 0);

	PlayerTD[playerid][29] = CreatePlayerTextDraw(playerid, 73.000000, 446.000000, "ld_dual:white");
	PlayerTextDrawFont(playerid, PlayerTD[playerid][29], 4);
	PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][29], 0.600000, 2.000000);
	PlayerTextDrawTextSize(playerid, PlayerTD[playerid][29], 9.500000, -20.000000);
	PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][29], 1);
	PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][29], 0);
	PlayerTextDrawAlignment(playerid, PlayerTD[playerid][29], 1);
	PlayerTextDrawColor(playerid, PlayerTD[playerid][29], -764862721);
	PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][29], 255);
	PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][29], 50);
	PlayerTextDrawUseBox(playerid, PlayerTD[playerid][29], 1);
	PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][29], 1);
	PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][29], 0);

	Bar_Stres[playerid] = CreatePlayerTextDraw(playerid, 73.000000, 445.000000, "ld_dual:white");
	PlayerTextDrawFont(playerid, Bar_Stres[playerid], 4);
	PlayerTextDrawLetterSize(playerid, Bar_Stres[playerid], 0.600000, 2.000000);
	PlayerTextDrawTextSize(playerid, Bar_Stres[playerid], 9.500000, -17.500000);
	PlayerTextDrawSetOutline(playerid, Bar_Stres[playerid], 1);
	PlayerTextDrawSetShadow(playerid, Bar_Stres[playerid], 0);
	PlayerTextDrawAlignment(playerid, Bar_Stres[playerid], 1);
	PlayerTextDrawColor(playerid, Bar_Stres[playerid], 16777215);
	PlayerTextDrawBackgroundColor(playerid, Bar_Stres[playerid], 255);
	PlayerTextDrawBoxColor(playerid, Bar_Stres[playerid], 50);
	PlayerTextDrawUseBox(playerid, Bar_Stres[playerid], 1);
	PlayerTextDrawSetProportional(playerid, Bar_Stres[playerid], 1);
	PlayerTextDrawSetSelectable(playerid, Bar_Stres[playerid], 0);

	PlayerTD[playerid][30] = CreatePlayerTextDraw(playerid, 15.000000, 431.000000, "HUD:radar_girlfriend");
	PlayerTextDrawFont(playerid, PlayerTD[playerid][30], 4);
	PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][30], 0.600000, 2.000000);
	PlayerTextDrawTextSize(playerid, PlayerTD[playerid][30], 7.000000, 9.000000);
	PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][30], 1);
	PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][30], 0);
	PlayerTextDrawAlignment(playerid, PlayerTD[playerid][30], 1);
	PlayerTextDrawColor(playerid, PlayerTD[playerid][30], -16776961);
	PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][30], 255);
	PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][30], 50);
	PlayerTextDrawUseBox(playerid, PlayerTD[playerid][30], 1);
	PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][30], 1);
	PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][30], 0);

	PlayerTD[playerid][31] = CreatePlayerTextDraw(playerid, 29.000000, 431.000000, "HUD:radar_tshirt");
	PlayerTextDrawFont(playerid, PlayerTD[playerid][31], 4);
	PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][31], 0.600000, 2.000000);
	PlayerTextDrawTextSize(playerid, PlayerTD[playerid][31], 7.000000, 9.000000);
	PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][31], 1);
	PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][31], 0);
	PlayerTextDrawAlignment(playerid, PlayerTD[playerid][31], 1);
	PlayerTextDrawColor(playerid, PlayerTD[playerid][31], -1);
	PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][31], 255);
	PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][31], 50);
	PlayerTextDrawUseBox(playerid, PlayerTD[playerid][31], 1);
	PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][31], 1);
	PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][31], 0);

	PlayerTD[playerid][32] = CreatePlayerTextDraw(playerid, 45.000000, 432.000000, "HUD:radar_burgershot");
	PlayerTextDrawFont(playerid, PlayerTD[playerid][32], 4);
	PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][32], 0.600000, 2.000000);
	PlayerTextDrawTextSize(playerid, PlayerTD[playerid][32], 5.500000, 7.500000);
	PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][32], 1);
	PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][32], 0);
	PlayerTextDrawAlignment(playerid, PlayerTD[playerid][32], 1);
	PlayerTextDrawColor(playerid, PlayerTD[playerid][32], 16711935);
	PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][32], 255);
	PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][32], 50);
	PlayerTextDrawUseBox(playerid, PlayerTD[playerid][32], 1);
	PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][32], 1);
	PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][32], 0);

	PlayerTD[playerid][33] = CreatePlayerTextDraw(playerid, 60.000000, 432.000000, "HUD:radar_diner");
	PlayerTextDrawFont(playerid, PlayerTD[playerid][33], 4);
	PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][33], 0.600000, 2.000000);
	PlayerTextDrawTextSize(playerid, PlayerTD[playerid][33], 5.500000, 7.500000);
	PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][33], 1);
	PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][33], 0);
	PlayerTextDrawAlignment(playerid, PlayerTD[playerid][33], 1);
	PlayerTextDrawColor(playerid, PlayerTD[playerid][33], 1097458175);
	PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][33], 255);
	PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][33], 50);
	PlayerTextDrawUseBox(playerid, PlayerTD[playerid][33], 1);
	PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][33], 1);
	PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][33], 0);

	PlayerTD[playerid][34] = CreatePlayerTextDraw(playerid, 75.000000, 432.000000, "HUD:radar_centre");
	PlayerTextDrawFont(playerid, PlayerTD[playerid][34], 4);
	PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][34], 0.600000, 2.000000);
	PlayerTextDrawTextSize(playerid, PlayerTD[playerid][34], 5.500000, 7.500000);
	PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][34], 1);
	PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][34], 0);
	PlayerTextDrawAlignment(playerid, PlayerTD[playerid][34], 1);
	PlayerTextDrawColor(playerid, PlayerTD[playerid][34], 16777215);
	PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][34], 255);
	PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][34], 50);
	PlayerTextDrawUseBox(playerid, PlayerTD[playerid][34], 1);
	PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][34], 1);
	PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][34], 0);

	return 1;
}

public OnPlayerDisconnect(playerid, reason)
{
	PlayerTextDrawDestroy(playerid, PlayerTD[playerid][0]);
	PlayerTextDrawDestroy(playerid, PlayerTD[playerid][1]);
	PlayerTextDrawDestroy(playerid, PlayerTD[playerid][2]);
	PlayerTextDrawDestroy(playerid, PlayerTD[playerid][3]);
	PlayerTextDrawDestroy(playerid, PlayerTD[playerid][4]);
	PlayerTextDrawDestroy(playerid, PlayerTD[playerid][5]);
	PlayerTextDrawDestroy(playerid, PlayerTD[playerid][6]);
	PlayerTextDrawDestroy(playerid, PlayerTD[playerid][7]);
	PlayerTextDrawDestroy(playerid, PlayerTD[playerid][8]);
	PlayerTextDrawDestroy(playerid, PlayerTD[playerid][9]);
	PlayerTextDrawDestroy(playerid, PlayerTD[playerid][10]);
	PlayerTextDrawDestroy(playerid, PlayerTD[playerid][11]);
	PlayerTextDrawDestroy(playerid, PlayerTD[playerid][12]);
	PlayerTextDrawDestroy(playerid, PlayerTD[playerid][13]);
	PlayerTextDrawDestroy(playerid, PlayerTD[playerid][14]);
	PlayerTextDrawDestroy(playerid, PlayerTD[playerid][15]);
	PlayerTextDrawDestroy(playerid, PlayerTD[playerid][16]);
	PlayerTextDrawDestroy(playerid, PlayerTD[playerid][17]);
	PlayerTextDrawDestroy(playerid, PlayerTD[playerid][18]);
	PlayerTextDrawDestroy(playerid, PlayerTD[playerid][19]);
	PlayerTextDrawDestroy(playerid, PlayerTD[playerid][20]);
	PlayerTextDrawDestroy(playerid, PlayerTD[playerid][21]);
	PlayerTextDrawDestroy(playerid, PlayerTD[playerid][22]);
	PlayerTextDrawDestroy(playerid, PlayerTD[playerid][23]);
	PlayerTextDrawDestroy(playerid, PlayerTD[playerid][24]);
	PlayerTextDrawDestroy(playerid, PlayerTD[playerid][25]);
	PlayerTextDrawDestroy(playerid, PlayerTD[playerid][26]);
	PlayerTextDrawDestroy(playerid, PlayerTD[playerid][27]);
	PlayerTextDrawDestroy(playerid, PlayerTD[playerid][28]);
	PlayerTextDrawDestroy(playerid, PlayerTD[playerid][29]);
	PlayerTextDrawDestroy(playerid, PlayerTD[playerid][30]);
	PlayerTextDrawDestroy(playerid, PlayerTD[playerid][31]);
	PlayerTextDrawDestroy(playerid, PlayerTD[playerid][32]);
	PlayerTextDrawDestroy(playerid, PlayerTD[playerid][33]);
	PlayerTextDrawDestroy(playerid, PlayerTD[playerid][34]);
	PlayerTextDrawDestroy(playerid, Bar_darah[playerid]);
	PlayerTextDrawDestroy(playerid, Bar_Armor[playerid]);
	PlayerTextDrawDestroy(playerid, Bar_Makan[playerid]);
	PlayerTextDrawDestroy(playerid, Bar_Harus[playerid]);
	PlayerTextDrawDestroy(playerid, Bar_Stres[playerid]);
	return 1;
}

public OnPlayerCommandText(playerid, cmdtext[])
{
	if(!strcmp(cmdtext, "/tdtest", true))
	{
		PlayerTextDrawShow(playerid, PlayerTD[playerid][0]);
		PlayerTextDrawShow(playerid, PlayerTD[playerid][1]);
		PlayerTextDrawShow(playerid, PlayerTD[playerid][2]);
		PlayerTextDrawShow(playerid, PlayerTD[playerid][3]);
		PlayerTextDrawShow(playerid, PlayerTD[playerid][4]);
		PlayerTextDrawShow(playerid, PlayerTD[playerid][5]);
		PlayerTextDrawShow(playerid, PlayerTD[playerid][6]);
		PlayerTextDrawShow(playerid, PlayerTD[playerid][7]);
		PlayerTextDrawShow(playerid, PlayerTD[playerid][8]);
		PlayerTextDrawShow(playerid, PlayerTD[playerid][9]);
		PlayerTextDrawShow(playerid, PlayerTD[playerid][10]);
		PlayerTextDrawShow(playerid, PlayerTD[playerid][11]);
		PlayerTextDrawShow(playerid, PlayerTD[playerid][12]);
		PlayerTextDrawShow(playerid, PlayerTD[playerid][13]);
		PlayerTextDrawShow(playerid, PlayerTD[playerid][14]);
		PlayerTextDrawShow(playerid, PlayerTD[playerid][15]);
		PlayerTextDrawShow(playerid, PlayerTD[playerid][16]);
		PlayerTextDrawShow(playerid, PlayerTD[playerid][17]);
		PlayerTextDrawShow(playerid, PlayerTD[playerid][18]);
		PlayerTextDrawShow(playerid, PlayerTD[playerid][19]);
		PlayerTextDrawShow(playerid, PlayerTD[playerid][20]);
		PlayerTextDrawShow(playerid, PlayerTD[playerid][21]);
		PlayerTextDrawShow(playerid, PlayerTD[playerid][22]);
		PlayerTextDrawShow(playerid, PlayerTD[playerid][23]);
		PlayerTextDrawShow(playerid, PlayerTD[playerid][24]);
		PlayerTextDrawShow(playerid, PlayerTD[playerid][25]);
		PlayerTextDrawShow(playerid, PlayerTD[playerid][26]);
		PlayerTextDrawShow(playerid, PlayerTD[playerid][27]);
		PlayerTextDrawShow(playerid, PlayerTD[playerid][28]);
		PlayerTextDrawShow(playerid, PlayerTD[playerid][29]);
		PlayerTextDrawShow(playerid, PlayerTD[playerid][30]);
		PlayerTextDrawShow(playerid, PlayerTD[playerid][31]);
		PlayerTextDrawShow(playerid, PlayerTD[playerid][32]);
		PlayerTextDrawShow(playerid, PlayerTD[playerid][33]);
		PlayerTextDrawShow(playerid, PlayerTD[playerid][34]);
		PlayerTextDrawShow(playerid, Bar_darah[playerid]);
		PlayerTextDrawShow(playerid, Bar_Armor[playerid]);
		PlayerTextDrawShow(playerid, Bar_Makan[playerid]);
		PlayerTextDrawShow(playerid, Bar_Harus[playerid]);
		PlayerTextDrawShow(playerid, Bar_Stres[playerid]);
		return 1;
	}
	return 0;
}
