/*
This file was generated by Nickk's TextDraw editor script
Nickk888 is the author of the NTD script
*/

//Variables
new Text:PublicTD[10];
new Text:DarahTD;
new Text:ArmorTD;
new Text:LaparTD;
new Text:HausTD;
new Text:StressTD;

//Textdraws
PublicTD[0] = TextDrawCreate(10.000000, 415.000000, "LD_SPAC:white");
TextDrawFont(PublicTD[0], 4);
TextDrawLetterSize(PublicTD[0], 0.600000, 2.000000);
TextDrawTextSize(PublicTD[0], 23.000000, 25.000000);
TextDrawSetOutline(PublicTD[0], 1);
TextDrawSetShadow(PublicTD[0], 0);
TextDrawAlignment(PublicTD[0], 1);
TextDrawColor(PublicTD[0], -1);
TextDrawBackgroundColor(PublicTD[0], -1);
TextDrawBoxColor(PublicTD[0], 50);
TextDrawUseBox(PublicTD[0], 1);
TextDrawSetProportional(PublicTD[0], 1);
TextDrawSetSelectable(PublicTD[0], 0);

PublicTD[1] = TextDrawCreate(35.000000, 415.000000, "LD_SPAC:white");
TextDrawFont(PublicTD[1], 4);
TextDrawLetterSize(PublicTD[1], 0.600000, 2.000000);
TextDrawTextSize(PublicTD[1], 23.000000, 25.000000);
TextDrawSetOutline(PublicTD[1], 1);
TextDrawSetShadow(PublicTD[1], 0);
TextDrawAlignment(PublicTD[1], 1);
TextDrawColor(PublicTD[1], -1);
TextDrawBackgroundColor(PublicTD[1], -1);
TextDrawBoxColor(PublicTD[1], 50);
TextDrawUseBox(PublicTD[1], 1);
TextDrawSetProportional(PublicTD[1], 1);
TextDrawSetSelectable(PublicTD[1], 0);

PublicTD[2] = TextDrawCreate(60.000000, 415.000000, "LD_SPAC:white");
TextDrawFont(PublicTD[2], 4);
TextDrawLetterSize(PublicTD[2], 0.600000, 2.000000);
TextDrawTextSize(PublicTD[2], 23.000000, 25.000000);
TextDrawSetOutline(PublicTD[2], 1);
TextDrawSetShadow(PublicTD[2], 0);
TextDrawAlignment(PublicTD[2], 1);
TextDrawColor(PublicTD[2], -1);
TextDrawBackgroundColor(PublicTD[2], -1);
TextDrawBoxColor(PublicTD[2], 50);
TextDrawUseBox(PublicTD[2], 1);
TextDrawSetProportional(PublicTD[2], 1);
TextDrawSetSelectable(PublicTD[2], 0);

PublicTD[3] = TextDrawCreate(85.000000, 415.000000, "LD_SPAC:white");
TextDrawFont(PublicTD[3], 4);
TextDrawLetterSize(PublicTD[3], 0.600000, 2.000000);
TextDrawTextSize(PublicTD[3], 23.000000, 25.000000);
TextDrawSetOutline(PublicTD[3], 1);
TextDrawSetShadow(PublicTD[3], 0);
TextDrawAlignment(PublicTD[3], 1);
TextDrawColor(PublicTD[3], -1);
TextDrawBackgroundColor(PublicTD[3], -1);
TextDrawBoxColor(PublicTD[3], 50);
TextDrawUseBox(PublicTD[3], 1);
TextDrawSetProportional(PublicTD[3], 1);
TextDrawSetSelectable(PublicTD[3], 0);

PublicTD[4] = TextDrawCreate(110.000000, 415.000000, "LD_SPAC:white");
TextDrawFont(PublicTD[4], 4);
TextDrawLetterSize(PublicTD[4], 0.600000, 2.000000);
TextDrawTextSize(PublicTD[4], 23.000000, 25.000000);
TextDrawSetOutline(PublicTD[4], 1);
TextDrawSetShadow(PublicTD[4], 0);
TextDrawAlignment(PublicTD[4], 1);
TextDrawColor(PublicTD[4], -1);
TextDrawBackgroundColor(PublicTD[4], -1);
TextDrawBoxColor(PublicTD[4], 50);
TextDrawUseBox(PublicTD[4], 1);
TextDrawSetProportional(PublicTD[4], 1);
TextDrawSetSelectable(PublicTD[4], 0);

DarahTD = TextDrawCreate(11.500000, 417.200012, "LD_SPAC:white");
TextDrawFont(DarahTD, 4);
TextDrawLetterSize(DarahTD, 0.600000, 2.000000);
TextDrawTextSize(DarahTD, 20.000000, 20.000000);
TextDrawSetOutline(DarahTD, 1);
TextDrawSetShadow(DarahTD, 0);
TextDrawAlignment(DarahTD, 1);
TextDrawColor(DarahTD, -16776961);
TextDrawBackgroundColor(DarahTD, -1);
TextDrawBoxColor(DarahTD, 50);
TextDrawUseBox(DarahTD, 1);
TextDrawSetProportional(DarahTD, 1);
TextDrawSetSelectable(DarahTD, 0);

ArmorTD = TextDrawCreate(36.500000, 417.200012, "LD_SPAC:white");
TextDrawFont(ArmorTD, 4);
TextDrawLetterSize(ArmorTD, 0.600000, 2.000000);
TextDrawTextSize(ArmorTD, 20.000000, 20.000000);
TextDrawSetOutline(ArmorTD, 1);
TextDrawSetShadow(ArmorTD, 0);
TextDrawAlignment(ArmorTD, 1);
TextDrawColor(ArmorTD, 1296911871);
TextDrawBackgroundColor(ArmorTD, -1);
TextDrawBoxColor(ArmorTD, 50);
TextDrawUseBox(ArmorTD, 1);
TextDrawSetProportional(ArmorTD, 1);
TextDrawSetSelectable(ArmorTD, 0);

LaparTD = TextDrawCreate(61.700000, 417.200012, "LD_SPAC:white");
TextDrawFont(LaparTD, 4);
TextDrawLetterSize(LaparTD, 0.600000, 2.000000);
TextDrawTextSize(LaparTD, 20.000000, 20.000000);
TextDrawSetOutline(LaparTD, 1);
TextDrawSetShadow(LaparTD, 0);
TextDrawAlignment(LaparTD, 1);
TextDrawColor(LaparTD, -2686721);
TextDrawBackgroundColor(LaparTD, -1);
TextDrawBoxColor(LaparTD, 50);
TextDrawUseBox(LaparTD, 1);
TextDrawSetProportional(LaparTD, 1);
TextDrawSetSelectable(LaparTD, 0);

HausTD = TextDrawCreate(86.500000, 417.200012, "LD_SPAC:white");
TextDrawFont(HausTD, 4);
TextDrawLetterSize(HausTD, 0.600000, 2.000000);
TextDrawTextSize(HausTD, 20.000000, 20.000000);
TextDrawSetOutline(HausTD, 1);
TextDrawSetShadow(HausTD, 0);
TextDrawAlignment(HausTD, 1);
TextDrawColor(HausTD, 1687547391);
TextDrawBackgroundColor(HausTD, -1);
TextDrawBoxColor(HausTD, 50);
TextDrawUseBox(HausTD, 1);
TextDrawSetProportional(HausTD, 1);
TextDrawSetSelectable(HausTD, 0);

StressTD = TextDrawCreate(111.500000, 417.200012, "LD_SPAC:white");
TextDrawFont(StressTD, 4);
TextDrawLetterSize(StressTD, 0.600000, 2.000000);
TextDrawTextSize(StressTD, 20.000000, 20.000000);
TextDrawSetOutline(StressTD, 1);
TextDrawSetShadow(StressTD, 0);
TextDrawAlignment(StressTD, 1);
TextDrawColor(StressTD, -1962934017);
TextDrawBackgroundColor(StressTD, -1);
TextDrawBoxColor(StressTD, 50);
TextDrawUseBox(StressTD, 1);
TextDrawSetProportional(StressTD, 1);
TextDrawSetSelectable(StressTD, 0);

PublicTD[5] = TextDrawCreate(14.500000, 420.000000, "hud:radar_girlfriend");
TextDrawFont(PublicTD[5], 4);
TextDrawLetterSize(PublicTD[5], 0.600000, 2.000000);
TextDrawTextSize(PublicTD[5], 14.000000, 14.000000);
TextDrawSetOutline(PublicTD[5], 1);
TextDrawSetShadow(PublicTD[5], 0);
TextDrawAlignment(PublicTD[5], 1);
TextDrawColor(PublicTD[5], -1);
TextDrawBackgroundColor(PublicTD[5], 255);
TextDrawBoxColor(PublicTD[5], 50);
TextDrawUseBox(PublicTD[5], 1);
TextDrawSetProportional(PublicTD[5], 1);
TextDrawSetSelectable(PublicTD[5], 0);

PublicTD[6] = TextDrawCreate(39.000000, 419.000000, "hud:radar_tshirt");
TextDrawFont(PublicTD[6], 4);
TextDrawLetterSize(PublicTD[6], 0.600000, 2.000000);
TextDrawTextSize(PublicTD[6], 16.000000, 16.000000);
TextDrawSetOutline(PublicTD[6], 1);
TextDrawSetShadow(PublicTD[6], 0);
TextDrawAlignment(PublicTD[6], 1);
TextDrawColor(PublicTD[6], -1);
TextDrawBackgroundColor(PublicTD[6], 255);
TextDrawBoxColor(PublicTD[6], 50);
TextDrawUseBox(PublicTD[6], 1);
TextDrawSetProportional(PublicTD[6], 1);
TextDrawSetSelectable(PublicTD[6], 0);

PublicTD[7] = TextDrawCreate(64.500000, 419.500000, "hud:radar_burgerShot");
TextDrawFont(PublicTD[7], 4);
TextDrawLetterSize(PublicTD[7], 0.600000, 2.000000);
TextDrawTextSize(PublicTD[7], 15.000000, 15.000000);
TextDrawSetOutline(PublicTD[7], 1);
TextDrawSetShadow(PublicTD[7], 0);
TextDrawAlignment(PublicTD[7], 1);
TextDrawColor(PublicTD[7], -1);
TextDrawBackgroundColor(PublicTD[7], 255);
TextDrawBoxColor(PublicTD[7], 50);
TextDrawUseBox(PublicTD[7], 1);
TextDrawSetProportional(PublicTD[7], 1);
TextDrawSetSelectable(PublicTD[7], 0);

PublicTD[8] = TextDrawCreate(89.000000, 419.500000, "hud:radar_diner");
TextDrawFont(PublicTD[8], 4);
TextDrawLetterSize(PublicTD[8], 0.600000, 2.000000);
TextDrawTextSize(PublicTD[8], 15.000000, 15.000000);
TextDrawSetOutline(PublicTD[8], 1);
TextDrawSetShadow(PublicTD[8], 0);
TextDrawAlignment(PublicTD[8], 1);
TextDrawColor(PublicTD[8], -1);
TextDrawBackgroundColor(PublicTD[8], 255);
TextDrawBoxColor(PublicTD[8], 50);
TextDrawUseBox(PublicTD[8], 1);
TextDrawSetProportional(PublicTD[8], 1);
TextDrawSetSelectable(PublicTD[8], 0);

PublicTD[9] = TextDrawCreate(114.000000, 419.500000, "hud:radar_centre");
TextDrawFont(PublicTD[9], 4);
TextDrawLetterSize(PublicTD[9], 0.600000, 2.000000);
TextDrawTextSize(PublicTD[9], 15.000000, 15.000000);
TextDrawSetOutline(PublicTD[9], 1);
TextDrawSetShadow(PublicTD[9], 0);
TextDrawAlignment(PublicTD[9], 1);
TextDrawColor(PublicTD[9], -1);
TextDrawBackgroundColor(PublicTD[9], 255);
TextDrawBoxColor(PublicTD[9], 50);
TextDrawUseBox(PublicTD[9], 1);
TextDrawSetProportional(PublicTD[9], 1);
TextDrawSetSelectable(PublicTD[9], 0);


//Player Textdraws

/*Player Progress Bars
Requires "progress2" include by Southclaws
Download: https://github.com/Southclaws/progress2/releases */
