/*
This file was generated by Nickk's TextDraw editor script
Kazuji Takahashi Is Remaker The Script
Nickk888 & Kazuji is the author of the K-NTD script
*/

//Variables
new Text:KazujiPUBTD[15];

//Textdraws
KazujiPUBTD[0] = TextDrawCreate(516.000000, 184.000000, "_");
TextDrawFont(KazujiPUBTD[0], 1);
TextDrawLetterSize(KazujiPUBTD[0], 0.554166, 21.149999);
TextDrawTextSize(KazujiPUBTD[0], 298.500000, 101.500000);
TextDrawSetOutline(KazujiPUBTD[0], 1);
TextDrawSetShadow(KazujiPUBTD[0], 0);
TextDrawAlignment(KazujiPUBTD[0], 2);
TextDrawColor(KazujiPUBTD[0], -1);
TextDrawBackgroundColor(KazujiPUBTD[0], 255);
TextDrawBoxColor(KazujiPUBTD[0], 1887473919);
TextDrawUseBox(KazujiPUBTD[0], 1);
TextDrawSetProportional(KazujiPUBTD[0], 1);
TextDrawSetSelectable(KazujiPUBTD[0], 0);

KazujiPUBTD[1] = TextDrawCreate(460.000000, 364.000000, "ld_beat:chit");
TextDrawFont(KazujiPUBTD[1], 4);
TextDrawLetterSize(KazujiPUBTD[1], 0.600000, 2.000000);
TextDrawTextSize(KazujiPUBTD[1], 14.000000, 14.000000);
TextDrawSetOutline(KazujiPUBTD[1], 1);
TextDrawSetShadow(KazujiPUBTD[1], 0);
TextDrawAlignment(KazujiPUBTD[1], 1);
TextDrawColor(KazujiPUBTD[1], 255);
TextDrawBackgroundColor(KazujiPUBTD[1], 255);
TextDrawBoxColor(KazujiPUBTD[1], 50);
TextDrawUseBox(KazujiPUBTD[1], 1);
TextDrawSetProportional(KazujiPUBTD[1], 1);
TextDrawSetSelectable(KazujiPUBTD[1], 0);

KazujiPUBTD[2] = TextDrawCreate(464.000000, 184.000000, "_");
TextDrawFont(KazujiPUBTD[2], 1);
TextDrawLetterSize(KazujiPUBTD[2], 0.600000, 20.949996);
TextDrawTextSize(KazujiPUBTD[2], 308.500000, 0.000000);
TextDrawSetOutline(KazujiPUBTD[2], 1);
TextDrawSetShadow(KazujiPUBTD[2], 0);
TextDrawAlignment(KazujiPUBTD[2], 2);
TextDrawColor(KazujiPUBTD[2], -1);
TextDrawBackgroundColor(KazujiPUBTD[2], 255);
TextDrawBoxColor(KazujiPUBTD[2], 241);
TextDrawUseBox(KazujiPUBTD[2], 1);
TextDrawSetProportional(KazujiPUBTD[2], 1);
TextDrawSetSelectable(KazujiPUBTD[2], 0);

KazujiPUBTD[3] = TextDrawCreate(561.000000, 365.000000, "ld_beat:chit");
TextDrawFont(KazujiPUBTD[3], 4);
TextDrawLetterSize(KazujiPUBTD[3], 0.600000, 2.000000);
TextDrawTextSize(KazujiPUBTD[3], 10.000000, 13.000000);
TextDrawSetOutline(KazujiPUBTD[3], 1);
TextDrawSetShadow(KazujiPUBTD[3], 0);
TextDrawAlignment(KazujiPUBTD[3], 1);
TextDrawColor(KazujiPUBTD[3], 255);
TextDrawBackgroundColor(KazujiPUBTD[3], 255);
TextDrawBoxColor(KazujiPUBTD[3], 50);
TextDrawUseBox(KazujiPUBTD[3], 1);
TextDrawSetProportional(KazujiPUBTD[3], 1);
TextDrawSetSelectable(KazujiPUBTD[3], 0);

KazujiPUBTD[4] = TextDrawCreate(568.000000, 184.000000, "_");
TextDrawFont(KazujiPUBTD[4], 1);
TextDrawLetterSize(KazujiPUBTD[4], 0.600000, 20.949996);
TextDrawTextSize(KazujiPUBTD[4], 308.500000, 0.000000);
TextDrawSetOutline(KazujiPUBTD[4], 1);
TextDrawSetShadow(KazujiPUBTD[4], 0);
TextDrawAlignment(KazujiPUBTD[4], 2);
TextDrawColor(KazujiPUBTD[4], -1);
TextDrawBackgroundColor(KazujiPUBTD[4], 255);
TextDrawBoxColor(KazujiPUBTD[4], 241);
TextDrawUseBox(KazujiPUBTD[4], 1);
TextDrawSetProportional(KazujiPUBTD[4], 1);
TextDrawSetSelectable(KazujiPUBTD[4], 0);

KazujiPUBTD[5] = TextDrawCreate(460.000000, 178.000000, "ld_beat:chit");
TextDrawFont(KazujiPUBTD[5], 4);
TextDrawLetterSize(KazujiPUBTD[5], 0.600000, 2.000000);
TextDrawTextSize(KazujiPUBTD[5], 12.000000, 13.500000);
TextDrawSetOutline(KazujiPUBTD[5], 1);
TextDrawSetShadow(KazujiPUBTD[5], 0);
TextDrawAlignment(KazujiPUBTD[5], 1);
TextDrawColor(KazujiPUBTD[5], 255);
TextDrawBackgroundColor(KazujiPUBTD[5], 255);
TextDrawBoxColor(KazujiPUBTD[5], 50);
TextDrawUseBox(KazujiPUBTD[5], 1);
TextDrawSetProportional(KazujiPUBTD[5], 1);
TextDrawSetSelectable(KazujiPUBTD[5], 0);

KazujiPUBTD[6] = TextDrawCreate(560.000000, 178.000000, "ld_beat:chit");
TextDrawFont(KazujiPUBTD[6], 4);
TextDrawLetterSize(KazujiPUBTD[6], 0.600000, 2.000000);
TextDrawTextSize(KazujiPUBTD[6], 12.000000, 13.500000);
TextDrawSetOutline(KazujiPUBTD[6], 1);
TextDrawSetShadow(KazujiPUBTD[6], 0);
TextDrawAlignment(KazujiPUBTD[6], 1);
TextDrawColor(KazujiPUBTD[6], 255);
TextDrawBackgroundColor(KazujiPUBTD[6], 255);
TextDrawBoxColor(KazujiPUBTD[6], 50);
TextDrawUseBox(KazujiPUBTD[6], 1);
TextDrawSetProportional(KazujiPUBTD[6], 1);
TextDrawSetSelectable(KazujiPUBTD[6], 0);

KazujiPUBTD[7] = TextDrawCreate(517.000000, 182.000000, "_");
TextDrawFont(KazujiPUBTD[7], 1);
TextDrawLetterSize(KazujiPUBTD[7], 0.600000, 0.000002);
TextDrawTextSize(KazujiPUBTD[7], 298.500000, 97.500000);
TextDrawSetOutline(KazujiPUBTD[7], 1);
TextDrawSetShadow(KazujiPUBTD[7], 0);
TextDrawAlignment(KazujiPUBTD[7], 2);
TextDrawColor(KazujiPUBTD[7], -1);
TextDrawBackgroundColor(KazujiPUBTD[7], 255);
TextDrawBoxColor(KazujiPUBTD[7], 255);
TextDrawUseBox(KazujiPUBTD[7], 1);
TextDrawSetProportional(KazujiPUBTD[7], 1);
TextDrawSetSelectable(KazujiPUBTD[7], 0);

KazujiPUBTD[8] = TextDrawCreate(517.000000, 374.000000, "_");
TextDrawFont(KazujiPUBTD[8], 1);
TextDrawLetterSize(KazujiPUBTD[8], 0.600000, 0.000002);
TextDrawTextSize(KazujiPUBTD[8], 298.500000, 94.500000);
TextDrawSetOutline(KazujiPUBTD[8], 1);
TextDrawSetShadow(KazujiPUBTD[8], 0);
TextDrawAlignment(KazujiPUBTD[8], 2);
TextDrawColor(KazujiPUBTD[8], -1);
TextDrawBackgroundColor(KazujiPUBTD[8], 255);
TextDrawBoxColor(KazujiPUBTD[8], 255);
TextDrawUseBox(KazujiPUBTD[8], 1);
TextDrawSetProportional(KazujiPUBTD[8], 1);
TextDrawSetSelectable(KazujiPUBTD[8], 0);

KazujiPUBTD[9] = TextDrawCreate(505.000000, 340.000000, "ld_beat:chit");
TextDrawFont(KazujiPUBTD[9], 4);
TextDrawLetterSize(KazujiPUBTD[9], 0.258332, 1.750000);
TextDrawTextSize(KazujiPUBTD[9], 19.500000, 21.500000);
TextDrawSetOutline(KazujiPUBTD[9], 1);
TextDrawSetShadow(KazujiPUBTD[9], 0);
TextDrawAlignment(KazujiPUBTD[9], 2);
TextDrawColor(KazujiPUBTD[9], -1);
TextDrawBackgroundColor(KazujiPUBTD[9], 255);
TextDrawBoxColor(KazujiPUBTD[9], 200);
TextDrawUseBox(KazujiPUBTD[9], 0);
TextDrawSetProportional(KazujiPUBTD[9], 1);
TextDrawSetSelectable(KazujiPUBTD[9], 1);

KazujiPUBTD[10] = TextDrawCreate(515.000000, 254.000000, "12/05/2024");
TextDrawFont(KazujiPUBTD[10], 3);
TextDrawLetterSize(KazujiPUBTD[10], 0.266665, 1.049999);
TextDrawTextSize(KazujiPUBTD[10], 400.000000, 17.000000);
TextDrawSetOutline(KazujiPUBTD[10], 0);
TextDrawSetShadow(KazujiPUBTD[10], 0);
TextDrawAlignment(KazujiPUBTD[10], 2);
TextDrawColor(KazujiPUBTD[10], -1);
TextDrawBackgroundColor(KazujiPUBTD[10], 255);
TextDrawBoxColor(KazujiPUBTD[10], 50);
TextDrawUseBox(KazujiPUBTD[10], 0);
TextDrawSetProportional(KazujiPUBTD[10], 1);
TextDrawSetSelectable(KazujiPUBTD[10], 0);

KazujiPUBTD[11] = TextDrawCreate(514.000000, 237.000000, "14.10");
TextDrawFont(KazujiPUBTD[11], 3);
TextDrawLetterSize(KazujiPUBTD[11], 0.424999, 1.799998);
TextDrawTextSize(KazujiPUBTD[11], 400.000000, 17.000000);
TextDrawSetOutline(KazujiPUBTD[11], 0);
TextDrawSetShadow(KazujiPUBTD[11], 0);
TextDrawAlignment(KazujiPUBTD[11], 2);
TextDrawColor(KazujiPUBTD[11], -1);
TextDrawBackgroundColor(KazujiPUBTD[11], 255);
TextDrawBoxColor(KazujiPUBTD[11], 50);
TextDrawUseBox(KazujiPUBTD[11], 0);
TextDrawSetProportional(KazujiPUBTD[11], 1);
TextDrawSetSelectable(KazujiPUBTD[11], 0);

KazujiPUBTD[12] = TextDrawCreate(517.000000, 184.000000, "_");
TextDrawFont(KazujiPUBTD[12], 1);
TextDrawLetterSize(KazujiPUBTD[12], 0.625000, 0.650002);
TextDrawTextSize(KazujiPUBTD[12], 298.500000, 102.500000);
TextDrawSetOutline(KazujiPUBTD[12], 1);
TextDrawSetShadow(KazujiPUBTD[12], 0);
TextDrawAlignment(KazujiPUBTD[12], 2);
TextDrawColor(KazujiPUBTD[12], -1);
TextDrawBackgroundColor(KazujiPUBTD[12], 255);
TextDrawBoxColor(KazujiPUBTD[12], 255);
TextDrawUseBox(KazujiPUBTD[12], 1);
TextDrawSetProportional(KazujiPUBTD[12], 1);
TextDrawSetSelectable(KazujiPUBTD[12], 0);

KazujiPUBTD[13] = TextDrawCreate(515.000000, 366.000000, "_");
TextDrawFont(KazujiPUBTD[13], 1);
TextDrawLetterSize(KazujiPUBTD[13], 0.625000, 0.650002);
TextDrawTextSize(KazujiPUBTD[13], 298.500000, 102.500000);
TextDrawSetOutline(KazujiPUBTD[13], 1);
TextDrawSetShadow(KazujiPUBTD[13], 0);
TextDrawAlignment(KazujiPUBTD[13], 2);
TextDrawColor(KazujiPUBTD[13], -1);
TextDrawBackgroundColor(KazujiPUBTD[13], 255);
TextDrawBoxColor(KazujiPUBTD[13], 255);
TextDrawUseBox(KazujiPUBTD[13], 1);
TextDrawSetProportional(KazujiPUBTD[13], 1);
TextDrawSetSelectable(KazujiPUBTD[13], 0);

KazujiPUBTD[14] = TextDrawCreate(504.000000, 182.000000, "Phone");
TextDrawFont(KazujiPUBTD[14], 1);
TextDrawLetterSize(KazujiPUBTD[14], 0.162500, 1.000000);
TextDrawTextSize(KazujiPUBTD[14], 399.500000, 14.000000);
TextDrawSetOutline(KazujiPUBTD[14], 0);
TextDrawSetShadow(KazujiPUBTD[14], 0);
TextDrawAlignment(KazujiPUBTD[14], 1);
TextDrawColor(KazujiPUBTD[14], -1);
TextDrawBackgroundColor(KazujiPUBTD[14], 255);
TextDrawBoxColor(KazujiPUBTD[14], 50);
TextDrawUseBox(KazujiPUBTD[14], 0);
TextDrawSetProportional(KazujiPUBTD[14], 1);
TextDrawSetSelectable(KazujiPUBTD[14], 0);


//Player Textdraws

/*Player Progress Bars
Requires "progress2" include by Southclaws
Download: https://github.com/Southclaws/progress2/releases */
