/*
This file was generated by Nickk's TextDraw editor script
Nickk888 is the author of the NTD script
*/

//Variables
new Text:PublicTD[6];
new PlayerBar:PlayerProgressBar[MAX_PLAYERS][2];

//Textdraws
PublicTD[0] = TextDrawCreate(586.000000, 360.000000, "_");
TextDrawFont(PublicTD[0], 1);
TextDrawLetterSize(PublicTD[0], 0.308333, 4.900003);
TextDrawTextSize(PublicTD[0], 298.500000, 90.000000);
TextDrawSetOutline(PublicTD[0], 1);
TextDrawSetShadow(PublicTD[0], 0);
TextDrawAlignment(PublicTD[0], 2);
TextDrawColor(PublicTD[0], -1);
TextDrawBackgroundColor(PublicTD[0], 255);
TextDrawBoxColor(PublicTD[0], 255);
TextDrawUseBox(PublicTD[0], 1);
TextDrawSetProportional(PublicTD[0], 1);
TextDrawSetSelectable(PublicTD[0], 0);

PublicTD[1] = TextDrawCreate(539.000000, 350.000000, "Vehicle Name");
TextDrawFont(PublicTD[1], 0);
TextDrawLetterSize(PublicTD[1], 0.404166, 1.650000);
TextDrawTextSize(PublicTD[1], 690.500000, 222.000000);
TextDrawSetOutline(PublicTD[1], 1);
TextDrawSetShadow(PublicTD[1], 0);
TextDrawAlignment(PublicTD[1], 1);
TextDrawColor(PublicTD[1], -1);
TextDrawBackgroundColor(PublicTD[1], 255);
TextDrawBoxColor(PublicTD[1], 50);
TextDrawUseBox(PublicTD[1], 0);
TextDrawSetProportional(PublicTD[1], 1);
TextDrawSetSelectable(PublicTD[1], 0);

PublicTD[2] = TextDrawCreate(545.000000, 373.000000, "Fuel");
TextDrawFont(PublicTD[2], 1);
TextDrawLetterSize(PublicTD[2], 0.250000, 1.150000);
TextDrawTextSize(PublicTD[2], 690.500000, 222.000000);
TextDrawSetOutline(PublicTD[2], 1);
TextDrawSetShadow(PublicTD[2], 0);
TextDrawAlignment(PublicTD[2], 1);
TextDrawColor(PublicTD[2], -1);
TextDrawBackgroundColor(PublicTD[2], 255);
TextDrawBoxColor(PublicTD[2], 50);
TextDrawUseBox(PublicTD[2], 0);
TextDrawSetProportional(PublicTD[2], 1);
TextDrawSetSelectable(PublicTD[2], 0);

PublicTD[3] = TextDrawCreate(545.000000, 388.000000, "Health");
TextDrawFont(PublicTD[3], 1);
TextDrawLetterSize(PublicTD[3], 0.250000, 1.150000);
TextDrawTextSize(PublicTD[3], 690.500000, 222.000000);
TextDrawSetOutline(PublicTD[3], 1);
TextDrawSetShadow(PublicTD[3], 0);
TextDrawAlignment(PublicTD[3], 1);
TextDrawColor(PublicTD[3], -1);
TextDrawBackgroundColor(PublicTD[3], 255);
TextDrawBoxColor(PublicTD[3], 50);
TextDrawUseBox(PublicTD[3], 0);
TextDrawSetProportional(PublicTD[3], 1);
TextDrawSetSelectable(PublicTD[3], 0);

PublicTD[4] = TextDrawCreate(593.000000, 406.000000, "100");
TextDrawFont(PublicTD[4], 3);
TextDrawLetterSize(PublicTD[4], 0.633333, 2.849999);
TextDrawTextSize(PublicTD[4], 400.000000, 17.000000);
TextDrawSetOutline(PublicTD[4], 1);
TextDrawSetShadow(PublicTD[4], 0);
TextDrawAlignment(PublicTD[4], 3);
TextDrawColor(PublicTD[4], -1094795521);
TextDrawBackgroundColor(PublicTD[4], 125);
TextDrawBoxColor(PublicTD[4], -1094795726);
TextDrawUseBox(PublicTD[4], 0);
TextDrawSetProportional(PublicTD[4], 1);
TextDrawSetSelectable(PublicTD[4], 0);

PublicTD[5] = TextDrawCreate(594.000000, 413.000000, "mph");
TextDrawFont(PublicTD[5], 1);
TextDrawLetterSize(PublicTD[5], 0.295833, 1.350000);
TextDrawTextSize(PublicTD[5], 690.500000, 222.000000);
TextDrawSetOutline(PublicTD[5], 1);
TextDrawSetShadow(PublicTD[5], 0);
TextDrawAlignment(PublicTD[5], 1);
TextDrawColor(PublicTD[5], 1296911871);
TextDrawBackgroundColor(PublicTD[5], 255);
TextDrawBoxColor(PublicTD[5], 50);
TextDrawUseBox(PublicTD[5], 0);
TextDrawSetProportional(PublicTD[5], 1);
TextDrawSetSelectable(PublicTD[5], 0);


//Player Textdraws

/*Player Progress Bars
Requires "progress2" include by Southclaws
Download: https://github.com/Southclaws/progress2/releases */
PlayerProgressBar[playerid][0] = CreatePlayerProgressBar(playerid, 575.000000, 375.000000, 56.500000, 7.000000, -1, 100.000000, 0);
SetPlayerProgressBarValue(playerid, PlayerProgressBar[playerid][0], 50.000000);

PlayerProgressBar[playerid][1] = CreatePlayerProgressBar(playerid, 575.000000, 390.000000, 56.500000, 7.000000, -1, 100.000000, 0);
SetPlayerProgressBarValue(playerid, PlayerProgressBar[playerid][1], 50.000000);

