/*
This file was generated by Nickk's TextDraw editor script
Nickk888 is the author of the NTD script
*/

//Variables
new Text:PublicTD[4];
new PlayerBar:PlayerProgressBar[MAX_PLAYERS][2];

//Textdraws
PublicTD[0] = TextDrawCreate(68.000000, 244.000000, "_");
TextDrawFont(PublicTD[0], 1);
TextDrawLetterSize(PublicTD[0], 0.937500, 5.100001);
TextDrawTextSize(PublicTD[0], 298.500000, 85.500000);
TextDrawSetOutline(PublicTD[0], 1);
TextDrawSetShadow(PublicTD[0], 0);
TextDrawAlignment(PublicTD[0], 2);
TextDrawColor(PublicTD[0], -1);
TextDrawBackgroundColor(PublicTD[0], 255);
TextDrawBoxColor(PublicTD[0], 255);
TextDrawUseBox(PublicTD[0], 1);
TextDrawSetProportional(PublicTD[0], 1);
TextDrawSetSelectable(PublicTD[0], 0);

PublicTD[1] = TextDrawCreate(23.000000, 236.000000, "Statistic");
TextDrawFont(PublicTD[1], 0);
TextDrawLetterSize(PublicTD[1], 0.637498, 1.450000);
TextDrawTextSize(PublicTD[1], 400.000000, 17.000000);
TextDrawSetOutline(PublicTD[1], 1);
TextDrawSetShadow(PublicTD[1], 0);
TextDrawAlignment(PublicTD[1], 1);
TextDrawColor(PublicTD[1], -1);
TextDrawBackgroundColor(PublicTD[1], 255);
TextDrawBoxColor(PublicTD[1], 50);
TextDrawUseBox(PublicTD[1], 0);
TextDrawSetProportional(PublicTD[1], 1);
TextDrawSetSelectable(PublicTD[1], 0);

PublicTD[2] = TextDrawCreate(27.000000, 256.000000, "Hunger");
TextDrawFont(PublicTD[2], 1);
TextDrawLetterSize(PublicTD[2], 0.233333, 1.049999);
TextDrawTextSize(PublicTD[2], 400.000000, 17.000000);
TextDrawSetOutline(PublicTD[2], 1);
TextDrawSetShadow(PublicTD[2], 0);
TextDrawAlignment(PublicTD[2], 1);
TextDrawColor(PublicTD[2], -1);
TextDrawBackgroundColor(PublicTD[2], 255);
TextDrawBoxColor(PublicTD[2], 50);
TextDrawUseBox(PublicTD[2], 0);
TextDrawSetProportional(PublicTD[2], 1);
TextDrawSetSelectable(PublicTD[2], 0);

PublicTD[3] = TextDrawCreate(27.000000, 271.000000, "Energy");
TextDrawFont(PublicTD[3], 1);
TextDrawLetterSize(PublicTD[3], 0.233333, 1.049999);
TextDrawTextSize(PublicTD[3], 400.000000, 17.000000);
TextDrawSetOutline(PublicTD[3], 1);
TextDrawSetShadow(PublicTD[3], 0);
TextDrawAlignment(PublicTD[3], 1);
TextDrawColor(PublicTD[3], -1);
TextDrawBackgroundColor(PublicTD[3], 255);
TextDrawBoxColor(PublicTD[3], 50);
TextDrawUseBox(PublicTD[3], 0);
TextDrawSetProportional(PublicTD[3], 1);
TextDrawSetSelectable(PublicTD[3], 0);


//Player Textdraws

/*Player Progress Bars
Requires "progress2" include by Southclaws
Download: https://github.com/Southclaws/progress2/releases */
PlayerProgressBar[playerid][0] = CreatePlayerProgressBar(playerid, 61.000000, 258.000000, 51.000000, 7.000000, -1, 100.000000, 0);
SetPlayerProgressBarValue(playerid, PlayerProgressBar[playerid][0], 50.000000);

PlayerProgressBar[playerid][1] = CreatePlayerProgressBar(playerid, 61.000000, 274.000000, 51.000000, 7.000000, -1, 100.000000, 0);
SetPlayerProgressBarValue(playerid, PlayerProgressBar[playerid][1], 50.000000);

