/*
This file was generated by Nickk's TextDraw editor script
Nickk888 is the author of the NTD script
*/

//Variables
new PlayerText:PlayerTD[MAX_PLAYERS][20];

//Textdraws

//Player Textdraws
PlayerTD[playerid][0] = CreatePlayerTextDraw(playerid, 584.000000, 406.000000, "_");
PlayerTextDrawFont(playerid, PlayerTD[playerid][0], 1);
PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][0], 1.254166, 3.299998);
PlayerTextDrawTextSize(playerid, PlayerTD[playerid][0], 294.000000, 87.000000);
PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][0], 1);
PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][0], 0);
PlayerTextDrawAlignment(playerid, PlayerTD[playerid][0], 2);
PlayerTextDrawColor(playerid, PlayerTD[playerid][0], -1);
PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][0], 255);
PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][0], 135);
PlayerTextDrawUseBox(playerid, PlayerTD[playerid][0], 1);
PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][0], 1);
PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][0], 0);

PlayerTD[playerid][1] = CreatePlayerTextDraw(playerid, 584.000000, 406.000000, "_");
PlayerTextDrawFont(playerid, PlayerTD[playerid][1], 1);
PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][1], 1.254166, -0.699998);
PlayerTextDrawTextSize(playerid, PlayerTD[playerid][1], 294.000000, 87.000000);
PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][1], 1);
PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][1], 0);
PlayerTextDrawAlignment(playerid, PlayerTD[playerid][1], 2);
PlayerTextDrawColor(playerid, PlayerTD[playerid][1], -1);
PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][1], 255);
PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][1], -151);
PlayerTextDrawUseBox(playerid, PlayerTD[playerid][1], 1);
PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][1], 1);
PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][1], 0);

PlayerTD[playerid][2] = CreatePlayerTextDraw(playerid, 539.000000, 392.000000, "Yaheed_Mossef");
PlayerTextDrawFont(playerid, PlayerTD[playerid][2], 1);
PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][2], 0.162498, 0.949998);
PlayerTextDrawTextSize(playerid, PlayerTD[playerid][2], 536.000000, 17.000000);
PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][2], 0);
PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][2], 0);
PlayerTextDrawAlignment(playerid, PlayerTD[playerid][2], 1);
PlayerTextDrawColor(playerid, PlayerTD[playerid][2], -1);
PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][2], 255);
PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][2], 50);
PlayerTextDrawUseBox(playerid, PlayerTD[playerid][2], 0);
PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][2], 1);
PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][2], 0);

PlayerTD[playerid][3] = CreatePlayerTextDraw(playerid, 584.000000, 410.000000, "_");
PlayerTextDrawFont(playerid, PlayerTD[playerid][3], 1);
PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][3], 1.108330, 0.900002);
PlayerTextDrawTextSize(playerid, PlayerTD[playerid][3], 294.000000, 82.500000);
PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][3], 1);
PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][3], 0);
PlayerTextDrawAlignment(playerid, PlayerTD[playerid][3], 2);
PlayerTextDrawColor(playerid, PlayerTD[playerid][3], -1);
PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][3], 255);
PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][3], 135);
PlayerTextDrawUseBox(playerid, PlayerTD[playerid][3], 1);
PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][3], 1);
PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][3], 0);

PlayerTD[playerid][4] = CreatePlayerTextDraw(playerid, 584.000000, 424.000000, "_");
PlayerTextDrawFont(playerid, PlayerTD[playerid][4], 1);
PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][4], 1.108330, 0.900002);
PlayerTextDrawTextSize(playerid, PlayerTD[playerid][4], 294.000000, 82.500000);
PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][4], 1);
PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][4], 0);
PlayerTextDrawAlignment(playerid, PlayerTD[playerid][4], 2);
PlayerTextDrawColor(playerid, PlayerTD[playerid][4], -1);
PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][4], 255);
PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][4], 135);
PlayerTextDrawUseBox(playerid, PlayerTD[playerid][4], 1);
PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][4], 1);
PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][4], 0);

PlayerTD[playerid][5] = CreatePlayerTextDraw(playerid, 542.000000, 409.000000, "ld_bum:blkdot"); ///HUNGER BAR
PlayerTextDrawFont(playerid, PlayerTD[playerid][5], 4);
PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][5], 0.600000, 2.000000);
PlayerTextDrawTextSize(playerid, PlayerTD[playerid][5], 84.000000, 10.000000);
PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][5], 1);
PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][5], 0);
PlayerTextDrawAlignment(playerid, PlayerTD[playerid][5], 1);
PlayerTextDrawColor(playerid, PlayerTD[playerid][5], 2094792889);
PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][5], 255);
PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][5], 50);
PlayerTextDrawUseBox(playerid, PlayerTD[playerid][5], 1);
PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][5], 1);
PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][5], 0);

PlayerTD[playerid][6] = CreatePlayerTextDraw(playerid, 542.000000, 423.000000, "ld_bum:blkdot"); ///ENERGY BAR
PlayerTextDrawFont(playerid, PlayerTD[playerid][6], 4);
PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][6], 0.600000, 2.000000);
PlayerTextDrawTextSize(playerid, PlayerTD[playerid][6], 84.000000, 10.000000);
PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][6], 1);
PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][6], 0);
PlayerTextDrawAlignment(playerid, PlayerTD[playerid][6], 1);
PlayerTextDrawColor(playerid, PlayerTD[playerid][6], -2016478535);
PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][6], 255);
PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][6], 50);
PlayerTextDrawUseBox(playerid, PlayerTD[playerid][6], 1);
PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][6], 1);
PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][6], 0);

PlayerTD[playerid][7] = CreatePlayerTextDraw(playerid, 584.000000, 409.000000, "HUNGER");
PlayerTextDrawFont(playerid, PlayerTD[playerid][7], 2);
PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][7], 0.162498, 0.949998);
PlayerTextDrawTextSize(playerid, PlayerTD[playerid][7], 400.000000, 17.000000);
PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][7], 0);
PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][7], 0);
PlayerTextDrawAlignment(playerid, PlayerTD[playerid][7], 2);
PlayerTextDrawColor(playerid, PlayerTD[playerid][7], -126);
PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][7], 255);
PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][7], 50);
PlayerTextDrawUseBox(playerid, PlayerTD[playerid][7], 0);
PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][7], 1);
PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][7], 0);

PlayerTD[playerid][8] = CreatePlayerTextDraw(playerid, 584.000000, 423.000000, "ENERGY");
PlayerTextDrawFont(playerid, PlayerTD[playerid][8], 2);
PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][8], 0.162498, 0.949998);
PlayerTextDrawTextSize(playerid, PlayerTD[playerid][8], 400.000000, 17.000000);
PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][8], 0);
PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][8], 0);
PlayerTextDrawAlignment(playerid, PlayerTD[playerid][8], 2);
PlayerTextDrawColor(playerid, PlayerTD[playerid][8], -126);
PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][8], 255);
PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][8], 50);
PlayerTextDrawUseBox(playerid, PlayerTD[playerid][8], 0);
PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][8], 1);
PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][8], 0);

PlayerTD[playerid][9] = CreatePlayerTextDraw(playerid, 492.000000, 406.000000, "_");
PlayerTextDrawFont(playerid, PlayerTD[playerid][9], 1);
PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][9], 1.254166, 3.299998);
PlayerTextDrawTextSize(playerid, PlayerTD[playerid][9], 294.000000, 87.000000);
PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][9], 1);
PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][9], 0);
PlayerTextDrawAlignment(playerid, PlayerTD[playerid][9], 2);
PlayerTextDrawColor(playerid, PlayerTD[playerid][9], -1);
PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][9], 255);
PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][9], 135);
PlayerTextDrawUseBox(playerid, PlayerTD[playerid][9], 1);
PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][9], 1);
PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][9], 0);

PlayerTD[playerid][10] = CreatePlayerTextDraw(playerid, 492.000000, 406.000000, "_");
PlayerTextDrawFont(playerid, PlayerTD[playerid][10], 1);
PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][10], 1.254166, -0.699998);
PlayerTextDrawTextSize(playerid, PlayerTD[playerid][10], 294.000000, 87.000000);
PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][10], 1);
PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][10], 0);
PlayerTextDrawAlignment(playerid, PlayerTD[playerid][10], 2);
PlayerTextDrawColor(playerid, PlayerTD[playerid][10], -1);
PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][10], 255);
PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][10], -151);
PlayerTextDrawUseBox(playerid, PlayerTD[playerid][10], 1);
PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][10], 1);
PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][10], 0);

PlayerTD[playerid][11] = CreatePlayerTextDraw(playerid, 447.000000, 392.000000, "Trashmaster");
PlayerTextDrawFont(playerid, PlayerTD[playerid][11], 1);
PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][11], 0.162498, 0.949998);
PlayerTextDrawTextSize(playerid, PlayerTD[playerid][11], 536.000000, 17.000000);
PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][11], 0);
PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][11], 0);
PlayerTextDrawAlignment(playerid, PlayerTD[playerid][11], 1);
PlayerTextDrawColor(playerid, PlayerTD[playerid][11], -1);
PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][11], 255);
PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][11], 50);
PlayerTextDrawUseBox(playerid, PlayerTD[playerid][11], 0);
PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][11], 1);
PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][11], 0);

PlayerTD[playerid][12] = CreatePlayerTextDraw(playerid, 464.000000, 408.000000, "120");
PlayerTextDrawFont(playerid, PlayerTD[playerid][12], 3);
PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][12], 0.387499, 1.600000);
PlayerTextDrawTextSize(playerid, PlayerTD[playerid][12], 400.000000, 17.000000);
PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][12], 1);
PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][12], 1);
PlayerTextDrawAlignment(playerid, PlayerTD[playerid][12], 2);
PlayerTextDrawColor(playerid, PlayerTD[playerid][12], -1);
PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][12], 35);
PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][12], 50);
PlayerTextDrawUseBox(playerid, PlayerTD[playerid][12], 0);
PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][12], 1);
PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][12], 0);

PlayerTD[playerid][13] = CreatePlayerTextDraw(playerid, 464.000000, 422.000000, "km/h");
PlayerTextDrawFont(playerid, PlayerTD[playerid][13], 2);
PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][13], 0.162498, 0.949998);
PlayerTextDrawTextSize(playerid, PlayerTD[playerid][13], 400.000000, 17.000000);
PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][13], 0);
PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][13], 0);
PlayerTextDrawAlignment(playerid, PlayerTD[playerid][13], 2);
PlayerTextDrawColor(playerid, PlayerTD[playerid][13], -1);
PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][13], 255);
PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][13], 50);
PlayerTextDrawUseBox(playerid, PlayerTD[playerid][13], 0);
PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][13], 1);
PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][13], 0);

PlayerTD[playerid][14] = CreatePlayerTextDraw(playerid, 508.000000, 410.000000, "_");
PlayerTextDrawFont(playerid, PlayerTD[playerid][14], 1);
PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][14], 1.108330, 0.900002);
PlayerTextDrawTextSize(playerid, PlayerTD[playerid][14], 294.000000, 50.500000);
PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][14], 1);
PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][14], 0);
PlayerTextDrawAlignment(playerid, PlayerTD[playerid][14], 2);
PlayerTextDrawColor(playerid, PlayerTD[playerid][14], -1);
PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][14], 255);
PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][14], 135);
PlayerTextDrawUseBox(playerid, PlayerTD[playerid][14], 1);
PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][14], 1);
PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][14], 0);

PlayerTD[playerid][15] = CreatePlayerTextDraw(playerid, 508.000000, 424.000000, "_");
PlayerTextDrawFont(playerid, PlayerTD[playerid][15], 1);
PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][15], 1.108330, 0.900002);
PlayerTextDrawTextSize(playerid, PlayerTD[playerid][15], 294.000000, 50.500000);
PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][15], 1);
PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][15], 0);
PlayerTextDrawAlignment(playerid, PlayerTD[playerid][15], 2);
PlayerTextDrawColor(playerid, PlayerTD[playerid][15], -1);
PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][15], 255);
PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][15], 135);
PlayerTextDrawUseBox(playerid, PlayerTD[playerid][15], 1);
PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][15], 1);
PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][15], 0);

PlayerTD[playerid][16] = CreatePlayerTextDraw(playerid, 482.000000, 409.000000, "ld_bum:blkdot"); ///FUEL BARR
PlayerTextDrawFont(playerid, PlayerTD[playerid][16], 4);
PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][16], 0.600000, 2.000000);
PlayerTextDrawTextSize(playerid, PlayerTD[playerid][16], 52.000000, 10.000000);
PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][16], 1);
PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][16], 0);
PlayerTextDrawAlignment(playerid, PlayerTD[playerid][16], 1);
PlayerTextDrawColor(playerid, PlayerTD[playerid][16], 9145273);
PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][16], 255);
PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][16], 50);
PlayerTextDrawUseBox(playerid, PlayerTD[playerid][16], 1);
PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][16], 1);
PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][16], 0);

PlayerTD[playerid][17] = CreatePlayerTextDraw(playerid, 482.000000, 423.000000, "ld_bum:blkdot"); ///DAMAGE BAR
PlayerTextDrawFont(playerid, PlayerTD[playerid][17], 4);
PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][17], 0.600000, 2.000000);
PlayerTextDrawTextSize(playerid, PlayerTD[playerid][17], 52.000000, 10.000000);
PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][17], 1);
PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][17], 0);
PlayerTextDrawAlignment(playerid, PlayerTD[playerid][17], 1);
PlayerTextDrawColor(playerid, PlayerTD[playerid][17], -16777031);
PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][17], 255);
PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][17], 50);
PlayerTextDrawUseBox(playerid, PlayerTD[playerid][17], 1);
PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][17], 1);
PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][17], 0);

PlayerTD[playerid][18] = CreatePlayerTextDraw(playerid, 509.000000, 410.000000, "FUEL");
PlayerTextDrawFont(playerid, PlayerTD[playerid][18], 2);
PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][18], 0.145833, 0.800000);
PlayerTextDrawTextSize(playerid, PlayerTD[playerid][18], 400.000000, 17.000000);
PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][18], 0);
PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][18], 0);
PlayerTextDrawAlignment(playerid, PlayerTD[playerid][18], 2);
PlayerTextDrawColor(playerid, PlayerTD[playerid][18], -126);
PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][18], 255);
PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][18], 50);
PlayerTextDrawUseBox(playerid, PlayerTD[playerid][18], 0);
PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][18], 1);
PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][18], 0);

PlayerTD[playerid][19] = CreatePlayerTextDraw(playerid, 509.000000, 424.000000, "DAMAGE");
PlayerTextDrawFont(playerid, PlayerTD[playerid][19], 2);
PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][19], 0.145833, 0.800000);
PlayerTextDrawTextSize(playerid, PlayerTD[playerid][19], 400.000000, 17.000000);
PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][19], 0);
PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][19], 0);
PlayerTextDrawAlignment(playerid, PlayerTD[playerid][19], 2);
PlayerTextDrawColor(playerid, PlayerTD[playerid][19], -126);
PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][19], 255);
PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][19], 50);
PlayerTextDrawUseBox(playerid, PlayerTD[playerid][19], 0);
PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][19], 1);
PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][19], 0);


/*Player Progress Bars
Requires "progress2" include by Southclaws
Download: https://github.com/Southclaws/progress2/releases */
