/*
This file was generated by Nickk's TextDraw editor script
Nickk888 is the author of the NTD script
*/

//Variables
new Text:PublicTD[16];

//Textdraws
PublicTD[0] = TextDrawCreate(435.000000, 150.000000, "_");
TextDrawFont(PublicTD[0], 1);
TextDrawLetterSize(PublicTD[0], 0.600000, 2.299998);
TextDrawTextSize(PublicTD[0], 298.500000, 70.000000);
TextDrawSetOutline(PublicTD[0], 1);
TextDrawSetShadow(PublicTD[0], 0);
TextDrawAlignment(PublicTD[0], 2);
TextDrawColor(PublicTD[0], -1);
TextDrawBackgroundColor(PublicTD[0], 255);
TextDrawBoxColor(PublicTD[0], 255);
TextDrawUseBox(PublicTD[0], 1);
TextDrawSetProportional(PublicTD[0], 1);
TextDrawSetSelectable(PublicTD[0], 0);

PublicTD[1] = TextDrawCreate(450.000000, 180.000000, "_");
TextDrawFont(PublicTD[1], 1);
TextDrawLetterSize(PublicTD[1], 0.600000, 2.500000);
TextDrawTextSize(PublicTD[1], 298.500000, 100.000000);
TextDrawSetOutline(PublicTD[1], 1);
TextDrawSetShadow(PublicTD[1], 0);
TextDrawAlignment(PublicTD[1], 2);
TextDrawColor(PublicTD[1], -1);
TextDrawBackgroundColor(PublicTD[1], 255);
TextDrawBoxColor(PublicTD[1], 255);
TextDrawUseBox(PublicTD[1], 1);
TextDrawSetProportional(PublicTD[1], 1);
TextDrawSetSelectable(PublicTD[1], 1);

PublicTD[2] = TextDrawCreate(450.000000, 210.000000, "_");
TextDrawFont(PublicTD[2], 1);
TextDrawLetterSize(PublicTD[2], 0.600000, 2.500000);
TextDrawTextSize(PublicTD[2], 298.500000, 100.000000);
TextDrawSetOutline(PublicTD[2], 1);
TextDrawSetShadow(PublicTD[2], 0);
TextDrawAlignment(PublicTD[2], 2);
TextDrawColor(PublicTD[2], -1);
TextDrawBackgroundColor(PublicTD[2], 255);
TextDrawBoxColor(PublicTD[2], 255);
TextDrawUseBox(PublicTD[2], 1);
TextDrawSetProportional(PublicTD[2], 1);
TextDrawSetSelectable(PublicTD[2], 1);

PublicTD[3] = TextDrawCreate(450.000000, 240.000000, "_");
TextDrawFont(PublicTD[3], 1);
TextDrawLetterSize(PublicTD[3], 0.600000, 2.500000);
TextDrawTextSize(PublicTD[3], 298.500000, 100.000000);
TextDrawSetOutline(PublicTD[3], 1);
TextDrawSetShadow(PublicTD[3], 0);
TextDrawAlignment(PublicTD[3], 2);
TextDrawColor(PublicTD[3], -1);
TextDrawBackgroundColor(PublicTD[3], 255);
TextDrawBoxColor(PublicTD[3], 255);
TextDrawUseBox(PublicTD[3], 1);
TextDrawSetProportional(PublicTD[3], 1);
TextDrawSetSelectable(PublicTD[3], 1);

PublicTD[4] = TextDrawCreate(450.000000, 270.000000, "_");
TextDrawFont(PublicTD[4], 1);
TextDrawLetterSize(PublicTD[4], 0.600000, 2.500000);
TextDrawTextSize(PublicTD[4], 298.500000, 100.000000);
TextDrawSetOutline(PublicTD[4], 1);
TextDrawSetShadow(PublicTD[4], 0);
TextDrawAlignment(PublicTD[4], 2);
TextDrawColor(PublicTD[4], -1);
TextDrawBackgroundColor(PublicTD[4], 255);
TextDrawBoxColor(PublicTD[4], 255);
TextDrawUseBox(PublicTD[4], 1);
TextDrawSetProportional(PublicTD[4], 1);
TextDrawSetSelectable(PublicTD[4], 1);

PublicTD[5] = TextDrawCreate(490.000000, 150.000000, "_");
TextDrawFont(PublicTD[5], 1);
TextDrawLetterSize(PublicTD[5], 0.600000, 2.299998);
TextDrawTextSize(PublicTD[5], 298.500000, 20.000000);
TextDrawSetOutline(PublicTD[5], 1);
TextDrawSetShadow(PublicTD[5], 0);
TextDrawAlignment(PublicTD[5], 2);
TextDrawColor(PublicTD[5], -1);
TextDrawBackgroundColor(PublicTD[5], 255);
TextDrawBoxColor(PublicTD[5], 255);
TextDrawUseBox(PublicTD[5], 1);
TextDrawSetProportional(PublicTD[5], 1);
TextDrawSetSelectable(PublicTD[5], 1);

PublicTD[6] = TextDrawCreate(415.000000, 153.000000, "RADIAL MENU");
TextDrawFont(PublicTD[6], 1);
TextDrawLetterSize(PublicTD[6], 0.200000, 1.000000);
TextDrawTextSize(PublicTD[6], 600.000000, 17.000000);
TextDrawSetOutline(PublicTD[6], 0);
TextDrawSetShadow(PublicTD[6], 0);
TextDrawAlignment(PublicTD[6], 1);
TextDrawColor(PublicTD[6], -1094795521);
TextDrawBackgroundColor(PublicTD[6], 255);
TextDrawBoxColor(PublicTD[6], -741092558);
TextDrawUseBox(PublicTD[6], 0);
TextDrawSetProportional(PublicTD[6], 1);
TextDrawSetSelectable(PublicTD[6], 0);

PublicTD[7] = TextDrawCreate(405.000000, 180.000000, "DOKUMEN");
TextDrawFont(PublicTD[7], 1);
TextDrawLetterSize(PublicTD[7], 0.200000, 1.000000);
TextDrawTextSize(PublicTD[7], 600.000000, 17.000000);
TextDrawSetOutline(PublicTD[7], 0);
TextDrawSetShadow(PublicTD[7], 0);
TextDrawAlignment(PublicTD[7], 1);
TextDrawColor(PublicTD[7], -1094795521);
TextDrawBackgroundColor(PublicTD[7], 255);
TextDrawBoxColor(PublicTD[7], -741092558);
TextDrawUseBox(PublicTD[7], 0);
TextDrawSetProportional(PublicTD[7], 1);
TextDrawSetSelectable(PublicTD[7], 0);

PublicTD[8] = TextDrawCreate(405.000000, 190.000000, "UNTUK MELIHAT DOKUMEN PRIBADI");
TextDrawFont(PublicTD[8], 1);
TextDrawLetterSize(PublicTD[8], 0.100000, 1.000000);
TextDrawTextSize(PublicTD[8], 600.000000, 17.000000);
TextDrawSetOutline(PublicTD[8], 0);
TextDrawSetShadow(PublicTD[8], 0);
TextDrawAlignment(PublicTD[8], 1);
TextDrawColor(PublicTD[8], -1094795521);
TextDrawBackgroundColor(PublicTD[8], 255);
TextDrawBoxColor(PublicTD[8], -741092558);
TextDrawUseBox(PublicTD[8], 0);
TextDrawSetProportional(PublicTD[8], 1);
TextDrawSetSelectable(PublicTD[8], 0);

PublicTD[9] = TextDrawCreate(405.000000, 211.000000, "PHONE");
TextDrawFont(PublicTD[9], 1);
TextDrawLetterSize(PublicTD[9], 0.200000, 1.000000);
TextDrawTextSize(PublicTD[9], 600.000000, 17.000000);
TextDrawSetOutline(PublicTD[9], 0);
TextDrawSetShadow(PublicTD[9], 0);
TextDrawAlignment(PublicTD[9], 1);
TextDrawColor(PublicTD[9], -1094795521);
TextDrawBackgroundColor(PublicTD[9], 255);
TextDrawBoxColor(PublicTD[9], -741092558);
TextDrawUseBox(PublicTD[9], 0);
TextDrawSetProportional(PublicTD[9], 1);
TextDrawSetSelectable(PublicTD[9], 0);

PublicTD[10] = TextDrawCreate(405.000000, 220.000000, "UNTUK MEMBUKA HANDPHONE");
TextDrawFont(PublicTD[10], 1);
TextDrawLetterSize(PublicTD[10], 0.100000, 1.000000);
TextDrawTextSize(PublicTD[10], 600.000000, 17.000000);
TextDrawSetOutline(PublicTD[10], 0);
TextDrawSetShadow(PublicTD[10], 0);
TextDrawAlignment(PublicTD[10], 1);
TextDrawColor(PublicTD[10], -1094795521);
TextDrawBackgroundColor(PublicTD[10], 255);
TextDrawBoxColor(PublicTD[10], -741092558);
TextDrawUseBox(PublicTD[10], 0);
TextDrawSetProportional(PublicTD[10], 1);
TextDrawSetSelectable(PublicTD[10], 0);

PublicTD[11] = TextDrawCreate(405.000000, 240.000000, "INVENTORY");
TextDrawFont(PublicTD[11], 1);
TextDrawLetterSize(PublicTD[11], 0.200000, 1.000000);
TextDrawTextSize(PublicTD[11], 600.000000, 17.000000);
TextDrawSetOutline(PublicTD[11], 0);
TextDrawSetShadow(PublicTD[11], 0);
TextDrawAlignment(PublicTD[11], 1);
TextDrawColor(PublicTD[11], -1094795521);
TextDrawBackgroundColor(PublicTD[11], 255);
TextDrawBoxColor(PublicTD[11], -741092558);
TextDrawUseBox(PublicTD[11], 0);
TextDrawSetProportional(PublicTD[11], 1);
TextDrawSetSelectable(PublicTD[11], 0);

PublicTD[12] = TextDrawCreate(405.000000, 250.000000, "UNTUK MEMBUKA INVENTORY");
TextDrawFont(PublicTD[12], 1);
TextDrawLetterSize(PublicTD[12], 0.100000, 1.000000);
TextDrawTextSize(PublicTD[12], 600.000000, 17.000000);
TextDrawSetOutline(PublicTD[12], 0);
TextDrawSetShadow(PublicTD[12], 0);
TextDrawAlignment(PublicTD[12], 1);
TextDrawColor(PublicTD[12], -1094795521);
TextDrawBackgroundColor(PublicTD[12], 255);
TextDrawBoxColor(PublicTD[12], -741092558);
TextDrawUseBox(PublicTD[12], 0);
TextDrawSetProportional(PublicTD[12], 1);
TextDrawSetSelectable(PublicTD[12], 0);

PublicTD[13] = TextDrawCreate(405.000000, 270.000000, "KENDARAAN");
TextDrawFont(PublicTD[13], 1);
TextDrawLetterSize(PublicTD[13], 0.200000, 1.000000);
TextDrawTextSize(PublicTD[13], 600.000000, 17.000000);
TextDrawSetOutline(PublicTD[13], 0);
TextDrawSetShadow(PublicTD[13], 0);
TextDrawAlignment(PublicTD[13], 1);
TextDrawColor(PublicTD[13], -1094795521);
TextDrawBackgroundColor(PublicTD[13], 255);
TextDrawBoxColor(PublicTD[13], -741092558);
TextDrawUseBox(PublicTD[13], 0);
TextDrawSetProportional(PublicTD[13], 1);
TextDrawSetSelectable(PublicTD[13], 0);

PublicTD[14] = TextDrawCreate(405.000000, 280.000000, "UNTUK MEMBUKA PANEL KENDARAAN");
TextDrawFont(PublicTD[14], 1);
TextDrawLetterSize(PublicTD[14], 0.100000, 1.000000);
TextDrawTextSize(PublicTD[14], 600.000000, 17.000000);
TextDrawSetOutline(PublicTD[14], 0);
TextDrawSetShadow(PublicTD[14], 0);
TextDrawAlignment(PublicTD[14], 1);
TextDrawColor(PublicTD[14], -1094795521);
TextDrawBackgroundColor(PublicTD[14], 255);
TextDrawBoxColor(PublicTD[14], -741092558);
TextDrawUseBox(PublicTD[14], 0);
TextDrawSetProportional(PublicTD[14], 1);
TextDrawSetSelectable(PublicTD[14], 0);

PublicTD[15] = TextDrawCreate(483.000000, 153.000000, "X");
TextDrawFont(PublicTD[15], 1);
TextDrawLetterSize(PublicTD[15], 0.600000, 1.299998);
TextDrawTextSize(PublicTD[15], 600.000000, 17.000000);
TextDrawSetOutline(PublicTD[15], 0);
TextDrawSetShadow(PublicTD[15], 0);
TextDrawAlignment(PublicTD[15], 1);
TextDrawColor(PublicTD[15], -1094795521);
TextDrawBackgroundColor(PublicTD[15], 255);
TextDrawBoxColor(PublicTD[15], -741092558);
TextDrawUseBox(PublicTD[15], 0);
TextDrawSetProportional(PublicTD[15], 1);
TextDrawSetSelectable(PublicTD[15], 0);


//Player Textdraws

/*Player Progress Bars
Requires "progress2" include by Southclaws
Download: https://github.com/Southclaws/progress2/releases */
