new PlayerText:PlayerTD[MAX_PLAYERS][45];
new PlayerText:phone_exit[MAX_PLAYERS];
new PlayerText:phone_music[MAX_PLAYERS];
new PlayerText:phone_twitter[MAX_PLAYERS];
new PlayerText:phone_cam[MAX_PLAYERS];
new PlayerText:phone_bank[MAX_PLAYERS];
new PlayerText:phone_sms[MAX_PLAYERS];
new PlayerText:phone_contact[MAX_PLAYERS];
new PlayerText:phone_gps[MAX_PLAYERS];
new PlayerText:phone_settings[MAX_PLAYERS];
new PlayerText:phone_player_level[MAX_PLAYERS];
new PlayerText:phone_player_money[MAX_PLAYERS];
new PlayerText:phone_player_age[MAX_PLAYERS];


PlayerTD[playerid][0] = CreatePlayerTextDraw(playerid, 435.000000, 180.000000, "ld_bum:blkdot");
PlayerTextDrawFont(playerid, PlayerTD[playerid][0], 4);
PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][0], 0.600000, 2.000000);
PlayerTextDrawTextSize(playerid, PlayerTD[playerid][0], 135.000000, 211.500000);
PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][0], 1);
PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][0], 0);
PlayerTextDrawAlignment(playerid, PlayerTD[playerid][0], 1);
PlayerTextDrawColor(playerid, PlayerTD[playerid][0], 255);
PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][0], -1);
PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][0], 50);
PlayerTextDrawUseBox(playerid, PlayerTD[playerid][0], 1);
PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][0], 1);
PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][0], 0);

PlayerTD[playerid][1] = CreatePlayerTextDraw(playerid, 439.000000, 183.000000, "ld_bum:blkdot");
PlayerTextDrawFont(playerid, PlayerTD[playerid][1], 4);
PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][1], 0.600000, 2.000000);
PlayerTextDrawTextSize(playerid, PlayerTD[playerid][1], 126.500000, 205.500000);
PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][1], 1);
PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][1], 0);
PlayerTextDrawAlignment(playerid, PlayerTD[playerid][1], 1);
PlayerTextDrawColor(playerid, PlayerTD[playerid][1], -1);
PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][1], -1);
PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][1], 50);
PlayerTextDrawUseBox(playerid, PlayerTD[playerid][1], 1);
PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][1], 1);
PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][1], 0);

PlayerTD[playerid][2] = CreatePlayerTextDraw(playerid, 494.000000, 183.000000, "ld_beat:chit");
PlayerTextDrawFont(playerid, PlayerTD[playerid][2], 4);
PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][2], 0.600000, 2.000000);
PlayerTextDrawTextSize(playerid, PlayerTD[playerid][2], 17.500000, 15.000000);
PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][2], 1);
PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][2], 0);
PlayerTextDrawAlignment(playerid, PlayerTD[playerid][2], 1);
PlayerTextDrawColor(playerid, PlayerTD[playerid][2], 255);
PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][2], 255);
PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][2], 50);
PlayerTextDrawUseBox(playerid, PlayerTD[playerid][2], 1);
PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][2], 1);
PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][2], 0);

PlayerTD[playerid][3] = CreatePlayerTextDraw(playerid, 535.000000, 186.000000, "ld_bum:blkdot");
PlayerTextDrawFont(playerid, PlayerTD[playerid][3], 4);
PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][3], 0.600000, 2.000000);
PlayerTextDrawTextSize(playerid, PlayerTD[playerid][3], 27.500000, 7.500000);
PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][3], 1);
PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][3], 0);
PlayerTextDrawAlignment(playerid, PlayerTD[playerid][3], 1);
PlayerTextDrawColor(playerid, PlayerTD[playerid][3], 16711935);
PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][3], -1);
PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][3], 50);
PlayerTextDrawUseBox(playerid, PlayerTD[playerid][3], 1);
PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][3], 1);
PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][3], 0);

PlayerTD[playerid][4] = CreatePlayerTextDraw(playerid, 539.000000, 187.000000, "100");
PlayerTextDrawFont(playerid, PlayerTD[playerid][4], 1);
PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][4], 0.283333, 0.650000);
PlayerTextDrawTextSize(playerid, PlayerTD[playerid][4], 400.000000, 17.000000);
PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][4], 0);
PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][4], 0);
PlayerTextDrawAlignment(playerid, PlayerTD[playerid][4], 1);
PlayerTextDrawColor(playerid, PlayerTD[playerid][4], 255);
PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][4], 255);
PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][4], 50);
PlayerTextDrawUseBox(playerid, PlayerTD[playerid][4], 0);
PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][4], 1);
PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][4], 0);

PlayerTD[playerid][5] = CreatePlayerTextDraw(playerid, 443.000000, 186.000000, "5G");
PlayerTextDrawFont(playerid, PlayerTD[playerid][5], 1);
PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][5], 0.295833, 0.850000);
PlayerTextDrawTextSize(playerid, PlayerTD[playerid][5], 400.000000, 17.000000);
PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][5], 0);
PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][5], 0);
PlayerTextDrawAlignment(playerid, PlayerTD[playerid][5], 1);
PlayerTextDrawColor(playerid, PlayerTD[playerid][5], 255);
PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][5], 255);
PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][5], 50);
PlayerTextDrawUseBox(playerid, PlayerTD[playerid][5], 0);
PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][5], 1);
PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][5], 0);

PlayerTD[playerid][6] = CreatePlayerTextDraw(playerid, 460.000000, 186.000000, "Smartfren");
PlayerTextDrawFont(playerid, PlayerTD[playerid][6], 1);
PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][6], 0.191667, 0.850000);
PlayerTextDrawTextSize(playerid, PlayerTD[playerid][6], 400.000000, 17.000000);
PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][6], 0);
PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][6], 0);
PlayerTextDrawAlignment(playerid, PlayerTD[playerid][6], 1);
PlayerTextDrawColor(playerid, PlayerTD[playerid][6], 255);
PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][6], 255);
PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][6], 50);
PlayerTextDrawUseBox(playerid, PlayerTD[playerid][6], 0);
PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][6], 1);
PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][6], 0);

PlayerTD[playerid][7] = CreatePlayerTextDraw(playerid, 443.000000, 209.000000, "ld_bum:blkdot");
PlayerTextDrawFont(playerid, PlayerTD[playerid][7], 4);
PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][7], 0.600000, 2.000000);
PlayerTextDrawTextSize(playerid, PlayerTD[playerid][7], 62.500000, 74.000000);
PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][7], 1);
PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][7], 0);
PlayerTextDrawAlignment(playerid, PlayerTD[playerid][7], 1);
PlayerTextDrawColor(playerid, PlayerTD[playerid][7], -421070081);
PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][7], -1);
PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][7], 50);
PlayerTextDrawUseBox(playerid, PlayerTD[playerid][7], 1);
PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][7], 1);
PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][7], 0);

phone_exit[playerid] = CreatePlayerTextDraw(playerid, 467.000000, 380.000000, "ld_bum:blkdot");
PlayerTextDrawFont(playerid, phone_exit[playerid], 4);
PlayerTextDrawLetterSize(playerid, phone_exit[playerid], 0.600000, 2.000000);
PlayerTextDrawTextSize(playerid, phone_exit[playerid], 67.000000, 6.000000);
PlayerTextDrawSetOutline(playerid, phone_exit[playerid], 1);
PlayerTextDrawSetShadow(playerid, phone_exit[playerid], 0);
PlayerTextDrawAlignment(playerid, phone_exit[playerid], 1);
PlayerTextDrawColor(playerid, phone_exit[playerid], -741092353);
PlayerTextDrawBackgroundColor(playerid, phone_exit[playerid], -1);
PlayerTextDrawBoxColor(playerid, phone_exit[playerid], 50);
PlayerTextDrawUseBox(playerid, phone_exit[playerid], 1);
PlayerTextDrawSetProportional(playerid, phone_exit[playerid], 1);
PlayerTextDrawSetSelectable(playerid, phone_exit[playerid], 0);

PlayerTD[playerid][8] = CreatePlayerTextDraw(playerid, 522.000000, 210.000000, "ld_bum:blkdot");
PlayerTextDrawFont(playerid, PlayerTD[playerid][8], 4);
PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][8], 0.600000, 2.000000);
PlayerTextDrawTextSize(playerid, PlayerTD[playerid][8], 38.000000, 30.500000);
PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][8], 1);
PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][8], 0);
PlayerTextDrawAlignment(playerid, PlayerTD[playerid][8], 1);
PlayerTextDrawColor(playerid, PlayerTD[playerid][8], -1378294017);
PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][8], -1);
PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][8], 50);
PlayerTextDrawUseBox(playerid, PlayerTD[playerid][8], 1);
PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][8], 1);
PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][8], 0);

PlayerTD[playerid][9] = CreatePlayerTextDraw(playerid, 522.000000, 249.000000, "ld_bum:blkdot");
PlayerTextDrawFont(playerid, PlayerTD[playerid][9], 4);
PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][9], 0.600000, 2.000000);
PlayerTextDrawTextSize(playerid, PlayerTD[playerid][9], 38.000000, 30.500000);
PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][9], 1);
PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][9], 0);
PlayerTextDrawAlignment(playerid, PlayerTD[playerid][9], 1);
PlayerTextDrawColor(playerid, PlayerTD[playerid][9], -8323073);
PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][9], -1);
PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][9], 50);
PlayerTextDrawUseBox(playerid, PlayerTD[playerid][9], 1);
PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][9], 1);
PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][9], 0);

PlayerTD[playerid][10] = CreatePlayerTextDraw(playerid, 440.000000, 297.000000, "ld_bum:blkdot");
PlayerTextDrawFont(playerid, PlayerTD[playerid][10], 4);
PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][10], 0.600000, 2.000000);
PlayerTextDrawTextSize(playerid, PlayerTD[playerid][10], 38.000000, 30.500000);
PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][10], 1);
PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][10], 0);
PlayerTextDrawAlignment(playerid, PlayerTD[playerid][10], 1);
PlayerTextDrawColor(playerid, PlayerTD[playerid][10], 1747094527);
PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][10], -1);
PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][10], 50);
PlayerTextDrawUseBox(playerid, PlayerTD[playerid][10], 1);
PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][10], 1);
PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][10], 0);

PlayerTD[playerid][11] = CreatePlayerTextDraw(playerid, 482.000000, 338.000000, "ld_bum:blkdot");
PlayerTextDrawFont(playerid, PlayerTD[playerid][11], 4);
PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][11], 0.600000, 2.000000);
PlayerTextDrawTextSize(playerid, PlayerTD[playerid][11], 38.000000, 30.500000);
PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][11], 2);
PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][11], 0);
PlayerTextDrawAlignment(playerid, PlayerTD[playerid][11], 1);
PlayerTextDrawColor(playerid, PlayerTD[playerid][11], 255);
PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][11], -1);
PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][11], 50);
PlayerTextDrawUseBox(playerid, PlayerTD[playerid][11], 1);
PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][11], 1);
PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][11], 0);

phone_music[playerid] = CreatePlayerTextDraw(playerid, 523.000000, 338.000000, "ld_bum:blkdot");
PlayerTextDrawFont(playerid, phone_music[playerid], 4);
PlayerTextDrawLetterSize(playerid, phone_music[playerid], 0.600000, 2.000000);
PlayerTextDrawTextSize(playerid, phone_music[playerid], 38.000000, 30.500000);
PlayerTextDrawSetOutline(playerid, phone_music[playerid], 1);
PlayerTextDrawSetShadow(playerid, phone_music[playerid], 0);
PlayerTextDrawAlignment(playerid, phone_music[playerid], 1);
PlayerTextDrawColor(playerid, phone_music[playerid], 255);
PlayerTextDrawBackgroundColor(playerid, phone_music[playerid], -1);
PlayerTextDrawBoxColor(playerid, phone_music[playerid], 50);
PlayerTextDrawUseBox(playerid, phone_music[playerid], 1);
PlayerTextDrawSetProportional(playerid, phone_music[playerid], 1);
PlayerTextDrawSetSelectable(playerid, phone_music[playerid], 0);

phone_twitter[playerid] = CreatePlayerTextDraw(playerid, 523.000000, 297.000000, "ld_bum:blkdot");
PlayerTextDrawFont(playerid, phone_twitter[playerid], 4);
PlayerTextDrawLetterSize(playerid, phone_twitter[playerid], 0.600000, 2.000000);
PlayerTextDrawTextSize(playerid, phone_twitter[playerid], 38.000000, 30.500000);
PlayerTextDrawSetOutline(playerid, phone_twitter[playerid], 1);
PlayerTextDrawSetShadow(playerid, phone_twitter[playerid], 0);
PlayerTextDrawAlignment(playerid, phone_twitter[playerid], 1);
PlayerTextDrawColor(playerid, phone_twitter[playerid], 255);
PlayerTextDrawBackgroundColor(playerid, phone_twitter[playerid], -1);
PlayerTextDrawBoxColor(playerid, phone_twitter[playerid], 50);
PlayerTextDrawUseBox(playerid, phone_twitter[playerid], 1);
PlayerTextDrawSetProportional(playerid, phone_twitter[playerid], 1);
PlayerTextDrawSetSelectable(playerid, phone_twitter[playerid], 0);

PlayerTD[playerid][12] = CreatePlayerTextDraw(playerid, 440.000000, 338.000000, "ld_bum:blkdot");
PlayerTextDrawFont(playerid, PlayerTD[playerid][12], 4);
PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][12], 0.600000, 2.000000);
PlayerTextDrawTextSize(playerid, PlayerTD[playerid][12], 38.000000, 30.500000);
PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][12], 1);
PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][12], 0);
PlayerTextDrawAlignment(playerid, PlayerTD[playerid][12], 1);
PlayerTextDrawColor(playerid, PlayerTD[playerid][12], 1296911871);
PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][12], -1);
PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][12], 50);
PlayerTextDrawUseBox(playerid, PlayerTD[playerid][12], 1);
PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][12], 1);
PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][12], 0);

PlayerTD[playerid][13] = CreatePlayerTextDraw(playerid, 523.000000, 207.000000, "ld_beat:chit");
PlayerTextDrawFont(playerid, PlayerTD[playerid][13], 4);
PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][13], 0.600000, 2.000000);
PlayerTextDrawTextSize(playerid, PlayerTD[playerid][13], 39.500000, 35.500000);
PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][13], 1);
PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][13], 0);
PlayerTextDrawAlignment(playerid, PlayerTD[playerid][13], 1);
PlayerTextDrawColor(playerid, PlayerTD[playerid][13], 1097458175);
PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][13], 255);
PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][13], 50);
PlayerTextDrawUseBox(playerid, PlayerTD[playerid][13], 1);
PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][13], 1);
PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][13], 0);

phone_cam[playerid] = CreatePlayerTextDraw(playerid, 526.000000, 210.000000, "ld_beat:chit");
PlayerTextDrawFont(playerid, phone_cam[playerid], 4);
PlayerTextDrawLetterSize(playerid, phone_cam[playerid], 0.600000, 2.000000);
PlayerTextDrawTextSize(playerid, phone_cam[playerid], 33.500000, 29.000000);
PlayerTextDrawSetOutline(playerid, phone_cam[playerid], 1);
PlayerTextDrawSetShadow(playerid, phone_cam[playerid], 0);
PlayerTextDrawAlignment(playerid, phone_cam[playerid], 1);
PlayerTextDrawColor(playerid, phone_cam[playerid], 255);
PlayerTextDrawBackgroundColor(playerid, phone_cam[playerid], 255);
PlayerTextDrawBoxColor(playerid, phone_cam[playerid], 50);
PlayerTextDrawUseBox(playerid, phone_cam[playerid], 1);
PlayerTextDrawSetProportional(playerid, phone_cam[playerid], 1);
PlayerTextDrawSetSelectable(playerid, phone_cam[playerid], 0);

PlayerTD[playerid][14] = CreatePlayerTextDraw(playerid, 536.000000, 219.000000, "ld_beat:chit");
PlayerTextDrawFont(playerid, PlayerTD[playerid][14], 4);
PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][14], 0.600000, 2.000000);
PlayerTextDrawTextSize(playerid, PlayerTD[playerid][14], 13.500000, 11.500000);
PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][14], 1);
PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][14], 0);
PlayerTextDrawAlignment(playerid, PlayerTD[playerid][14], 1);
PlayerTextDrawColor(playerid, PlayerTD[playerid][14], -741092353);
PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][14], 255);
PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][14], 50);
PlayerTextDrawUseBox(playerid, PlayerTD[playerid][14], 1);
PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][14], 1);
PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][14], 0);

PlayerTD[playerid][15] = CreatePlayerTextDraw(playerid, 531.000000, 240.000000, "Camera");
PlayerTextDrawFont(playerid, PlayerTD[playerid][15], 1);
PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][15], 0.187500, 0.750000);
PlayerTextDrawTextSize(playerid, PlayerTD[playerid][15], 400.000000, 17.000000);
PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][15], 0);
PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][15], 0);
PlayerTextDrawAlignment(playerid, PlayerTD[playerid][15], 1);
PlayerTextDrawColor(playerid, PlayerTD[playerid][15], 255);
PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][15], 255);
PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][15], 50);
PlayerTextDrawUseBox(playerid, PlayerTD[playerid][15], 0);
PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][15], 1);
PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][15], 0);

phone_bank[playerid] = CreatePlayerTextDraw(playerid, 534.000000, 252.000000, "$");
PlayerTextDrawFont(playerid, phone_bank[playerid], 3);
PlayerTextDrawLetterSize(playerid, phone_bank[playerid], 0.745833, 2.500000);
PlayerTextDrawTextSize(playerid, phone_bank[playerid], 400.000000, 17.000000);
PlayerTextDrawSetOutline(playerid, phone_bank[playerid], 0);
PlayerTextDrawSetShadow(playerid, phone_bank[playerid], 0);
PlayerTextDrawAlignment(playerid, phone_bank[playerid], 1);
PlayerTextDrawColor(playerid, phone_bank[playerid], -1);
PlayerTextDrawBackgroundColor(playerid, phone_bank[playerid], 255);
PlayerTextDrawBoxColor(playerid, phone_bank[playerid], 50);
PlayerTextDrawUseBox(playerid, phone_bank[playerid], 0);
PlayerTextDrawSetProportional(playerid, phone_bank[playerid], 1);
PlayerTextDrawSetSelectable(playerid, phone_bank[playerid], 0);

PlayerTD[playerid][16] = CreatePlayerTextDraw(playerid, 535.000000, 279.000000, "Bank");
PlayerTextDrawFont(playerid, PlayerTD[playerid][16], 1);
PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][16], 0.187500, 0.750000);
PlayerTextDrawTextSize(playerid, PlayerTD[playerid][16], 400.000000, 17.000000);
PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][16], 0);
PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][16], 0);
PlayerTextDrawAlignment(playerid, PlayerTD[playerid][16], 1);
PlayerTextDrawColor(playerid, PlayerTD[playerid][16], 255);
PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][16], 255);
PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][16], 50);
PlayerTextDrawUseBox(playerid, PlayerTD[playerid][16], 0);
PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][16], 1);
PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][16], 0);

PlayerTD[playerid][17] = CreatePlayerTextDraw(playerid, 531.000000, 300.000000, "X");
PlayerTextDrawFont(playerid, PlayerTD[playerid][17], 1);
PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][17], 0.941666, 2.399997);
PlayerTextDrawTextSize(playerid, PlayerTD[playerid][17], 400.000000, 17.000000);
PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][17], 0);
PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][17], 0);
PlayerTextDrawAlignment(playerid, PlayerTD[playerid][17], 1);
PlayerTextDrawColor(playerid, PlayerTD[playerid][17], -1);
PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][17], 255);
PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][17], 50);
PlayerTextDrawUseBox(playerid, PlayerTD[playerid][17], 0);
PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][17], 1);
PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][17], 0);

PlayerTD[playerid][18] = CreatePlayerTextDraw(playerid, 532.000000, 327.000000, "Twitter");
PlayerTextDrawFont(playerid, PlayerTD[playerid][18], 1);
PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][18], 0.187500, 0.750000);
PlayerTextDrawTextSize(playerid, PlayerTD[playerid][18], 400.000000, 17.000000);
PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][18], 0);
PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][18], 0);
PlayerTextDrawAlignment(playerid, PlayerTD[playerid][18], 1);
PlayerTextDrawColor(playerid, PlayerTD[playerid][18], 255);
PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][18], 255);
PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][18], 50);
PlayerTextDrawUseBox(playerid, PlayerTD[playerid][18], 0);
PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][18], 1);
PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][18], 0);

PlayerTD[playerid][19] = CreatePlayerTextDraw(playerid, 540.000000, 342.000000, "ld_bum:blkdot");
PlayerTextDrawFont(playerid, PlayerTD[playerid][19], 4);
PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][19], 0.600000, 2.000000);
PlayerTextDrawTextSize(playerid, PlayerTD[playerid][19], 4.000000, 23.000000);
PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][19], 1);
PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][19], 0);
PlayerTextDrawAlignment(playerid, PlayerTD[playerid][19], 1);
PlayerTextDrawColor(playerid, PlayerTD[playerid][19], -1);
PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][19], -1);
PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][19], 50);
PlayerTextDrawUseBox(playerid, PlayerTD[playerid][19], 1);
PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][19], 1);
PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][19], 0);

PlayerTD[playerid][20] = CreatePlayerTextDraw(playerid, 534.000000, 355.000000, "ld_bum:blkdot");
PlayerTextDrawFont(playerid, PlayerTD[playerid][20], 4);
PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][20], 0.600000, 2.000000);
PlayerTextDrawTextSize(playerid, PlayerTD[playerid][20], 4.000000, 7.000000);
PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][20], 1);
PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][20], 0);
PlayerTextDrawAlignment(playerid, PlayerTD[playerid][20], 1);
PlayerTextDrawColor(playerid, PlayerTD[playerid][20], 255);
PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][20], -1);
PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][20], 50);
PlayerTextDrawUseBox(playerid, PlayerTD[playerid][20], 1);
PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][20], 1);
PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][20], 0);

PlayerTD[playerid][21] = CreatePlayerTextDraw(playerid, 534.000000, 352.000000, "ld_bum:blkdot");
PlayerTextDrawFont(playerid, PlayerTD[playerid][21], 4);
PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][21], 0.600000, 2.000000);
PlayerTextDrawTextSize(playerid, PlayerTD[playerid][21], 4.000000, 14.000000);
PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][21], 1);
PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][21], 0);
PlayerTextDrawAlignment(playerid, PlayerTD[playerid][21], 1);
PlayerTextDrawColor(playerid, PlayerTD[playerid][21], -1);
PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][21], -1);
PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][21], 50);
PlayerTextDrawUseBox(playerid, PlayerTD[playerid][21], 1);
PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][21], 1);
PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][21], 0);

PlayerTD[playerid][22] = CreatePlayerTextDraw(playerid, 528.000000, 346.000000, "ld_bum:blkdot");
PlayerTextDrawFont(playerid, PlayerTD[playerid][22], 4);
PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][22], 0.600000, 2.000000);
PlayerTextDrawTextSize(playerid, PlayerTD[playerid][22], 4.000000, 16.000000);
PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][22], 1);
PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][22], 0);
PlayerTextDrawAlignment(playerid, PlayerTD[playerid][22], 1);
PlayerTextDrawColor(playerid, PlayerTD[playerid][22], -1);
PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][22], -1);
PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][22], 50);
PlayerTextDrawUseBox(playerid, PlayerTD[playerid][22], 1);
PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][22], 1);
PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][22], 0);

PlayerTD[playerid][23] = CreatePlayerTextDraw(playerid, 534.000000, 343.000000, "ld_bum:blkdot");
PlayerTextDrawFont(playerid, PlayerTD[playerid][23], 4);
PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][23], 0.600000, 2.000000);
PlayerTextDrawTextSize(playerid, PlayerTD[playerid][23], 4.000000, 5.500000);
PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][23], 1);
PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][23], 0);
PlayerTextDrawAlignment(playerid, PlayerTD[playerid][23], 1);
PlayerTextDrawColor(playerid, PlayerTD[playerid][23], -1);
PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][23], -1);
PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][23], 50);
PlayerTextDrawUseBox(playerid, PlayerTD[playerid][23], 1);
PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][23], 1);
PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][23], 0);

PlayerTD[playerid][24] = CreatePlayerTextDraw(playerid, 546.000000, 346.000000, "ld_bum:blkdot");
PlayerTextDrawFont(playerid, PlayerTD[playerid][24], 4);
PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][24], 0.600000, 2.000000);
PlayerTextDrawTextSize(playerid, PlayerTD[playerid][24], 4.000000, 14.000000);
PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][24], 1);
PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][24], 0);
PlayerTextDrawAlignment(playerid, PlayerTD[playerid][24], 1);
PlayerTextDrawColor(playerid, PlayerTD[playerid][24], -1);
PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][24], -1);
PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][24], 50);
PlayerTextDrawUseBox(playerid, PlayerTD[playerid][24], 1);
PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][24], 1);
PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][24], 0);

PlayerTD[playerid][25] = CreatePlayerTextDraw(playerid, 552.000000, 344.000000, "ld_bum:blkdot");
PlayerTextDrawFont(playerid, PlayerTD[playerid][25], 4);
PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][25], 0.600000, 2.000000);
PlayerTextDrawTextSize(playerid, PlayerTD[playerid][25], 4.000000, 10.000000);
PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][25], 1);
PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][25], 0);
PlayerTextDrawAlignment(playerid, PlayerTD[playerid][25], 1);
PlayerTextDrawColor(playerid, PlayerTD[playerid][25], -1);
PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][25], -1);
PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][25], 50);
PlayerTextDrawUseBox(playerid, PlayerTD[playerid][25], 1);
PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][25], 1);
PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][25], 0);

PlayerTD[playerid][26] = CreatePlayerTextDraw(playerid, 532.000000, 368.000000, "Music");
PlayerTextDrawFont(playerid, PlayerTD[playerid][26], 1);
PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][26], 0.216667, 0.700000);
PlayerTextDrawTextSize(playerid, PlayerTD[playerid][26], 400.000000, 17.000000);
PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][26], 0);
PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][26], 0);
PlayerTextDrawAlignment(playerid, PlayerTD[playerid][26], 1);
PlayerTextDrawColor(playerid, PlayerTD[playerid][26], 255);
PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][26], 255);
PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][26], 50);
PlayerTextDrawUseBox(playerid, PlayerTD[playerid][26], 0);
PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][26], 1);
PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][26], 0);

PlayerTD[playerid][27] = CreatePlayerTextDraw(playerid, 482.000000, 297.000000, "ld_bum:blkdot");
PlayerTextDrawFont(playerid, PlayerTD[playerid][27], 4);
PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][27], 0.600000, 2.000000);
PlayerTextDrawTextSize(playerid, PlayerTD[playerid][27], 38.000000, 30.500000);
PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][27], 1);
PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][27], 0);
PlayerTextDrawAlignment(playerid, PlayerTD[playerid][27], 1);
PlayerTextDrawColor(playerid, PlayerTD[playerid][27], 16711935);
PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][27], -1);
PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][27], 50);
PlayerTextDrawUseBox(playerid, PlayerTD[playerid][27], 1);
PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][27], 1);
PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][27], 0);

phone_sms[playerid] = CreatePlayerTextDraw(playerid, 482.000000, 297.000000, "ld_beat:chit");
PlayerTextDrawFont(playerid, phone_sms[playerid], 4);
PlayerTextDrawLetterSize(playerid, phone_sms[playerid], 0.600000, 2.000000);
PlayerTextDrawTextSize(playerid, phone_sms[playerid], 39.000000, 31.500000);
PlayerTextDrawSetOutline(playerid, phone_sms[playerid], 1);
PlayerTextDrawSetShadow(playerid, phone_sms[playerid], 0);
PlayerTextDrawAlignment(playerid, phone_sms[playerid], 1);
PlayerTextDrawColor(playerid, phone_sms[playerid], -1);
PlayerTextDrawBackgroundColor(playerid, phone_sms[playerid], 255);
PlayerTextDrawBoxColor(playerid, phone_sms[playerid], 50);
PlayerTextDrawUseBox(playerid, phone_sms[playerid], 1);
PlayerTextDrawSetProportional(playerid, phone_sms[playerid], 1);
PlayerTextDrawSetSelectable(playerid, phone_sms[playerid], 0);

PlayerTD[playerid][28] = CreatePlayerTextDraw(playerid, 531.000000, 300.000000, "X");
PlayerTextDrawFont(playerid, PlayerTD[playerid][28], 1);
PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][28], 0.941666, 2.399997);
PlayerTextDrawTextSize(playerid, PlayerTD[playerid][28], 400.000000, 17.000000);
PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][28], 0);
PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][28], 0);
PlayerTextDrawAlignment(playerid, PlayerTD[playerid][28], 1);
PlayerTextDrawColor(playerid, PlayerTD[playerid][28], -1);
PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][28], 255);
PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][28], 50);
PlayerTextDrawUseBox(playerid, PlayerTD[playerid][28], 0);
PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][28], 1);
PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][28], 0);

PlayerTD[playerid][29] = CreatePlayerTextDraw(playerid, 484.000000, 314.000000, "ld_beat:chit");
PlayerTextDrawFont(playerid, PlayerTD[playerid][29], 4);
PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][29], 0.600000, 2.000000);
PlayerTextDrawTextSize(playerid, PlayerTD[playerid][29], 15.000000, 12.500000);
PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][29], 1);
PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][29], 0);
PlayerTextDrawAlignment(playerid, PlayerTD[playerid][29], 1);
PlayerTextDrawColor(playerid, PlayerTD[playerid][29], -1);
PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][29], 255);
PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][29], 50);
PlayerTextDrawUseBox(playerid, PlayerTD[playerid][29], 1);
PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][29], 1);
PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][29], 0);

PlayerTD[playerid][30] = CreatePlayerTextDraw(playerid, 494.000000, 327.000000, "Sms");
PlayerTextDrawFont(playerid, PlayerTD[playerid][30], 1);
PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][30], 0.187500, 0.750000);
PlayerTextDrawTextSize(playerid, PlayerTD[playerid][30], 400.000000, 17.000000);
PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][30], 0);
PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][30], 0);
PlayerTextDrawAlignment(playerid, PlayerTD[playerid][30], 1);
PlayerTextDrawColor(playerid, PlayerTD[playerid][30], 255);
PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][30], 255);
PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][30], 50);
PlayerTextDrawUseBox(playerid, PlayerTD[playerid][30], 0);
PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][30], 1);
PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][30], 0);

phone_contact[playerid] = CreatePlayerTextDraw(playerid, 440.000000, 306.000000, "ld_beat:chit");
PlayerTextDrawFont(playerid, phone_contact[playerid], 4);
PlayerTextDrawLetterSize(playerid, phone_contact[playerid], 0.600000, 2.000000);
PlayerTextDrawTextSize(playerid, phone_contact[playerid], 37.000000, 22.500000);
PlayerTextDrawSetOutline(playerid, phone_contact[playerid], 1);
PlayerTextDrawSetShadow(playerid, phone_contact[playerid], 0);
PlayerTextDrawAlignment(playerid, phone_contact[playerid], 1);
PlayerTextDrawColor(playerid, phone_contact[playerid], -1);
PlayerTextDrawBackgroundColor(playerid, phone_contact[playerid], 255);
PlayerTextDrawBoxColor(playerid, phone_contact[playerid], 50);
PlayerTextDrawUseBox(playerid, phone_contact[playerid], 1);
PlayerTextDrawSetProportional(playerid, phone_contact[playerid], 1);
PlayerTextDrawSetSelectable(playerid, phone_contact[playerid], 0);

PlayerTD[playerid][31] = CreatePlayerTextDraw(playerid, 443.000000, 296.000000, "ld_beat:chit");
PlayerTextDrawFont(playerid, PlayerTD[playerid][31], 4);
PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][31], 0.600000, 2.000000);
PlayerTextDrawTextSize(playerid, PlayerTD[playerid][31], 30.500000, 25.500000);
PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][31], 1);
PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][31], 0);
PlayerTextDrawAlignment(playerid, PlayerTD[playerid][31], 1);
PlayerTextDrawColor(playerid, PlayerTD[playerid][31], -1);
PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][31], 255);
PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][31], 50);
PlayerTextDrawUseBox(playerid, PlayerTD[playerid][31], 1);
PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][31], 1);
PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][31], 0);

PlayerTD[playerid][32] = CreatePlayerTextDraw(playerid, 447.000000, 327.000000, "Contact");
PlayerTextDrawFont(playerid, PlayerTD[playerid][32], 1);
PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][32], 0.187500, 0.750000);
PlayerTextDrawTextSize(playerid, PlayerTD[playerid][32], 400.000000, 17.000000);
PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][32], 0);
PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][32], 0);
PlayerTextDrawAlignment(playerid, PlayerTD[playerid][32], 1);
PlayerTextDrawColor(playerid, PlayerTD[playerid][32], 255);
PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][32], 255);
PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][32], 50);
PlayerTextDrawUseBox(playerid, PlayerTD[playerid][32], 0);
PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][32], 1);
PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][32], 0);

phone_gps[playerid] = CreatePlayerTextDraw(playerid, 486.000000, 337.000000, "ld_beat:chit");
PlayerTextDrawFont(playerid, phone_gps[playerid], 4);
PlayerTextDrawLetterSize(playerid, phone_gps[playerid], 0.600000, 2.000000);
PlayerTextDrawTextSize(playerid, phone_gps[playerid], 31.000000, 24.000000);
PlayerTextDrawSetOutline(playerid, phone_gps[playerid], 1);
PlayerTextDrawSetShadow(playerid, phone_gps[playerid], 0);
PlayerTextDrawAlignment(playerid, phone_gps[playerid], 1);
PlayerTextDrawColor(playerid, phone_gps[playerid], -1);
PlayerTextDrawBackgroundColor(playerid, phone_gps[playerid], 255);
PlayerTextDrawBoxColor(playerid, phone_gps[playerid], 50);
PlayerTextDrawUseBox(playerid, phone_gps[playerid], 1);
PlayerTextDrawSetProportional(playerid, phone_gps[playerid], 1);
PlayerTextDrawSetSelectable(playerid, phone_gps[playerid], 0);

PlayerTD[playerid][33] = CreatePlayerTextDraw(playerid, 494.000000, 353.000000, "ld_beat:chit");
PlayerTextDrawFont(playerid, PlayerTD[playerid][33], 4);
PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][33], 0.600000, 2.000000);
PlayerTextDrawTextSize(playerid, PlayerTD[playerid][33], 15.500000, 11.500000);
PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][33], 1);
PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][33], 0);
PlayerTextDrawAlignment(playerid, PlayerTD[playerid][33], 1);
PlayerTextDrawColor(playerid, PlayerTD[playerid][33], -1);
PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][33], 255);
PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][33], 50);
PlayerTextDrawUseBox(playerid, PlayerTD[playerid][33], 1);
PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][33], 1);
PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][33], 0);

PlayerTD[playerid][34] = CreatePlayerTextDraw(playerid, 496.000000, 368.000000, "GPS");
PlayerTextDrawFont(playerid, PlayerTD[playerid][34], 1);
PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][34], 0.216667, 0.700000);
PlayerTextDrawTextSize(playerid, PlayerTD[playerid][34], 400.000000, 17.000000);
PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][34], 0);
PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][34], 0);
PlayerTextDrawAlignment(playerid, PlayerTD[playerid][34], 1);
PlayerTextDrawColor(playerid, PlayerTD[playerid][34], 255);
PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][34], 255);
PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][34], 50);
PlayerTextDrawUseBox(playerid, PlayerTD[playerid][34], 0);
PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][34], 1);
PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][34], 0);

phone_settings[playerid] = CreatePlayerTextDraw(playerid, 441.000000, 337.000000, "ld_beat:chit");
PlayerTextDrawFont(playerid, phone_settings[playerid], 4);
PlayerTextDrawLetterSize(playerid, phone_settings[playerid], 0.600000, 2.000000);
PlayerTextDrawTextSize(playerid, phone_settings[playerid], 37.000000, 31.500000);
PlayerTextDrawSetOutline(playerid, phone_settings[playerid], 1);
PlayerTextDrawSetShadow(playerid, phone_settings[playerid], 0);
PlayerTextDrawAlignment(playerid, phone_settings[playerid], 1);
PlayerTextDrawColor(playerid, phone_settings[playerid], -1);
PlayerTextDrawBackgroundColor(playerid, phone_settings[playerid], 255);
PlayerTextDrawBoxColor(playerid, phone_settings[playerid], 50);
PlayerTextDrawUseBox(playerid, phone_settings[playerid], 1);
PlayerTextDrawSetProportional(playerid, phone_settings[playerid], 1);
PlayerTextDrawSetSelectable(playerid, phone_settings[playerid], 0);

PlayerTD[playerid][35] = CreatePlayerTextDraw(playerid, 463.000000, 353.000000, "ld_beat:chit");
PlayerTextDrawFont(playerid, PlayerTD[playerid][35], 4);
PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][35], 0.600000, 2.000000);
PlayerTextDrawTextSize(playerid, PlayerTD[playerid][35], 15.500000, 11.500000);
PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][35], 1);
PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][35], 0);
PlayerTextDrawAlignment(playerid, PlayerTD[playerid][35], 1);
PlayerTextDrawColor(playerid, PlayerTD[playerid][35], -1);
PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][35], 255);
PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][35], 50);
PlayerTextDrawUseBox(playerid, PlayerTD[playerid][35], 1);
PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][35], 1);
PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][35], 0);

PlayerTD[playerid][36] = CreatePlayerTextDraw(playerid, 442.000000, 340.000000, "ld_beat:chit");
PlayerTextDrawFont(playerid, PlayerTD[playerid][36], 4);
PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][36], 0.600000, 2.000000);
PlayerTextDrawTextSize(playerid, PlayerTD[playerid][36], 15.500000, 11.500000);
PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][36], 1);
PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][36], 0);
PlayerTextDrawAlignment(playerid, PlayerTD[playerid][36], 1);
PlayerTextDrawColor(playerid, PlayerTD[playerid][36], -1);
PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][36], 255);
PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][36], 50);
PlayerTextDrawUseBox(playerid, PlayerTD[playerid][36], 1);
PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][36], 1);
PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][36], 0);

PlayerTD[playerid][37] = CreatePlayerTextDraw(playerid, 461.000000, 340.000000, "ld_beat:chit");
PlayerTextDrawFont(playerid, PlayerTD[playerid][37], 4);
PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][37], 0.600000, 2.000000);
PlayerTextDrawTextSize(playerid, PlayerTD[playerid][37], 15.500000, 11.500000);
PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][37], 1);
PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][37], 0);
PlayerTextDrawAlignment(playerid, PlayerTD[playerid][37], 1);
PlayerTextDrawColor(playerid, PlayerTD[playerid][37], -1);
PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][37], 255);
PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][37], 50);
PlayerTextDrawUseBox(playerid, PlayerTD[playerid][37], 1);
PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][37], 1);
PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][37], 0);

PlayerTD[playerid][38] = CreatePlayerTextDraw(playerid, 442.000000, 354.000000, "ld_beat:chit");
PlayerTextDrawFont(playerid, PlayerTD[playerid][38], 4);
PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][38], 0.600000, 2.000000);
PlayerTextDrawTextSize(playerid, PlayerTD[playerid][38], 15.500000, 11.500000);
PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][38], 1);
PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][38], 0);
PlayerTextDrawAlignment(playerid, PlayerTD[playerid][38], 1);
PlayerTextDrawColor(playerid, PlayerTD[playerid][38], -1);
PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][38], 255);
PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][38], 50);
PlayerTextDrawUseBox(playerid, PlayerTD[playerid][38], 1);
PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][38], 1);
PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][38], 0);

PlayerTD[playerid][39] = CreatePlayerTextDraw(playerid, 450.000000, 209.000000, "ld_beat:chit");
PlayerTextDrawFont(playerid, PlayerTD[playerid][39], 4);
PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][39], 0.600000, 2.000000);
PlayerTextDrawTextSize(playerid, PlayerTD[playerid][39], 46.000000, 37.500000);
PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][39], 1);
PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][39], 0);
PlayerTextDrawAlignment(playerid, PlayerTD[playerid][39], 1);
PlayerTextDrawColor(playerid, PlayerTD[playerid][39], -1);
PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][39], 255);
PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][39], 50);
PlayerTextDrawUseBox(playerid, PlayerTD[playerid][39], 1);
PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][39], 1);
PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][39], 0);

PlayerTD[playerid][40] = CreatePlayerTextDraw(playerid, 446.000000, 368.000000, "Settings");
PlayerTextDrawFont(playerid, PlayerTD[playerid][40], 1);
PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][40], 0.216667, 0.700000);
PlayerTextDrawTextSize(playerid, PlayerTD[playerid][40], 400.000000, 17.000000);
PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][40], 0);
PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][40], 0);
PlayerTextDrawAlignment(playerid, PlayerTD[playerid][40], 1);
PlayerTextDrawColor(playerid, PlayerTD[playerid][40], 255);
PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][40], 255);
PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][40], 50);
PlayerTextDrawUseBox(playerid, PlayerTD[playerid][40], 0);
PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][40], 1);
PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][40], 0);

PlayerTD[playerid][41] = CreatePlayerTextDraw(playerid, 448.000000, 231.000000, "ld_beat:chit");
PlayerTextDrawFont(playerid, PlayerTD[playerid][41], 4);
PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][41], 0.600000, 2.000000);
PlayerTextDrawTextSize(playerid, PlayerTD[playerid][41], 51.000000, 27.500000);
PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][41], 1);
PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][41], 0);
PlayerTextDrawAlignment(playerid, PlayerTD[playerid][41], 1);
PlayerTextDrawColor(playerid, PlayerTD[playerid][41], -1);
PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][41], 255);
PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][41], 50);
PlayerTextDrawUseBox(playerid, PlayerTD[playerid][41], 1);
PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][41], 1);
PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][41], 0);

PlayerTD[playerid][42] = CreatePlayerTextDraw(playerid, 446.000000, 257.000000, "Level:");
PlayerTextDrawFont(playerid, PlayerTD[playerid][42], 1);
PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][42], 0.241667, 0.750000);
PlayerTextDrawTextSize(playerid, PlayerTD[playerid][42], 400.000000, 17.000000);
PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][42], 0);
PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][42], 0);
PlayerTextDrawAlignment(playerid, PlayerTD[playerid][42], 1);
PlayerTextDrawColor(playerid, PlayerTD[playerid][42], -1);
PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][42], 255);
PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][42], 50);
PlayerTextDrawUseBox(playerid, PlayerTD[playerid][42], 0);
PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][42], 1);
PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][42], 0);

PlayerTD[playerid][43] = CreatePlayerTextDraw(playerid, 444.000000, 265.000000, "Money:");
PlayerTextDrawFont(playerid, PlayerTD[playerid][43], 1);
PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][43], 0.241667, 0.750000);
PlayerTextDrawTextSize(playerid, PlayerTD[playerid][43], 400.000000, 17.000000);
PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][43], 0);
PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][43], 0);
PlayerTextDrawAlignment(playerid, PlayerTD[playerid][43], 1);
PlayerTextDrawColor(playerid, PlayerTD[playerid][43], -1);
PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][43], 255);
PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][43], 50);
PlayerTextDrawUseBox(playerid, PlayerTD[playerid][43], 0);
PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][43], 1);
PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][43], 0);

PlayerTD[playerid][44] = CreatePlayerTextDraw(playerid, 445.000000, 273.000000, "Age:");
PlayerTextDrawFont(playerid, PlayerTD[playerid][44], 1);
PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][44], 0.241667, 0.750000);
PlayerTextDrawTextSize(playerid, PlayerTD[playerid][44], 400.000000, 17.000000);
PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][44], 0);
PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][44], 0);
PlayerTextDrawAlignment(playerid, PlayerTD[playerid][44], 1);
PlayerTextDrawColor(playerid, PlayerTD[playerid][44], -1);
PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][44], 255);
PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][44], 50);
PlayerTextDrawUseBox(playerid, PlayerTD[playerid][44], 0);
PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][44], 1);
PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][44], 0);

phone_player_level[playerid] = CreatePlayerTextDraw(playerid, 473.000000, 257.000000, "1000");
PlayerTextDrawFont(playerid, phone_player_level[playerid], 1);
PlayerTextDrawLetterSize(playerid, phone_player_level[playerid], 0.241667, 0.750000);
PlayerTextDrawTextSize(playerid, phone_player_level[playerid], 400.000000, 17.000000);
PlayerTextDrawSetOutline(playerid, phone_player_level[playerid], 0);
PlayerTextDrawSetShadow(playerid, phone_player_level[playerid], 0);
PlayerTextDrawAlignment(playerid, phone_player_level[playerid], 1);
PlayerTextDrawColor(playerid, phone_player_level[playerid], -1);
PlayerTextDrawBackgroundColor(playerid, phone_player_level[playerid], 255);
PlayerTextDrawBoxColor(playerid, phone_player_level[playerid], 50);
PlayerTextDrawUseBox(playerid, phone_player_level[playerid], 0);
PlayerTextDrawSetProportional(playerid, phone_player_level[playerid], 1);
PlayerTextDrawSetSelectable(playerid, phone_player_level[playerid], 0);

phone_player_money[playerid] = CreatePlayerTextDraw(playerid, 473.000000, 266.000000, "1000");
PlayerTextDrawFont(playerid, phone_player_money[playerid], 1);
PlayerTextDrawLetterSize(playerid, phone_player_money[playerid], 0.241667, 0.750000);
PlayerTextDrawTextSize(playerid, phone_player_money[playerid], 400.000000, 17.000000);
PlayerTextDrawSetOutline(playerid, phone_player_money[playerid], 0);
PlayerTextDrawSetShadow(playerid, phone_player_money[playerid], 0);
PlayerTextDrawAlignment(playerid, phone_player_money[playerid], 1);
PlayerTextDrawColor(playerid, phone_player_money[playerid], -1);
PlayerTextDrawBackgroundColor(playerid, phone_player_money[playerid], 255);
PlayerTextDrawBoxColor(playerid, phone_player_money[playerid], 50);
PlayerTextDrawUseBox(playerid, phone_player_money[playerid], 0);
PlayerTextDrawSetProportional(playerid, phone_player_money[playerid], 1);
PlayerTextDrawSetSelectable(playerid, phone_player_money[playerid], 0);

phone_player_age[playerid] = CreatePlayerTextDraw(playerid, 464.000000, 273.000000, "200");
PlayerTextDrawFont(playerid, phone_player_age[playerid], 1);
PlayerTextDrawLetterSize(playerid, phone_player_age[playerid], 0.241667, 0.750000);
PlayerTextDrawTextSize(playerid, phone_player_age[playerid], 400.000000, 17.000000);
PlayerTextDrawSetOutline(playerid, phone_player_age[playerid], 0);
PlayerTextDrawSetShadow(playerid, phone_player_age[playerid], 0);
PlayerTextDrawAlignment(playerid, phone_player_age[playerid], 1);
PlayerTextDrawColor(playerid, phone_player_age[playerid], -1);
PlayerTextDrawBackgroundColor(playerid, phone_player_age[playerid], 255);
PlayerTextDrawBoxColor(playerid, phone_player_age[playerid], 50);
PlayerTextDrawUseBox(playerid, phone_player_age[playerid], 0);
PlayerTextDrawSetProportional(playerid, phone_player_age[playerid], 1);
PlayerTextDrawSetSelectable(playerid, phone_player_age[playerid], 0);

