/*
This file was generated by Nickk's TextDraw editor script
Nickk888 is the author of the NTD script
*/

//Variables
new Text:PublicTD[23];

//Textdraws
PublicTD[0] = TextDrawCreate(38.000000, 2.000000, "_");
TextDrawFont(PublicTD[0], 1);
TextDrawLetterSize(PublicTD[0], 0.000000, 49.649982);
TextDrawTextSize(PublicTD[0], 333.500000, 352.500000);
TextDrawSetOutline(PublicTD[0], 1);
TextDrawSetShadow(PublicTD[0], 0);
TextDrawAlignment(PublicTD[0], 2);
TextDrawColor(PublicTD[0], -1);
TextDrawBackgroundColor(PublicTD[0], 255);
TextDrawBoxColor(PublicTD[0], 572662527);
TextDrawUseBox(PublicTD[0], 1);
TextDrawSetProportional(PublicTD[0], 1);
TextDrawSetSelectable(PublicTD[0], 0);

PublicTD[1] = TextDrawCreate(99.000000, 125.000000, "Create Your");
TextDrawFont(PublicTD[1], 1);
TextDrawLetterSize(PublicTD[1], 0.208333, 0.800000);
TextDrawTextSize(PublicTD[1], 400.000000, 17.000000);
TextDrawSetOutline(PublicTD[1], 0);
TextDrawSetShadow(PublicTD[1], 0);
TextDrawAlignment(PublicTD[1], 3);
TextDrawColor(PublicTD[1], -1);
TextDrawBackgroundColor(PublicTD[1], 255);
TextDrawBoxColor(PublicTD[1], 50);
TextDrawUseBox(PublicTD[1], 0);
TextDrawSetProportional(PublicTD[1], 1);
TextDrawSetSelectable(PublicTD[1], 0);

PublicTD[2] = TextDrawCreate(164.000000, 125.000000, "Character Identity");
TextDrawFont(PublicTD[2], 1);
TextDrawLetterSize(PublicTD[2], 0.208333, 0.800000);
TextDrawTextSize(PublicTD[2], 400.000000, 17.000000);
TextDrawSetOutline(PublicTD[2], 0);
TextDrawSetShadow(PublicTD[2], 0);
TextDrawAlignment(PublicTD[2], 3);
TextDrawColor(PublicTD[2], -1);
TextDrawBackgroundColor(PublicTD[2], 255);
TextDrawBoxColor(PublicTD[2], 50);
TextDrawUseBox(PublicTD[2], 0);
TextDrawSetProportional(PublicTD[2], 1);
TextDrawSetSelectable(PublicTD[2], 0);

PublicTD[3] = TextDrawCreate(-50.000000, 133.000000, "Preview_Model");
TextDrawFont(PublicTD[3], 5);
TextDrawLetterSize(PublicTD[3], 0.600000, 2.000000);
TextDrawTextSize(PublicTD[3], 323.000000, 47.000000);
TextDrawSetOutline(PublicTD[3], 0);
TextDrawSetShadow(PublicTD[3], 0);
TextDrawAlignment(PublicTD[3], 1);
TextDrawColor(PublicTD[3], 645986303);
TextDrawBackgroundColor(PublicTD[3], 0);
TextDrawBoxColor(PublicTD[3], 255);
TextDrawUseBox(PublicTD[3], 0);
TextDrawSetProportional(PublicTD[3], 1);
TextDrawSetSelectable(PublicTD[3], 0);
TextDrawSetPreviewModel(PublicTD[3], 19873);
TextDrawSetPreviewRot(PublicTD[3], 90.000000, 90.000000, 90.000000, 1.189998);
TextDrawSetPreviewVehCol(PublicTD[3], 1, 1);

PublicTD[4] = TextDrawCreate(138.000000, 150.000000, "First Name");
TextDrawFont(PublicTD[4], 1);
TextDrawLetterSize(PublicTD[4], 0.291666, 1.299999);
TextDrawTextSize(PublicTD[4], 400.000000, 17.000000);
TextDrawSetOutline(PublicTD[4], 0);
TextDrawSetShadow(PublicTD[4], 0);
TextDrawAlignment(PublicTD[4], 3);
TextDrawColor(PublicTD[4], -1);
TextDrawBackgroundColor(PublicTD[4], 255);
TextDrawBoxColor(PublicTD[4], 50);
TextDrawUseBox(PublicTD[4], 0);
TextDrawSetProportional(PublicTD[4], 1);
TextDrawSetSelectable(PublicTD[4], 0);

PublicTD[5] = TextDrawCreate(-50.000000, 161.000000, "Preview_Model");
TextDrawFont(PublicTD[5], 5);
TextDrawLetterSize(PublicTD[5], 0.600000, 2.000000);
TextDrawTextSize(PublicTD[5], 323.000000, 47.000000);
TextDrawSetOutline(PublicTD[5], 0);
TextDrawSetShadow(PublicTD[5], 0);
TextDrawAlignment(PublicTD[5], 1);
TextDrawColor(PublicTD[5], 645986303);
TextDrawBackgroundColor(PublicTD[5], 0);
TextDrawBoxColor(PublicTD[5], 255);
TextDrawUseBox(PublicTD[5], 0);
TextDrawSetProportional(PublicTD[5], 1);
TextDrawSetSelectable(PublicTD[5], 0);
TextDrawSetPreviewModel(PublicTD[5], 19873);
TextDrawSetPreviewRot(PublicTD[5], 90.000000, 90.000000, 90.000000, 1.189998);
TextDrawSetPreviewVehCol(PublicTD[5], 1, 1);

PublicTD[6] = TextDrawCreate(137.000000, 178.000000, "Last Name");
TextDrawFont(PublicTD[6], 1);
TextDrawLetterSize(PublicTD[6], 0.291666, 1.299999);
TextDrawTextSize(PublicTD[6], 400.000000, 17.000000);
TextDrawSetOutline(PublicTD[6], 0);
TextDrawSetShadow(PublicTD[6], 0);
TextDrawAlignment(PublicTD[6], 3);
TextDrawColor(PublicTD[6], -1);
TextDrawBackgroundColor(PublicTD[6], 255);
TextDrawBoxColor(PublicTD[6], 50);
TextDrawUseBox(PublicTD[6], 0);
TextDrawSetProportional(PublicTD[6], 1);
TextDrawSetSelectable(PublicTD[6], 0);

PublicTD[7] = TextDrawCreate(-50.000000, 188.000000, "Preview_Model");
TextDrawFont(PublicTD[7], 5);
TextDrawLetterSize(PublicTD[7], 0.600000, 2.000000);
TextDrawTextSize(PublicTD[7], 323.000000, 47.000000);
TextDrawSetOutline(PublicTD[7], 0);
TextDrawSetShadow(PublicTD[7], 0);
TextDrawAlignment(PublicTD[7], 1);
TextDrawColor(PublicTD[7], 645986303);
TextDrawBackgroundColor(PublicTD[7], 0);
TextDrawBoxColor(PublicTD[7], 255);
TextDrawUseBox(PublicTD[7], 0);
TextDrawSetProportional(PublicTD[7], 1);
TextDrawSetSelectable(PublicTD[7], 0);
TextDrawSetPreviewModel(PublicTD[7], 19873);
TextDrawSetPreviewRot(PublicTD[7], 90.000000, 90.000000, 90.000000, 1.189998);
TextDrawSetPreviewVehCol(PublicTD[7], 1, 1);

PublicTD[8] = TextDrawCreate(144.000000, 205.000000, "Date of Birth");
TextDrawFont(PublicTD[8], 1);
TextDrawLetterSize(PublicTD[8], 0.291666, 1.299999);
TextDrawTextSize(PublicTD[8], 400.000000, 17.000000);
TextDrawSetOutline(PublicTD[8], 0);
TextDrawSetShadow(PublicTD[8], 0);
TextDrawAlignment(PublicTD[8], 3);
TextDrawColor(PublicTD[8], -1);
TextDrawBackgroundColor(PublicTD[8], 255);
TextDrawBoxColor(PublicTD[8], 50);
TextDrawUseBox(PublicTD[8], 0);
TextDrawSetProportional(PublicTD[8], 1);
TextDrawSetSelectable(PublicTD[8], 0);

PublicTD[9] = TextDrawCreate(-50.000000, 215.000000, "Preview_Model");
TextDrawFont(PublicTD[9], 5);
TextDrawLetterSize(PublicTD[9], 0.600000, 2.000000);
TextDrawTextSize(PublicTD[9], 323.000000, 47.000000);
TextDrawSetOutline(PublicTD[9], 0);
TextDrawSetShadow(PublicTD[9], 0);
TextDrawAlignment(PublicTD[9], 1);
TextDrawColor(PublicTD[9], 645986303);
TextDrawBackgroundColor(PublicTD[9], 0);
TextDrawBoxColor(PublicTD[9], 255);
TextDrawUseBox(PublicTD[9], 0);
TextDrawSetProportional(PublicTD[9], 1);
TextDrawSetSelectable(PublicTD[9], 0);
TextDrawSetPreviewModel(PublicTD[9], 19873);
TextDrawSetPreviewRot(PublicTD[9], 90.000000, 90.000000, 90.000000, 1.189998);
TextDrawSetPreviewVehCol(PublicTD[9], 1, 1);

PublicTD[10] = TextDrawCreate(128.000000, 232.000000, "Gender");
TextDrawFont(PublicTD[10], 1);
TextDrawLetterSize(PublicTD[10], 0.291666, 1.299999);
TextDrawTextSize(PublicTD[10], 400.000000, 17.000000);
TextDrawSetOutline(PublicTD[10], 0);
TextDrawSetShadow(PublicTD[10], 0);
TextDrawAlignment(PublicTD[10], 3);
TextDrawColor(PublicTD[10], -1);
TextDrawBackgroundColor(PublicTD[10], 255);
TextDrawBoxColor(PublicTD[10], 50);
TextDrawUseBox(PublicTD[10], 0);
TextDrawSetProportional(PublicTD[10], 1);
TextDrawSetSelectable(PublicTD[10], 0);

PublicTD[11] = TextDrawCreate(-50.000000, 242.000000, "Preview_Model");
TextDrawFont(PublicTD[11], 5);
TextDrawLetterSize(PublicTD[11], 0.600000, 2.000000);
TextDrawTextSize(PublicTD[11], 323.000000, 47.000000);
TextDrawSetOutline(PublicTD[11], 0);
TextDrawSetShadow(PublicTD[11], 0);
TextDrawAlignment(PublicTD[11], 1);
TextDrawColor(PublicTD[11], 645986303);
TextDrawBackgroundColor(PublicTD[11], 0);
TextDrawBoxColor(PublicTD[11], 255);
TextDrawUseBox(PublicTD[11], 0);
TextDrawSetProportional(PublicTD[11], 1);
TextDrawSetSelectable(PublicTD[11], 0);
TextDrawSetPreviewModel(PublicTD[11], 19873);
TextDrawSetPreviewRot(PublicTD[11], 90.000000, 90.000000, 90.000000, 1.189998);
TextDrawSetPreviewVehCol(PublicTD[11], 1, 1);

PublicTD[12] = TextDrawCreate(126.000000, 259.000000, "Height");
TextDrawFont(PublicTD[12], 1);
TextDrawLetterSize(PublicTD[12], 0.291666, 1.299999);
TextDrawTextSize(PublicTD[12], 400.000000, 17.000000);
TextDrawSetOutline(PublicTD[12], 0);
TextDrawSetShadow(PublicTD[12], 0);
TextDrawAlignment(PublicTD[12], 3);
TextDrawColor(PublicTD[12], -1);
TextDrawBackgroundColor(PublicTD[12], 255);
TextDrawBoxColor(PublicTD[12], 50);
TextDrawUseBox(PublicTD[12], 0);
TextDrawSetProportional(PublicTD[12], 1);
TextDrawSetSelectable(PublicTD[12], 0);

PublicTD[13] = TextDrawCreate(-141.000000, 168.000000, "Preview_Model");
TextDrawFont(PublicTD[13], 5);
TextDrawLetterSize(PublicTD[13], 0.600000, 2.000000);
TextDrawTextSize(PublicTD[13], 492.000000, 4.500000);
TextDrawSetOutline(PublicTD[13], 0);
TextDrawSetShadow(PublicTD[13], 0);
TextDrawAlignment(PublicTD[13], 1);
TextDrawColor(PublicTD[13], -1);
TextDrawBackgroundColor(PublicTD[13], 0);
TextDrawBoxColor(PublicTD[13], 255);
TextDrawUseBox(PublicTD[13], 0);
TextDrawSetProportional(PublicTD[13], 1);
TextDrawSetSelectable(PublicTD[13], 0);
TextDrawSetPreviewModel(PublicTD[13], 3003);
TextDrawSetPreviewRot(PublicTD[13], 90.000000, 90.000000, 90.000000, 1.009999);
TextDrawSetPreviewVehCol(PublicTD[13], 1, 1);

PublicTD[14] = TextDrawCreate(-141.000000, 196.000000, "Preview_Model");
TextDrawFont(PublicTD[14], 5);
TextDrawLetterSize(PublicTD[14], 0.600000, 2.000000);
TextDrawTextSize(PublicTD[14], 492.000000, 4.500000);
TextDrawSetOutline(PublicTD[14], 0);
TextDrawSetShadow(PublicTD[14], 0);
TextDrawAlignment(PublicTD[14], 1);
TextDrawColor(PublicTD[14], -1);
TextDrawBackgroundColor(PublicTD[14], 0);
TextDrawBoxColor(PublicTD[14], 255);
TextDrawUseBox(PublicTD[14], 0);
TextDrawSetProportional(PublicTD[14], 1);
TextDrawSetSelectable(PublicTD[14], 0);
TextDrawSetPreviewModel(PublicTD[14], 3003);
TextDrawSetPreviewRot(PublicTD[14], 90.000000, 90.000000, 90.000000, 1.009999);
TextDrawSetPreviewVehCol(PublicTD[14], 1, 1);

PublicTD[15] = TextDrawCreate(-141.000000, 222.000000, "Preview_Model");
TextDrawFont(PublicTD[15], 5);
TextDrawLetterSize(PublicTD[15], 0.600000, 2.000000);
TextDrawTextSize(PublicTD[15], 492.000000, 4.500000);
TextDrawSetOutline(PublicTD[15], 0);
TextDrawSetShadow(PublicTD[15], 0);
TextDrawAlignment(PublicTD[15], 1);
TextDrawColor(PublicTD[15], -1);
TextDrawBackgroundColor(PublicTD[15], 0);
TextDrawBoxColor(PublicTD[15], 255);
TextDrawUseBox(PublicTD[15], 0);
TextDrawSetProportional(PublicTD[15], 1);
TextDrawSetSelectable(PublicTD[15], 0);
TextDrawSetPreviewModel(PublicTD[15], 3003);
TextDrawSetPreviewRot(PublicTD[15], 90.000000, 90.000000, 90.000000, 1.009999);
TextDrawSetPreviewVehCol(PublicTD[15], 1, 1);

PublicTD[16] = TextDrawCreate(-141.000000, 249.000000, "Preview_Model");
TextDrawFont(PublicTD[16], 5);
TextDrawLetterSize(PublicTD[16], 0.600000, 2.000000);
TextDrawTextSize(PublicTD[16], 492.000000, 4.500000);
TextDrawSetOutline(PublicTD[16], 0);
TextDrawSetShadow(PublicTD[16], 0);
TextDrawAlignment(PublicTD[16], 1);
TextDrawColor(PublicTD[16], -1);
TextDrawBackgroundColor(PublicTD[16], 0);
TextDrawBoxColor(PublicTD[16], 255);
TextDrawUseBox(PublicTD[16], 0);
TextDrawSetProportional(PublicTD[16], 1);
TextDrawSetSelectable(PublicTD[16], 0);
TextDrawSetPreviewModel(PublicTD[16], 3003);
TextDrawSetPreviewRot(PublicTD[16], 90.000000, 90.000000, 90.000000, 1.009999);
TextDrawSetPreviewVehCol(PublicTD[16], 1, 1);

PublicTD[17] = TextDrawCreate(-141.000000, 277.000000, "Preview_Model");
TextDrawFont(PublicTD[17], 5);
TextDrawLetterSize(PublicTD[17], 0.600000, 2.000000);
TextDrawTextSize(PublicTD[17], 492.000000, 4.500000);
TextDrawSetOutline(PublicTD[17], 0);
TextDrawSetShadow(PublicTD[17], 0);
TextDrawAlignment(PublicTD[17], 1);
TextDrawColor(PublicTD[17], -1);
TextDrawBackgroundColor(PublicTD[17], 0);
TextDrawBoxColor(PublicTD[17], 255);
TextDrawUseBox(PublicTD[17], 0);
TextDrawSetProportional(PublicTD[17], 1);
TextDrawSetSelectable(PublicTD[17], 0);
TextDrawSetPreviewModel(PublicTD[17], 3003);
TextDrawSetPreviewRot(PublicTD[17], 90.000000, 90.000000, 90.000000, 1.009999);
TextDrawSetPreviewVehCol(PublicTD[17], 1, 1);

PublicTD[18] = TextDrawCreate(-12.000000, 340.000000, "Preview_Model");
TextDrawFont(PublicTD[18], 5);
TextDrawLetterSize(PublicTD[18], 0.600000, 2.000000);
TextDrawTextSize(PublicTD[18], 245.000000, -71.500000);
TextDrawSetOutline(PublicTD[18], 0);
TextDrawSetShadow(PublicTD[18], 0);
TextDrawAlignment(PublicTD[18], 1);
TextDrawColor(PublicTD[18], 513538047);
TextDrawBackgroundColor(PublicTD[18], 0);
TextDrawBoxColor(PublicTD[18], 255);
TextDrawUseBox(PublicTD[18], 0);
TextDrawSetProportional(PublicTD[18], 1);
TextDrawSetSelectable(PublicTD[18], 0);
TextDrawSetPreviewModel(PublicTD[18], 19827);
TextDrawSetPreviewRot(PublicTD[18], 270.000000, 90.000000, 90.000000, 1.009999);
TextDrawSetPreviewVehCol(PublicTD[18], 1, 1);

PublicTD[19] = TextDrawCreate(135.000000, 299.000000, "Create Identity");
TextDrawFont(PublicTD[19], 1);
TextDrawLetterSize(PublicTD[19], 0.195832, 0.899999);
TextDrawTextSize(PublicTD[19], 400.000000, 17.000000);
TextDrawSetOutline(PublicTD[19], 0);
TextDrawSetShadow(PublicTD[19], 0);
TextDrawAlignment(PublicTD[19], 3);
TextDrawColor(PublicTD[19], -1);
TextDrawBackgroundColor(PublicTD[19], 255);
TextDrawBoxColor(PublicTD[19], 50);
TextDrawUseBox(PublicTD[19], 0);
TextDrawSetProportional(PublicTD[19], 1);
TextDrawSetSelectable(PublicTD[19], 0);

PublicTD[20] = TextDrawCreate(86.000000, 127.000000, "Preview_Model");
TextDrawFont(PublicTD[20], 5);
TextDrawLetterSize(PublicTD[20], 0.600000, 2.000000);
TextDrawTextSize(PublicTD[20], 54.000000, -71.500000);
TextDrawSetOutline(PublicTD[20], 0);
TextDrawSetShadow(PublicTD[20], 0);
TextDrawAlignment(PublicTD[20], 1);
TextDrawColor(PublicTD[20], -1378294017);
TextDrawBackgroundColor(PublicTD[20], 0);
TextDrawBoxColor(PublicTD[20], 255);
TextDrawUseBox(PublicTD[20], 0);
TextDrawSetProportional(PublicTD[20], 1);
TextDrawSetSelectable(PublicTD[20], 0);
TextDrawSetPreviewModel(PublicTD[20], 1898);
TextDrawSetPreviewRot(PublicTD[20], 0.000000, -20.000000, 270.000000, 1.009999);
TextDrawSetPreviewVehCol(PublicTD[20], 1, 1);

PublicTD[21] = TextDrawCreate(70.000000, 125.000000, "Preview_Model");
TextDrawFont(PublicTD[21], 5);
TextDrawLetterSize(PublicTD[21], 0.600000, 2.000000);
TextDrawTextSize(PublicTD[21], 54.000000, -71.500000);
TextDrawSetOutline(PublicTD[21], 0);
TextDrawSetShadow(PublicTD[21], 0);
TextDrawAlignment(PublicTD[21], 1);
TextDrawColor(PublicTD[21], -1378294017);
TextDrawBackgroundColor(PublicTD[21], 0);
TextDrawBoxColor(PublicTD[21], 255);
TextDrawUseBox(PublicTD[21], 0);
TextDrawSetProportional(PublicTD[21], 1);
TextDrawSetSelectable(PublicTD[21], 0);
TextDrawSetPreviewModel(PublicTD[21], 1898);
TextDrawSetPreviewRot(PublicTD[21], 0.000000, 15.000000, 270.000000, 1.009999);
TextDrawSetPreviewVehCol(PublicTD[21], 1, 1);

PublicTD[22] = TextDrawCreate(87.000000, 129.000000, "Preview_Model");
TextDrawFont(PublicTD[22], 5);
TextDrawLetterSize(PublicTD[22], 0.600000, 2.000000);
TextDrawTextSize(PublicTD[22], 54.000000, -71.500000);
TextDrawSetOutline(PublicTD[22], 0);
TextDrawSetShadow(PublicTD[22], 0);
TextDrawAlignment(PublicTD[22], 1);
TextDrawColor(PublicTD[22], -1378294017);
TextDrawBackgroundColor(PublicTD[22], 0);
TextDrawBoxColor(PublicTD[22], 255);
TextDrawUseBox(PublicTD[22], 0);
TextDrawSetProportional(PublicTD[22], 1);
TextDrawSetSelectable(PublicTD[22], 0);
TextDrawSetPreviewModel(PublicTD[22], 1898);
TextDrawSetPreviewRot(PublicTD[22], 0.000000, 15.000000, 270.000000, 1.009999);
TextDrawSetPreviewVehCol(PublicTD[22], 1, 1);


//Player Textdraws

/*Player Progress Bars
Requires "progress2" include by Southclaws
Download: https://github.com/Southclaws/progress2/releases */
