/*
This file was generated by Nickk's TextDraw editor script
Nickk888 is the author of the NTD script
*/

//Variables
new Text:PublicTD[11];

//Textdraws
PublicTD[0] = TextDrawCreate(631.000000, 212.000000, "_");
TextDrawFont(PublicTD[0], 1);
TextDrawLetterSize(PublicTD[0], 0.383332, 16.700019);
TextDrawTextSize(PublicTD[0], 506.000000, 17.000000);
TextDrawSetOutline(PublicTD[0], 1);
TextDrawSetShadow(PublicTD[0], 0);
TextDrawAlignment(PublicTD[0], 1);
TextDrawColor(PublicTD[0], -1);
TextDrawBackgroundColor(PublicTD[0], 255);
TextDrawBoxColor(PublicTD[0], 50);
TextDrawUseBox(PublicTD[0], 1);
TextDrawSetProportional(PublicTD[0], 1);
TextDrawSetSelectable(PublicTD[0], 0);

PublicTD[1] = TextDrawCreate(511.000000, 212.000000, "Welcom_to_servername");
TextDrawFont(PublicTD[1], 1);
TextDrawLetterSize(PublicTD[1], 0.174999, 1.399999);
TextDrawTextSize(PublicTD[1], 400.000000, 17.000000);
TextDrawSetOutline(PublicTD[1], 0);
TextDrawSetShadow(PublicTD[1], 0);
TextDrawAlignment(PublicTD[1], 1);
TextDrawColor(PublicTD[1], -1);
TextDrawBackgroundColor(PublicTD[1], 255);
TextDrawBoxColor(PublicTD[1], 50);
TextDrawUseBox(PublicTD[1], 0);
TextDrawSetProportional(PublicTD[1], 1);
TextDrawSetSelectable(PublicTD[1], 0);

PublicTD[2] = TextDrawCreate(527.000000, 255.000000, "_");
TextDrawFont(PublicTD[2], 1);
TextDrawLetterSize(PublicTD[2], 0.150000, 1.999992);
TextDrawTextSize(PublicTD[2], 612.500000, 17.000000);
TextDrawSetOutline(PublicTD[2], 1);
TextDrawSetShadow(PublicTD[2], 0);
TextDrawAlignment(PublicTD[2], 1);
TextDrawColor(PublicTD[2], -1);
TextDrawBackgroundColor(PublicTD[2], 255);
TextDrawBoxColor(PublicTD[2], 50);
TextDrawUseBox(PublicTD[2], 1);
TextDrawSetProportional(PublicTD[2], 1);
TextDrawSetSelectable(PublicTD[2], 0);

PublicTD[3] = TextDrawCreate(568.000000, 256.000000, "Nama");
TextDrawFont(PublicTD[3], 1);
TextDrawLetterSize(PublicTD[3], 0.174999, 1.399999);
TextDrawTextSize(PublicTD[3], 400.000000, 17.000000);
TextDrawSetOutline(PublicTD[3], 0);
TextDrawSetShadow(PublicTD[3], 0);
TextDrawAlignment(PublicTD[3], 2);
TextDrawColor(PublicTD[3], -1);
TextDrawBackgroundColor(PublicTD[3], 255);
TextDrawBoxColor(PublicTD[3], 50);
TextDrawUseBox(PublicTD[3], 0);
TextDrawSetProportional(PublicTD[3], 1);
TextDrawSetSelectable(PublicTD[3], 1);

PublicTD[4] = TextDrawCreate(527.000000, 280.000000, "_");
TextDrawFont(PublicTD[4], 1);
TextDrawLetterSize(PublicTD[4], 0.150000, 1.999992);
TextDrawTextSize(PublicTD[4], 612.500000, 17.000000);
TextDrawSetOutline(PublicTD[4], 1);
TextDrawSetShadow(PublicTD[4], 0);
TextDrawAlignment(PublicTD[4], 1);
TextDrawColor(PublicTD[4], -1);
TextDrawBackgroundColor(PublicTD[4], 255);
TextDrawBoxColor(PublicTD[4], 50);
TextDrawUseBox(PublicTD[4], 1);
TextDrawSetProportional(PublicTD[4], 1);
TextDrawSetSelectable(PublicTD[4], 0);

PublicTD[5] = TextDrawCreate(569.000000, 281.000000, "Tanggal_Lahir");
TextDrawFont(PublicTD[5], 1);
TextDrawLetterSize(PublicTD[5], 0.174999, 1.399999);
TextDrawTextSize(PublicTD[5], 400.000000, 17.000000);
TextDrawSetOutline(PublicTD[5], 0);
TextDrawSetShadow(PublicTD[5], 0);
TextDrawAlignment(PublicTD[5], 2);
TextDrawColor(PublicTD[5], -1);
TextDrawBackgroundColor(PublicTD[5], 255);
TextDrawBoxColor(PublicTD[5], 50);
TextDrawUseBox(PublicTD[5], 0);
TextDrawSetProportional(PublicTD[5], 1);
TextDrawSetSelectable(PublicTD[5], 1);

PublicTD[6] = TextDrawCreate(527.000000, 307.000000, "_");
TextDrawFont(PublicTD[6], 1);
TextDrawLetterSize(PublicTD[6], 0.150000, 1.999992);
TextDrawTextSize(PublicTD[6], 612.500000, 17.000000);
TextDrawSetOutline(PublicTD[6], 1);
TextDrawSetShadow(PublicTD[6], 0);
TextDrawAlignment(PublicTD[6], 1);
TextDrawColor(PublicTD[6], -1);
TextDrawBackgroundColor(PublicTD[6], 255);
TextDrawBoxColor(PublicTD[6], 50);
TextDrawUseBox(PublicTD[6], 1);
TextDrawSetProportional(PublicTD[6], 1);
TextDrawSetSelectable(PublicTD[6], 1);

PublicTD[7] = TextDrawCreate(568.000000, 308.000000, "Jenis_Kelamin");
TextDrawFont(PublicTD[7], 1);
TextDrawLetterSize(PublicTD[7], 0.174999, 1.399999);
TextDrawTextSize(PublicTD[7], 400.000000, 17.000000);
TextDrawSetOutline(PublicTD[7], 0);
TextDrawSetShadow(PublicTD[7], 0);
TextDrawAlignment(PublicTD[7], 2);
TextDrawColor(PublicTD[7], -1);
TextDrawBackgroundColor(PublicTD[7], 255);
TextDrawBoxColor(PublicTD[7], 50);
TextDrawUseBox(PublicTD[7], 0);
TextDrawSetProportional(PublicTD[7], 1);
TextDrawSetSelectable(PublicTD[7], 1);

PublicTD[8] = TextDrawCreate(527.000000, 333.000000, "_");
TextDrawFont(PublicTD[8], 1);
TextDrawLetterSize(PublicTD[8], 0.150000, 1.999992);
TextDrawTextSize(PublicTD[8], 612.500000, 17.000000);
TextDrawSetOutline(PublicTD[8], 1);
TextDrawSetShadow(PublicTD[8], 0);
TextDrawAlignment(PublicTD[8], 1);
TextDrawColor(PublicTD[8], -1);
TextDrawBackgroundColor(PublicTD[8], 255);
TextDrawBoxColor(PublicTD[8], 50);
TextDrawUseBox(PublicTD[8], 1);
TextDrawSetProportional(PublicTD[8], 1);
TextDrawSetSelectable(PublicTD[8], 0);

PublicTD[9] = TextDrawCreate(569.000000, 334.000000, "Confrim");
TextDrawFont(PublicTD[9], 1);
TextDrawLetterSize(PublicTD[9], 0.174999, 1.399999);
TextDrawTextSize(PublicTD[9], 400.000000, 17.000000);
TextDrawSetOutline(PublicTD[9], 0);
TextDrawSetShadow(PublicTD[9], 0);
TextDrawAlignment(PublicTD[9], 2);
TextDrawColor(PublicTD[9], -1);
TextDrawBackgroundColor(PublicTD[9], 255);
TextDrawBoxColor(PublicTD[9], 50);
TextDrawUseBox(PublicTD[9], 0);
TextDrawSetProportional(PublicTD[9], 1);
TextDrawSetSelectable(PublicTD[9], 1);

PublicTD[10] = TextDrawCreate(526.000000, 238.000000, "Pembuatan_Character");
TextDrawFont(PublicTD[10], 1);
TextDrawLetterSize(PublicTD[10], 0.137500, 1.149999);
TextDrawTextSize(PublicTD[10], 400.000000, 17.000000);
TextDrawSetOutline(PublicTD[10], 0);
TextDrawSetShadow(PublicTD[10], 0);
TextDrawAlignment(PublicTD[10], 1);
TextDrawColor(PublicTD[10], -1);
TextDrawBackgroundColor(PublicTD[10], 255);
TextDrawBoxColor(PublicTD[10], 50);
TextDrawUseBox(PublicTD[10], 0);
TextDrawSetProportional(PublicTD[10], 1);
TextDrawSetSelectable(PublicTD[10], 0);


//Player Textdraws

/*Player Progress Bars
Requires "progress2" include by Southclaws
Download: https://github.com/Southclaws/progress2/releases */
