new Text: Ditzy_GlobalTD[4];

Ditzy_GlobalTD[0] = TextDrawCreate(320.000, 10.000, "S");
TextDrawLetterSize(Ditzy_GlobalTD[0], 1.159, 2.999);
TextDrawAlignment(Ditzy_GlobalTD[0], 2);
TextDrawColor(Ditzy_GlobalTD[0], -1);
TextDrawSetShadow(Ditzy_GlobalTD[0], 1);
TextDrawSetOutline(Ditzy_GlobalTD[0], 1);
TextDrawBackgroundColor(Ditzy_GlobalTD[0], 255);
TextDrawFont(Ditzy_GlobalTD[0], 1);
TextDrawSetProportional(Ditzy_GlobalTD[0], 1);

Ditzy_GlobalTD[1] = TextDrawCreate(319.500, 12.000, "N");
TextDrawLetterSize(Ditzy_GlobalTD[1], 0.479, 2.499);
TextDrawAlignment(Ditzy_GlobalTD[1], 2);
TextDrawColor(Ditzy_GlobalTD[1], -1);
TextDrawSetShadow(Ditzy_GlobalTD[1], 1);
TextDrawSetOutline(Ditzy_GlobalTD[1], 1);
TextDrawBackgroundColor(Ditzy_GlobalTD[1], 255);
TextDrawFont(Ditzy_GlobalTD[1], 1);
TextDrawSetProportional(Ditzy_GlobalTD[1], 1);

Ditzy_GlobalTD[2] = TextDrawCreate(320.500, 38.000, "NAME KONTOL");
TextDrawLetterSize(Ditzy_GlobalTD[2], 0.269, 1.500);
TextDrawAlignment(Ditzy_GlobalTD[2], 2);
TextDrawColor(Ditzy_GlobalTD[2], -1);
TextDrawSetShadow(Ditzy_GlobalTD[2], 1);
TextDrawSetOutline(Ditzy_GlobalTD[2], 1);
TextDrawBackgroundColor(Ditzy_GlobalTD[2], 255);
TextDrawFont(Ditzy_GlobalTD[2], 1);
TextDrawSetProportional(Ditzy_GlobalTD[2], 1);

Ditzy_GlobalTD[3] = TextDrawCreate(320.500, 39.000, "NAME KONTOL");
TextDrawLetterSize(Ditzy_GlobalTD[3], 0.269, 1.500);
TextDrawAlignment(Ditzy_GlobalTD[3], 2);
TextDrawColor(Ditzy_GlobalTD[3], -1);
TextDrawSetShadow(Ditzy_GlobalTD[3], 1);
TextDrawSetOutline(Ditzy_GlobalTD[3], 1);
TextDrawBackgroundColor(Ditzy_GlobalTD[3], 255);
TextDrawFont(Ditzy_GlobalTD[3], 1);
TextDrawSetProportional(Ditzy_GlobalTD[3], 1);

