/*
This file was generated by Nickk's TextDraw editor script
Nickk888 is the author of the NTD script
*/

//Variables
new Text:PublicTD[22];
new PlayerText:PlayerTD[MAX_PLAYERS][1];
new Text:hudLapar;
new Text:hudHaus;

//Textdraws
PublicTD[0] = TextDrawCreate(644.000000, 385.000000, "_");
TextDrawFont(PublicTD[0], 1);
TextDrawLetterSize(PublicTD[0], 0.925000, 6.449999);
TextDrawTextSize(PublicTD[0], 536.500000, 17.000000);
TextDrawSetOutline(PublicTD[0], 1);
TextDrawSetShadow(PublicTD[0], 0);
TextDrawAlignment(PublicTD[0], 1);
TextDrawColor(PublicTD[0], -1);
TextDrawBackgroundColor(PublicTD[0], 255);
TextDrawBoxColor(PublicTD[0], 50);
TextDrawUseBox(PublicTD[0], 1);
TextDrawSetProportional(PublicTD[0], 1);
TextDrawSetSelectable(PublicTD[0], 0);

hudLapar = TextDrawCreate(571.000000, 392.000000, "ld_bum:blkdot");
TextDrawFont(hudLapar, 4);
TextDrawLetterSize(hudLapar, 0.600000, 2.000000);
TextDrawTextSize(hudLapar, 67.000000, 14.500000);
TextDrawSetOutline(hudLapar, 1);
TextDrawSetShadow(hudLapar, 0);
TextDrawAlignment(hudLapar, 1);
TextDrawColor(hudLapar, -764862721);
TextDrawBackgroundColor(hudLapar, 255);
TextDrawBoxColor(hudLapar, 50);
TextDrawUseBox(hudLapar, 1);
TextDrawSetProportional(hudLapar, 1);
TextDrawSetSelectable(hudLapar, 0);

PublicTD[1] = TextDrawCreate(597.000000, 394.000000, "100%");
TextDrawFont(PublicTD[1], 1);
TextDrawLetterSize(PublicTD[1], 0.175000, 0.850000);
TextDrawTextSize(PublicTD[1], 400.000000, 17.000000);
TextDrawSetOutline(PublicTD[1], 0);
TextDrawSetShadow(PublicTD[1], 0);
TextDrawAlignment(PublicTD[1], 1);
TextDrawColor(PublicTD[1], -1);
TextDrawBackgroundColor(PublicTD[1], 255);
TextDrawBoxColor(PublicTD[1], 50);
TextDrawUseBox(PublicTD[1], 0);
TextDrawSetProportional(PublicTD[1], 1);
TextDrawSetSelectable(PublicTD[1], 0);

PublicTD[2] = TextDrawCreate(543.000000, 394.000000, "Hunger");
TextDrawFont(PublicTD[2], 1);
TextDrawLetterSize(PublicTD[2], 0.175000, 0.850000);
TextDrawTextSize(PublicTD[2], 400.000000, 17.000000);
TextDrawSetOutline(PublicTD[2], 0);
TextDrawSetShadow(PublicTD[2], 0);
TextDrawAlignment(PublicTD[2], 1);
TextDrawColor(PublicTD[2], -1);
TextDrawBackgroundColor(PublicTD[2], 255);
TextDrawBoxColor(PublicTD[2], 50);
TextDrawUseBox(PublicTD[2], 0);
TextDrawSetProportional(PublicTD[2], 1);
TextDrawSetSelectable(PublicTD[2], 0);

hudHaus = TextDrawCreate(571.000000, 409.000000, "ld_bum:blkdot");
TextDrawFont(hudHaus, 4);
TextDrawLetterSize(hudHaus, 0.600000, 2.000000);
TextDrawTextSize(hudHaus, 67.000000, 14.500000);
TextDrawSetOutline(hudHaus, 1);
TextDrawSetShadow(hudHaus, 0);
TextDrawAlignment(hudHaus, 1);
TextDrawColor(hudHaus, 9145343);
TextDrawBackgroundColor(hudHaus, 255);
TextDrawBoxColor(hudHaus, 50);
TextDrawUseBox(hudHaus, 1);
TextDrawSetProportional(hudHaus, 1);
TextDrawSetSelectable(hudHaus, 0);

PublicTD[3] = TextDrawCreate(597.000000, 411.000000, "100%");
TextDrawFont(PublicTD[3], 1);
TextDrawLetterSize(PublicTD[3], 0.175000, 0.850000);
TextDrawTextSize(PublicTD[3], 400.000000, 17.000000);
TextDrawSetOutline(PublicTD[3], 0);
TextDrawSetShadow(PublicTD[3], 0);
TextDrawAlignment(PublicTD[3], 1);
TextDrawColor(PublicTD[3], -1);
TextDrawBackgroundColor(PublicTD[3], 255);
TextDrawBoxColor(PublicTD[3], 50);
TextDrawUseBox(PublicTD[3], 0);
TextDrawSetProportional(PublicTD[3], 1);
TextDrawSetSelectable(PublicTD[3], 0);

PublicTD[4] = TextDrawCreate(549.000000, 431.000000, "Pee");
TextDrawFont(PublicTD[4], 1);
TextDrawLetterSize(PublicTD[4], 0.175000, 0.850000);
TextDrawTextSize(PublicTD[4], 400.000000, 17.000000);
TextDrawSetOutline(PublicTD[4], 0);
TextDrawSetShadow(PublicTD[4], 0);
TextDrawAlignment(PublicTD[4], 1);
TextDrawColor(PublicTD[4], -1);
TextDrawBackgroundColor(PublicTD[4], 255);
TextDrawBoxColor(PublicTD[4], 50);
TextDrawUseBox(PublicTD[4], 0);
TextDrawSetProportional(PublicTD[4], 1);
TextDrawSetSelectable(PublicTD[4], 0);

PublicTD[5] = TextDrawCreate(571.000000, 427.000000, "ld_bum:blkdot");
TextDrawFont(PublicTD[5], 4);
TextDrawLetterSize(PublicTD[5], 0.600000, 2.000000);
TextDrawTextSize(PublicTD[5], 67.000000, 14.500000);
TextDrawSetOutline(PublicTD[5], 1);
TextDrawSetShadow(PublicTD[5], 0);
TextDrawAlignment(PublicTD[5], 1);
TextDrawColor(PublicTD[5], -1962934017);
TextDrawBackgroundColor(PublicTD[5], 255);
TextDrawBoxColor(PublicTD[5], 50);
TextDrawUseBox(PublicTD[5], 1);
TextDrawSetProportional(PublicTD[5], 1);
TextDrawSetSelectable(PublicTD[5], 0);

PublicTD[6] = TextDrawCreate(597.000000, 430.000000, "100%");
TextDrawFont(PublicTD[6], 1);
TextDrawLetterSize(PublicTD[6], 0.175000, 0.850000);
TextDrawTextSize(PublicTD[6], 400.000000, 17.000000);
TextDrawSetOutline(PublicTD[6], 0);
TextDrawSetShadow(PublicTD[6], 0);
TextDrawAlignment(PublicTD[6], 1);
TextDrawColor(PublicTD[6], -1);
TextDrawBackgroundColor(PublicTD[6], 255);
TextDrawBoxColor(PublicTD[6], 50);
TextDrawUseBox(PublicTD[6], 0);
TextDrawSetProportional(PublicTD[6], 1);
TextDrawSetSelectable(PublicTD[6], 0);

PublicTD[7] = TextDrawCreate(644.000000, 367.000000, "_");
TextDrawFont(PublicTD[7], 1);
TextDrawLetterSize(PublicTD[7], 0.925000, 1.450000);
TextDrawTextSize(PublicTD[7], 536.500000, 17.000000);
TextDrawSetOutline(PublicTD[7], 1);
TextDrawSetShadow(PublicTD[7], 0);
TextDrawAlignment(PublicTD[7], 1);
TextDrawColor(PublicTD[7], -1);
TextDrawBackgroundColor(PublicTD[7], 255);
TextDrawBoxColor(PublicTD[7], 50);
TextDrawUseBox(PublicTD[7], 1);
TextDrawSetProportional(PublicTD[7], 1);
TextDrawSetSelectable(PublicTD[7], 0);

PublicTD[8] = TextDrawCreate(543.000000, 370.000000, "ID:_0");
TextDrawFont(PublicTD[8], 1);
TextDrawLetterSize(PublicTD[8], 0.175000, 0.850000);
TextDrawTextSize(PublicTD[8], 400.000000, 17.000000);
TextDrawSetOutline(PublicTD[8], 0);
TextDrawSetShadow(PublicTD[8], 0);
TextDrawAlignment(PublicTD[8], 1);
TextDrawColor(PublicTD[8], -1);
TextDrawBackgroundColor(PublicTD[8], 255);
TextDrawBoxColor(PublicTD[8], 50);
TextDrawUseBox(PublicTD[8], 0);
TextDrawSetProportional(PublicTD[8], 1);
TextDrawSetSelectable(PublicTD[8], 0);

PublicTD[9] = TextDrawCreate(571.000000, 369.000000, "Pekerjaan:_Penggauran");
TextDrawFont(PublicTD[9], 1);
TextDrawLetterSize(PublicTD[9], 0.175000, 0.850000);
TextDrawTextSize(PublicTD[9], 400.000000, 17.000000);
TextDrawSetOutline(PublicTD[9], 0);
TextDrawSetShadow(PublicTD[9], 0);
TextDrawAlignment(PublicTD[9], 1);
TextDrawColor(PublicTD[9], -1);
TextDrawBackgroundColor(PublicTD[9], 255);
TextDrawBoxColor(PublicTD[9], 50);
TextDrawUseBox(PublicTD[9], 0);
TextDrawSetProportional(PublicTD[9], 1);
TextDrawSetSelectable(PublicTD[9], 0);

PublicTD[10] = TextDrawCreate(564.000000, 364.000000, "l");
TextDrawFont(PublicTD[10], 1);
TextDrawLetterSize(PublicTD[10], 0.175000, 1.900000);
TextDrawTextSize(PublicTD[10], 400.000000, 17.000000);
TextDrawSetOutline(PublicTD[10], 0);
TextDrawSetShadow(PublicTD[10], 0);
TextDrawAlignment(PublicTD[10], 1);
TextDrawColor(PublicTD[10], -1);
TextDrawBackgroundColor(PublicTD[10], 255);
TextDrawBoxColor(PublicTD[10], 50);
TextDrawUseBox(PublicTD[10], 0);
TextDrawSetProportional(PublicTD[10], 1);
TextDrawSetSelectable(PublicTD[10], 0);

PublicTD[11] = TextDrawCreate(442.000000, 410.000000, "_");
TextDrawFont(PublicTD[11], 1);
TextDrawLetterSize(PublicTD[11], 0.925000, 3.649997);
TextDrawTextSize(PublicTD[11], 535.500000, 15.000000);
TextDrawSetOutline(PublicTD[11], 1);
TextDrawSetShadow(PublicTD[11], 0);
TextDrawAlignment(PublicTD[11], 1);
TextDrawColor(PublicTD[11], -1);
TextDrawBackgroundColor(PublicTD[11], 255);
TextDrawBoxColor(PublicTD[11], 50);
TextDrawUseBox(PublicTD[11], 1);
TextDrawSetProportional(PublicTD[11], 1);
TextDrawSetSelectable(PublicTD[11], 0);

PublicTD[12] = TextDrawCreate(481.000000, 424.000000, "ld_bum:blkdot");
TextDrawFont(PublicTD[12], 4);
TextDrawLetterSize(PublicTD[12], 0.600000, 2.000000);
TextDrawTextSize(PublicTD[12], 53.500000, 7.500000);
TextDrawSetOutline(PublicTD[12], 1);
TextDrawSetShadow(PublicTD[12], 0);
TextDrawAlignment(PublicTD[12], 1);
TextDrawColor(PublicTD[12], 1097458175);
TextDrawBackgroundColor(PublicTD[12], 255);
TextDrawBoxColor(PublicTD[12], 50);
TextDrawUseBox(PublicTD[12], 0);
TextDrawSetProportional(PublicTD[12], 1);
TextDrawSetSelectable(PublicTD[12], 0);

PublicTD[13] = TextDrawCreate(481.000000, 435.000000, "ld_bum:blkdot");
TextDrawFont(PublicTD[13], 4);
TextDrawLetterSize(PublicTD[13], 0.600000, 2.000000);
TextDrawTextSize(PublicTD[13], 53.500000, 7.500000);
TextDrawSetOutline(PublicTD[13], 1);
TextDrawSetShadow(PublicTD[13], 0);
TextDrawAlignment(PublicTD[13], 1);
TextDrawColor(PublicTD[13], -16776961);
TextDrawBackgroundColor(PublicTD[13], 255);
TextDrawBoxColor(PublicTD[13], 50);
TextDrawUseBox(PublicTD[13], 1);
TextDrawSetProportional(PublicTD[13], 1);
TextDrawSetSelectable(PublicTD[13], 0);

PublicTD[14] = TextDrawCreate(502.000000, 424.000000, "Fuel");
TextDrawFont(PublicTD[14], 1);
TextDrawLetterSize(PublicTD[14], 0.154166, 0.800000);
TextDrawTextSize(PublicTD[14], 400.000000, 17.000000);
TextDrawSetOutline(PublicTD[14], 0);
TextDrawSetShadow(PublicTD[14], 0);
TextDrawAlignment(PublicTD[14], 1);
TextDrawColor(PublicTD[14], -1);
TextDrawBackgroundColor(PublicTD[14], 255);
TextDrawBoxColor(PublicTD[14], 50);
TextDrawUseBox(PublicTD[14], 0);
TextDrawSetProportional(PublicTD[14], 1);
TextDrawSetSelectable(PublicTD[14], 0);

PublicTD[15] = TextDrawCreate(501.000000, 434.000000, "Healt");
TextDrawFont(PublicTD[15], 1);
TextDrawLetterSize(PublicTD[15], 0.154166, 0.800000);
TextDrawTextSize(PublicTD[15], 400.000000, 17.000000);
TextDrawSetOutline(PublicTD[15], 0);
TextDrawSetShadow(PublicTD[15], 0);
TextDrawAlignment(PublicTD[15], 1);
TextDrawColor(PublicTD[15], -1);
TextDrawBackgroundColor(PublicTD[15], 255);
TextDrawBoxColor(PublicTD[15], 50);
TextDrawUseBox(PublicTD[15], 0);
TextDrawSetProportional(PublicTD[15], 1);
TextDrawSetSelectable(PublicTD[15], 0);

PublicTD[16] = TextDrawCreate(448.000000, 417.000000, "100");
TextDrawFont(PublicTD[16], 1);
TextDrawLetterSize(PublicTD[16], 0.308333, 2.049999);
TextDrawTextSize(PublicTD[16], 400.000000, 17.000000);
TextDrawSetOutline(PublicTD[16], 0);
TextDrawSetShadow(PublicTD[16], 0);
TextDrawAlignment(PublicTD[16], 1);
TextDrawColor(PublicTD[16], -1);
TextDrawBackgroundColor(PublicTD[16], 255);
TextDrawBoxColor(PublicTD[16], 50);
TextDrawUseBox(PublicTD[16], 0);
TextDrawSetProportional(PublicTD[16], 1);
TextDrawSetSelectable(PublicTD[16], 0);

PublicTD[17] = TextDrawCreate(481.000000, 413.000000, "ld_bum:blkdot");
TextDrawFont(PublicTD[17], 4);
TextDrawLetterSize(PublicTD[17], 0.600000, 2.000000);
TextDrawTextSize(PublicTD[17], 8.500000, 8.000000);
TextDrawSetOutline(PublicTD[17], 1);
TextDrawSetShadow(PublicTD[17], 0);
TextDrawAlignment(PublicTD[17], 1);
TextDrawColor(PublicTD[17], 16711935);
TextDrawBackgroundColor(PublicTD[17], 255);
TextDrawBoxColor(PublicTD[17], 50);
TextDrawUseBox(PublicTD[17], 0);
TextDrawSetProportional(PublicTD[17], 1);
TextDrawSetSelectable(PublicTD[17], 0);

PublicTD[18] = TextDrawCreate(468.000000, 427.000000, "Km/h");
TextDrawFont(PublicTD[18], 1);
TextDrawLetterSize(PublicTD[18], 0.116666, 0.750000);
TextDrawTextSize(PublicTD[18], 400.000000, 17.000000);
TextDrawSetOutline(PublicTD[18], 0);
TextDrawSetShadow(PublicTD[18], 0);
TextDrawAlignment(PublicTD[18], 1);
TextDrawColor(PublicTD[18], -1);
TextDrawBackgroundColor(PublicTD[18], 255);
TextDrawBoxColor(PublicTD[18], 50);
TextDrawUseBox(PublicTD[18], 0);
TextDrawSetProportional(PublicTD[18], 1);
TextDrawSetSelectable(PublicTD[18], 0);

PublicTD[19] = TextDrawCreate(491.000000, 412.000000, "Engine");
TextDrawFont(PublicTD[19], 1);
TextDrawLetterSize(PublicTD[19], 0.175000, 0.850000);
TextDrawTextSize(PublicTD[19], 400.000000, 17.000000);
TextDrawSetOutline(PublicTD[19], 0);
TextDrawSetShadow(PublicTD[19], 0);
TextDrawAlignment(PublicTD[19], 1);
TextDrawColor(PublicTD[19], -1);
TextDrawBackgroundColor(PublicTD[19], 255);
TextDrawBoxColor(PublicTD[19], 50);
TextDrawUseBox(PublicTD[19], 0);
TextDrawSetProportional(PublicTD[19], 1);
TextDrawSetSelectable(PublicTD[19], 0);

PublicTD[20] = TextDrawCreate(512.000000, 413.000000, "l");
TextDrawFont(PublicTD[20], 1);
TextDrawLetterSize(PublicTD[20], 0.175000, 0.850000);
TextDrawTextSize(PublicTD[20], 400.000000, 17.000000);
TextDrawSetOutline(PublicTD[20], 0);
TextDrawSetShadow(PublicTD[20], 0);
TextDrawAlignment(PublicTD[20], 1);
TextDrawColor(PublicTD[20], -1);
TextDrawBackgroundColor(PublicTD[20], 255);
TextDrawBoxColor(PublicTD[20], 50);
TextDrawUseBox(PublicTD[20], 0);
TextDrawSetProportional(PublicTD[20], 1);
TextDrawSetSelectable(PublicTD[20], 0);

PublicTD[21] = TextDrawCreate(515.000000, 412.000000, "Seatbeal");
TextDrawFont(PublicTD[21], 1);
TextDrawLetterSize(PublicTD[21], 0.150000, 0.850000);
TextDrawTextSize(PublicTD[21], 400.000000, 17.000000);
TextDrawSetOutline(PublicTD[21], 0);
TextDrawSetShadow(PublicTD[21], 0);
TextDrawAlignment(PublicTD[21], 1);
TextDrawColor(PublicTD[21], -1);
TextDrawBackgroundColor(PublicTD[21], 255);
TextDrawBoxColor(PublicTD[21], 50);
TextDrawUseBox(PublicTD[21], 0);
TextDrawSetProportional(PublicTD[21], 1);
TextDrawSetSelectable(PublicTD[21], 0);


//Player Textdraws
PlayerTD[playerid][0] = CreatePlayerTextDraw(playerid, 546.000000, 412.000000, "Sprite");
PlayerTextDrawFont(playerid, PlayerTD[playerid][0], 1);
PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][0], 0.175000, 0.850000);
PlayerTextDrawTextSize(playerid, PlayerTD[playerid][0], 400.000000, 17.000000);
PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][0], 0);
PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][0], 0);
PlayerTextDrawAlignment(playerid, PlayerTD[playerid][0], 1);
PlayerTextDrawColor(playerid, PlayerTD[playerid][0], -1);
PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][0], 255);
PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][0], 50);
PlayerTextDrawUseBox(playerid, PlayerTD[playerid][0], 0);
PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][0], 1);
PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][0], 0);


/*Player Progress Bars
Requires "progress2" include by Southclaws
Download: https://github.com/Southclaws/progress2/releases */
