/*
This file was generated by Nickk's TextDraw editor script
Nickk888 is the author of the NTD script
*/

//Variables
new Text:PublicTD[23];

//Textdraws
PublicTD[0] = TextDrawCreate(145.000000, 357.000000, "_");
TextDrawFont(PublicTD[0], 1);
TextDrawLetterSize(PublicTD[0], 0.225000, 2.999999);
TextDrawTextSize(PublicTD[0], 180.500000, 17.000000);
TextDrawSetOutline(PublicTD[0], 1);
TextDrawSetShadow(PublicTD[0], 0);
TextDrawAlignment(PublicTD[0], 1);
TextDrawColor(PublicTD[0], -1);
TextDrawBackgroundColor(PublicTD[0], 255);
TextDrawBoxColor(PublicTD[0], 50);
TextDrawUseBox(PublicTD[0], 1);
TextDrawSetProportional(PublicTD[0], 1);
TextDrawSetSelectable(PublicTD[0], 0);

PublicTD[1] = TextDrawCreate(184.000000, 355.000000, "ld_bum:blkdot");
TextDrawFont(PublicTD[1], 4);
TextDrawLetterSize(PublicTD[1], 0.600000, 2.000000);
TextDrawTextSize(PublicTD[1], 13.500000, 30.500000);
TextDrawSetOutline(PublicTD[1], 1);
TextDrawSetShadow(PublicTD[1], 0);
TextDrawAlignment(PublicTD[1], 1);
TextDrawColor(PublicTD[1], -1);
TextDrawBackgroundColor(PublicTD[1], 255);
TextDrawBoxColor(PublicTD[1], 50);
TextDrawUseBox(PublicTD[1], 1);
TextDrawSetProportional(PublicTD[1], 1);
TextDrawSetSelectable(PublicTD[1], 0);

PublicTD[2] = TextDrawCreate(185.000000, 356.000000, "ld_bum:blkdot");
TextDrawFont(PublicTD[2], 4);
TextDrawLetterSize(PublicTD[2], 0.600000, 2.000000);
TextDrawTextSize(PublicTD[2], 12.000000, 28.500000);
TextDrawSetOutline(PublicTD[2], 1);
TextDrawSetShadow(PublicTD[2], 0);
TextDrawAlignment(PublicTD[2], 3);
TextDrawColor(PublicTD[2], 16777215);
TextDrawBackgroundColor(PublicTD[2], 255);
TextDrawBoxColor(PublicTD[2], 50);
TextDrawUseBox(PublicTD[2], 1);
TextDrawSetProportional(PublicTD[2], 1);
TextDrawSetSelectable(PublicTD[2], 0);

PublicTD[3] = TextDrawCreate(200.000000, 355.000000, "ld_bum:blkdot");
TextDrawFont(PublicTD[3], 4);
TextDrawLetterSize(PublicTD[3], 0.600000, 2.000000);
TextDrawTextSize(PublicTD[3], 13.500000, 30.500000);
TextDrawSetOutline(PublicTD[3], 1);
TextDrawSetShadow(PublicTD[3], 0);
TextDrawAlignment(PublicTD[3], 1);
TextDrawColor(PublicTD[3], -1);
TextDrawBackgroundColor(PublicTD[3], 255);
TextDrawBoxColor(PublicTD[3], 50);
TextDrawUseBox(PublicTD[3], 1);
TextDrawSetProportional(PublicTD[3], 1);
TextDrawSetSelectable(PublicTD[3], 0);

PublicTD[4] = TextDrawCreate(201.000000, 356.000000, "ld_bum:blkdot");
TextDrawFont(PublicTD[4], 4);
TextDrawLetterSize(PublicTD[4], 0.600000, 2.000000);
TextDrawTextSize(PublicTD[4], 12.000000, 28.500000);
TextDrawSetOutline(PublicTD[4], 1);
TextDrawSetShadow(PublicTD[4], 0);
TextDrawAlignment(PublicTD[4], 3);
TextDrawColor(PublicTD[4], 16777215);
TextDrawBackgroundColor(PublicTD[4], 255);
TextDrawBoxColor(PublicTD[4], 50);
TextDrawUseBox(PublicTD[4], 1);
TextDrawSetProportional(PublicTD[4], 1);
TextDrawSetSelectable(PublicTD[4], 0);

PublicTD[5] = TextDrawCreate(186.000000, 371.000000, "F");
TextDrawFont(PublicTD[5], 1);
TextDrawLetterSize(PublicTD[5], 0.400000, 1.250000);
TextDrawTextSize(PublicTD[5], 400.000000, 17.000000);
TextDrawSetOutline(PublicTD[5], 0);
TextDrawSetShadow(PublicTD[5], 0);
TextDrawAlignment(PublicTD[5], 1);
TextDrawColor(PublicTD[5], 255);
TextDrawBackgroundColor(PublicTD[5], 255);
TextDrawBoxColor(PublicTD[5], 50);
TextDrawUseBox(PublicTD[5], 0);
TextDrawSetProportional(PublicTD[5], 1);
TextDrawSetSelectable(PublicTD[5], 0);

PublicTD[6] = TextDrawCreate(203.000000, 371.000000, "H");
TextDrawFont(PublicTD[6], 1);
TextDrawLetterSize(PublicTD[6], 0.354166, 1.250000);
TextDrawTextSize(PublicTD[6], 400.000000, 17.000000);
TextDrawSetOutline(PublicTD[6], 0);
TextDrawSetShadow(PublicTD[6], 0);
TextDrawAlignment(PublicTD[6], 1);
TextDrawColor(PublicTD[6], 255);
TextDrawBackgroundColor(PublicTD[6], 255);
TextDrawBoxColor(PublicTD[6], 50);
TextDrawUseBox(PublicTD[6], 0);
TextDrawSetProportional(PublicTD[6], 1);
TextDrawSetSelectable(PublicTD[6], 0);

PublicTD[7] = TextDrawCreate(146.000000, 364.000000, "100");
TextDrawFont(PublicTD[7], 1);
TextDrawLetterSize(PublicTD[7], 0.400000, 1.250000);
TextDrawTextSize(PublicTD[7], 400.000000, 17.000000);
TextDrawSetOutline(PublicTD[7], 0);
TextDrawSetShadow(PublicTD[7], 0);
TextDrawAlignment(PublicTD[7], 1);
TextDrawColor(PublicTD[7], -1);
TextDrawBackgroundColor(PublicTD[7], 255);
TextDrawBoxColor(PublicTD[7], 50);
TextDrawUseBox(PublicTD[7], 0);
TextDrawSetProportional(PublicTD[7], 1);
TextDrawSetSelectable(PublicTD[7], 0);

PublicTD[8] = TextDrawCreate(144.000000, 389.000000, "ld_bum:blkdot");
TextDrawFont(PublicTD[8], 4);
TextDrawLetterSize(PublicTD[8], 0.600000, 2.000000);
TextDrawTextSize(PublicTD[8], 4.500000, 28.500000);
TextDrawSetOutline(PublicTD[8], 1);
TextDrawSetShadow(PublicTD[8], 0);
TextDrawAlignment(PublicTD[8], 3);
TextDrawColor(PublicTD[8], 16777215);
TextDrawBackgroundColor(PublicTD[8], 255);
TextDrawBoxColor(PublicTD[8], 50);
TextDrawUseBox(PublicTD[8], 1);
TextDrawSetProportional(PublicTD[8], 1);
TextDrawSetSelectable(PublicTD[8], 0);

PublicTD[9] = TextDrawCreate(150.000000, 389.000000, "ld_bum:blkdot");
TextDrawFont(PublicTD[9], 4);
TextDrawLetterSize(PublicTD[9], 0.600000, 2.000000);
TextDrawTextSize(PublicTD[9], 4.500000, 28.500000);
TextDrawSetOutline(PublicTD[9], 1);
TextDrawSetShadow(PublicTD[9], 0);
TextDrawAlignment(PublicTD[9], 3);
TextDrawColor(PublicTD[9], 16777215);
TextDrawBackgroundColor(PublicTD[9], 255);
TextDrawBoxColor(PublicTD[9], 50);
TextDrawUseBox(PublicTD[9], 1);
TextDrawSetProportional(PublicTD[9], 1);
TextDrawSetSelectable(PublicTD[9], 0);

PublicTD[10] = TextDrawCreate(156.000000, 389.000000, "ld_bum:blkdot");
TextDrawFont(PublicTD[10], 4);
TextDrawLetterSize(PublicTD[10], 0.600000, 2.000000);
TextDrawTextSize(PublicTD[10], 4.500000, 28.500000);
TextDrawSetOutline(PublicTD[10], 1);
TextDrawSetShadow(PublicTD[10], 0);
TextDrawAlignment(PublicTD[10], 3);
TextDrawColor(PublicTD[10], 16777215);
TextDrawBackgroundColor(PublicTD[10], 255);
TextDrawBoxColor(PublicTD[10], 50);
TextDrawUseBox(PublicTD[10], 1);
TextDrawSetProportional(PublicTD[10], 1);
TextDrawSetSelectable(PublicTD[10], 0);

PublicTD[11] = TextDrawCreate(162.000000, 389.000000, "ld_bum:blkdot");
TextDrawFont(PublicTD[11], 4);
TextDrawLetterSize(PublicTD[11], 0.600000, 2.000000);
TextDrawTextSize(PublicTD[11], 4.500000, 28.500000);
TextDrawSetOutline(PublicTD[11], 1);
TextDrawSetShadow(PublicTD[11], 0);
TextDrawAlignment(PublicTD[11], 3);
TextDrawColor(PublicTD[11], 16777215);
TextDrawBackgroundColor(PublicTD[11], 255);
TextDrawBoxColor(PublicTD[11], 50);
TextDrawUseBox(PublicTD[11], 1);
TextDrawSetProportional(PublicTD[11], 1);
TextDrawSetSelectable(PublicTD[11], 0);

PublicTD[12] = TextDrawCreate(168.000000, 389.000000, "ld_bum:blkdot");
TextDrawFont(PublicTD[12], 4);
TextDrawLetterSize(PublicTD[12], 0.600000, 2.000000);
TextDrawTextSize(PublicTD[12], 4.500000, 28.500000);
TextDrawSetOutline(PublicTD[12], 1);
TextDrawSetShadow(PublicTD[12], 0);
TextDrawAlignment(PublicTD[12], 3);
TextDrawColor(PublicTD[12], 2094792959);
TextDrawBackgroundColor(PublicTD[12], 255);
TextDrawBoxColor(PublicTD[12], 50);
TextDrawUseBox(PublicTD[12], 1);
TextDrawSetProportional(PublicTD[12], 1);
TextDrawSetSelectable(PublicTD[12], 0);

PublicTD[13] = TextDrawCreate(174.000000, 389.000000, "ld_bum:blkdot");
TextDrawFont(PublicTD[13], 4);
TextDrawLetterSize(PublicTD[13], 0.600000, 2.000000);
TextDrawTextSize(PublicTD[13], 4.500000, 28.500000);
TextDrawSetOutline(PublicTD[13], 1);
TextDrawSetShadow(PublicTD[13], 0);
TextDrawAlignment(PublicTD[13], 3);
TextDrawColor(PublicTD[13], 2094792959);
TextDrawBackgroundColor(PublicTD[13], 255);
TextDrawBoxColor(PublicTD[13], 50);
TextDrawUseBox(PublicTD[13], 1);
TextDrawSetProportional(PublicTD[13], 1);
TextDrawSetSelectable(PublicTD[13], 0);

PublicTD[14] = TextDrawCreate(180.000000, 389.000000, "ld_bum:blkdot");
TextDrawFont(PublicTD[14], 4);
TextDrawLetterSize(PublicTD[14], 0.600000, 2.000000);
TextDrawTextSize(PublicTD[14], 4.500000, 28.500000);
TextDrawSetOutline(PublicTD[14], 1);
TextDrawSetShadow(PublicTD[14], 0);
TextDrawAlignment(PublicTD[14], 3);
TextDrawColor(PublicTD[14], 2094792959);
TextDrawBackgroundColor(PublicTD[14], 255);
TextDrawBoxColor(PublicTD[14], 50);
TextDrawUseBox(PublicTD[14], 1);
TextDrawSetProportional(PublicTD[14], 1);
TextDrawSetSelectable(PublicTD[14], 0);

PublicTD[15] = TextDrawCreate(186.000000, 389.000000, "ld_bum:blkdot");
TextDrawFont(PublicTD[15], 4);
TextDrawLetterSize(PublicTD[15], 0.600000, 2.000000);
TextDrawTextSize(PublicTD[15], 4.500000, 28.500000);
TextDrawSetOutline(PublicTD[15], 1);
TextDrawSetShadow(PublicTD[15], 0);
TextDrawAlignment(PublicTD[15], 3);
TextDrawColor(PublicTD[15], 2094792959);
TextDrawBackgroundColor(PublicTD[15], 255);
TextDrawBoxColor(PublicTD[15], 50);
TextDrawUseBox(PublicTD[15], 1);
TextDrawSetProportional(PublicTD[15], 1);
TextDrawSetSelectable(PublicTD[15], 0);

PublicTD[16] = TextDrawCreate(192.000000, 389.000000, "ld_bum:blkdot");
TextDrawFont(PublicTD[16], 4);
TextDrawLetterSize(PublicTD[16], 0.600000, 2.000000);
TextDrawTextSize(PublicTD[16], 4.500000, 28.500000);
TextDrawSetOutline(PublicTD[16], 1);
TextDrawSetShadow(PublicTD[16], 0);
TextDrawAlignment(PublicTD[16], 3);
TextDrawColor(PublicTD[16], -1);
TextDrawBackgroundColor(PublicTD[16], 255);
TextDrawBoxColor(PublicTD[16], 50);
TextDrawUseBox(PublicTD[16], 1);
TextDrawSetProportional(PublicTD[16], 1);
TextDrawSetSelectable(PublicTD[16], 0);

PublicTD[17] = TextDrawCreate(198.000000, 389.000000, "ld_bum:blkdot");
TextDrawFont(PublicTD[17], 4);
TextDrawLetterSize(PublicTD[17], 0.600000, 2.000000);
TextDrawTextSize(PublicTD[17], 4.500000, 28.500000);
TextDrawSetOutline(PublicTD[17], 1);
TextDrawSetShadow(PublicTD[17], 0);
TextDrawAlignment(PublicTD[17], 3);
TextDrawColor(PublicTD[17], -1);
TextDrawBackgroundColor(PublicTD[17], 255);
TextDrawBoxColor(PublicTD[17], 50);
TextDrawUseBox(PublicTD[17], 1);
TextDrawSetProportional(PublicTD[17], 1);
TextDrawSetSelectable(PublicTD[17], 0);

PublicTD[18] = TextDrawCreate(204.000000, 389.000000, "ld_bum:blkdot");
TextDrawFont(PublicTD[18], 4);
TextDrawLetterSize(PublicTD[18], 0.600000, 2.000000);
TextDrawTextSize(PublicTD[18], 4.500000, 28.500000);
TextDrawSetOutline(PublicTD[18], 1);
TextDrawSetShadow(PublicTD[18], 0);
TextDrawAlignment(PublicTD[18], 3);
TextDrawColor(PublicTD[18], -1);
TextDrawBackgroundColor(PublicTD[18], 255);
TextDrawBoxColor(PublicTD[18], 50);
TextDrawUseBox(PublicTD[18], 1);
TextDrawSetProportional(PublicTD[18], 1);
TextDrawSetSelectable(PublicTD[18], 0);

PublicTD[19] = TextDrawCreate(210.000000, 389.000000, "ld_bum:blkdot");
TextDrawFont(PublicTD[19], 4);
TextDrawLetterSize(PublicTD[19], 0.600000, 2.000000);
TextDrawTextSize(PublicTD[19], 4.500000, 28.500000);
TextDrawSetOutline(PublicTD[19], 1);
TextDrawSetShadow(PublicTD[19], 0);
TextDrawAlignment(PublicTD[19], 3);
TextDrawColor(PublicTD[19], -1);
TextDrawBackgroundColor(PublicTD[19], 255);
TextDrawBoxColor(PublicTD[19], 50);
TextDrawUseBox(PublicTD[19], 1);
TextDrawSetProportional(PublicTD[19], 1);
TextDrawSetSelectable(PublicTD[19], 0);

PublicTD[20] = TextDrawCreate(143.000000, 387.000000, "ld_bum:blkdot");
TextDrawFont(PublicTD[20], 4);
TextDrawLetterSize(PublicTD[20], 0.600000, 2.000000);
TextDrawTextSize(PublicTD[20], 71.500000, 1.500000);
TextDrawSetOutline(PublicTD[20], 1);
TextDrawSetShadow(PublicTD[20], 0);
TextDrawAlignment(PublicTD[20], 1);
TextDrawColor(PublicTD[20], -1);
TextDrawBackgroundColor(PublicTD[20], 255);
TextDrawBoxColor(PublicTD[20], 50);
TextDrawUseBox(PublicTD[20], 1);
TextDrawSetProportional(PublicTD[20], 1);
TextDrawSetSelectable(PublicTD[20], 0);

PublicTD[21] = TextDrawCreate(210.000000, 389.000000, "ld_bum:blkdot");
TextDrawFont(PublicTD[21], 4);
TextDrawLetterSize(PublicTD[21], 0.600000, 2.000000);
TextDrawTextSize(PublicTD[21], 4.500000, 28.500000);
TextDrawSetOutline(PublicTD[21], 1);
TextDrawSetShadow(PublicTD[21], 0);
TextDrawAlignment(PublicTD[21], 3);
TextDrawColor(PublicTD[21], -1);
TextDrawBackgroundColor(PublicTD[21], 255);
TextDrawBoxColor(PublicTD[21], 50);
TextDrawUseBox(PublicTD[21], 1);
TextDrawSetProportional(PublicTD[21], 1);
TextDrawSetSelectable(PublicTD[21], 0);

PublicTD[22] = TextDrawCreate(171.000000, 367.000000, "KM/H");
TextDrawFont(PublicTD[22], 1);
TextDrawLetterSize(PublicTD[22], 0.104166, 0.700001);
TextDrawTextSize(PublicTD[22], 400.000000, 17.000000);
TextDrawSetOutline(PublicTD[22], 0);
TextDrawSetShadow(PublicTD[22], 0);
TextDrawAlignment(PublicTD[22], 1);
TextDrawColor(PublicTD[22], -1);
TextDrawBackgroundColor(PublicTD[22], 255);
TextDrawBoxColor(PublicTD[22], 50);
TextDrawUseBox(PublicTD[22], 0);
TextDrawSetProportional(PublicTD[22], 1);
TextDrawSetSelectable(PublicTD[22], 0);


//Player Textdraws

/*Player Progress Bars
Requires "progress2" include by Southclaws
Download: https://github.com/Southclaws/progress2/releases */
