/*
This file was generated by Nickk's TextDraw editor script
Nickk888 is the author of the NTD script
*/

#include <a_samp>

new Text:PublicTD[13];

public OnFilterScriptInit()
{
	PublicTD[0] = TextDrawCreate(-18.000000, -39.000000, "Preview_Model");
	TextDrawFont(PublicTD[0], 5);
	TextDrawLetterSize(PublicTD[0], 0.600000, 2.000000);
	TextDrawTextSize(PublicTD[0], 112.500000, 150.000000);
	TextDrawSetOutline(PublicTD[0], 0);
	TextDrawSetShadow(PublicTD[0], 0);
	TextDrawAlignment(PublicTD[0], 1);
	TextDrawColor(PublicTD[0], -1);
	TextDrawBackgroundColor(PublicTD[0], 0);
	TextDrawBoxColor(PublicTD[0], 255);
	TextDrawUseBox(PublicTD[0], 0);
	TextDrawSetProportional(PublicTD[0], 1);
	TextDrawSetSelectable(PublicTD[0], 0);
	TextDrawSetPreviewModel(PublicTD[0], 19076);
	TextDrawSetPreviewRot(PublicTD[0], -10.000000, 0.000000, -20.000000, 4.559998);
	TextDrawSetPreviewVehCol(PublicTD[0], 1, 1);

	PublicTD[1] = TextDrawCreate(64.000000, -40.000000, "Preview_Model");
	TextDrawFont(PublicTD[1], 5);
	TextDrawLetterSize(PublicTD[1], 0.600000, 2.000000);
	TextDrawTextSize(PublicTD[1], 112.500000, 150.000000);
	TextDrawSetOutline(PublicTD[1], 0);
	TextDrawSetShadow(PublicTD[1], 0);
	TextDrawAlignment(PublicTD[1], 1);
	TextDrawColor(PublicTD[1], -1);
	TextDrawBackgroundColor(PublicTD[1], 0);
	TextDrawBoxColor(PublicTD[1], 255);
	TextDrawUseBox(PublicTD[1], 0);
	TextDrawSetProportional(PublicTD[1], 1);
	TextDrawSetSelectable(PublicTD[1], 0);
	TextDrawSetPreviewModel(PublicTD[1], 19076);
	TextDrawSetPreviewRot(PublicTD[1], -10.000000, 0.000000, -27.000000, 4.559998);
	TextDrawSetPreviewVehCol(PublicTD[1], 1, 1);

	PublicTD[2] = TextDrawCreate(34.000000, 44.000000, "ld_dual:white");
	TextDrawFont(PublicTD[2], 4);
	TextDrawLetterSize(PublicTD[2], 0.600000, 2.000000);
	TextDrawTextSize(PublicTD[2], 90.500000, 17.000000);
	TextDrawSetOutline(PublicTD[2], 1);
	TextDrawSetShadow(PublicTD[2], 0);
	TextDrawAlignment(PublicTD[2], 1);
	TextDrawColor(PublicTD[2], 143);
	TextDrawBackgroundColor(PublicTD[2], 255);
	TextDrawBoxColor(PublicTD[2], 50);
	TextDrawUseBox(PublicTD[2], 1);
	TextDrawSetProportional(PublicTD[2], 1);
	TextDrawSetSelectable(PublicTD[2], 1);

	PublicTD[3] = TextDrawCreate(34.000000, 63.000000, "ld_dual:white");
	TextDrawFont(PublicTD[3], 4);
	TextDrawLetterSize(PublicTD[3], 0.600000, 2.000000);
	TextDrawTextSize(PublicTD[3], 90.500000, 17.000000);
	TextDrawSetOutline(PublicTD[3], 1);
	TextDrawSetShadow(PublicTD[3], 0);
	TextDrawAlignment(PublicTD[3], 1);
	TextDrawColor(PublicTD[3], 143);
	TextDrawBackgroundColor(PublicTD[3], 255);
	TextDrawBoxColor(PublicTD[3], 50);
	TextDrawUseBox(PublicTD[3], 1);
	TextDrawSetProportional(PublicTD[3], 1);
	TextDrawSetSelectable(PublicTD[3], 1);

	PublicTD[4] = TextDrawCreate(34.000000, 82.000000, "ld_dual:white");
	TextDrawFont(PublicTD[4], 4);
	TextDrawLetterSize(PublicTD[4], 0.600000, 2.000000);
	TextDrawTextSize(PublicTD[4], 90.500000, 17.000000);
	TextDrawSetOutline(PublicTD[4], 1);
	TextDrawSetShadow(PublicTD[4], 0);
	TextDrawAlignment(PublicTD[4], 1);
	TextDrawColor(PublicTD[4], 16711823);
	TextDrawBackgroundColor(PublicTD[4], 255);
	TextDrawBoxColor(PublicTD[4], 50);
	TextDrawUseBox(PublicTD[4], 1);
	TextDrawSetProportional(PublicTD[4], 1);
	TextDrawSetSelectable(PublicTD[4], 1);

	PublicTD[5] = TextDrawCreate(44.000000, 31.000000, "Dimana Anda Ingin Mendarat?");
	TextDrawFont(PublicTD[5], 1);
	TextDrawLetterSize(PublicTD[5], 0.145833, 1.000000);
	TextDrawTextSize(PublicTD[5], 400.000000, 17.000000);
	TextDrawSetOutline(PublicTD[5], 0);
	TextDrawSetShadow(PublicTD[5], 0);
	TextDrawAlignment(PublicTD[5], 1);
	TextDrawColor(PublicTD[5], -1);
	TextDrawBackgroundColor(PublicTD[5], 255);
	TextDrawBoxColor(PublicTD[5], 50);
	TextDrawUseBox(PublicTD[5], 0);
	TextDrawSetProportional(PublicTD[5], 1);
	TextDrawSetSelectable(PublicTD[5], 0);

	PublicTD[6] = TextDrawCreate(69.000000, 47.000000, "Bandara");
	TextDrawFont(PublicTD[6], 1);
	TextDrawLetterSize(PublicTD[6], 0.137500, 1.000000);
	TextDrawTextSize(PublicTD[6], 400.000000, 17.000000);
	TextDrawSetOutline(PublicTD[6], 0);
	TextDrawSetShadow(PublicTD[6], 0);
	TextDrawAlignment(PublicTD[6], 1);
	TextDrawColor(PublicTD[6], -1);
	TextDrawBackgroundColor(PublicTD[6], 255);
	TextDrawBoxColor(PublicTD[6], 50);
	TextDrawUseBox(PublicTD[6], 0);
	TextDrawSetProportional(PublicTD[6], 1);
	TextDrawSetSelectable(PublicTD[6], 0);

	PublicTD[7] = TextDrawCreate(62.000000, 66.000000, "Lokasi Terakhir");
	TextDrawFont(PublicTD[7], 1);
	TextDrawLetterSize(PublicTD[7], 0.137500, 1.000000);
	TextDrawTextSize(PublicTD[7], 400.000000, 17.000000);
	TextDrawSetOutline(PublicTD[7], 0);
	TextDrawSetShadow(PublicTD[7], 0);
	TextDrawAlignment(PublicTD[7], 1);
	TextDrawColor(PublicTD[7], -1);
	TextDrawBackgroundColor(PublicTD[7], 255);
	TextDrawBoxColor(PublicTD[7], 50);
	TextDrawUseBox(PublicTD[7], 0);
	TextDrawSetProportional(PublicTD[7], 1);
	TextDrawSetSelectable(PublicTD[7], 0);

	PublicTD[8] = TextDrawCreate(71.000000, 85.000000, "Spawn");
	TextDrawFont(PublicTD[8], 1);
	TextDrawLetterSize(PublicTD[8], 0.137500, 1.000000);
	TextDrawTextSize(PublicTD[8], 400.000000, 17.000000);
	TextDrawSetOutline(PublicTD[8], 0);
	TextDrawSetShadow(PublicTD[8], 0);
	TextDrawAlignment(PublicTD[8], 1);
	TextDrawColor(PublicTD[8], 255);
	TextDrawBackgroundColor(PublicTD[8], 255);
	TextDrawBoxColor(PublicTD[8], 50);
	TextDrawUseBox(PublicTD[8], 0);
	TextDrawSetProportional(PublicTD[8], 1);
	TextDrawSetSelectable(PublicTD[8], 0);

	PublicTD[9] = TextDrawCreate(34.000000, 44.000000, "ld_dual:white");
	TextDrawFont(PublicTD[9], 4);
	TextDrawLetterSize(PublicTD[9], 0.600000, 2.000000);
	TextDrawTextSize(PublicTD[9], 0.500000, 17.000000);
	TextDrawSetOutline(PublicTD[9], 1);
	TextDrawSetShadow(PublicTD[9], 0);
	TextDrawAlignment(PublicTD[9], 1);
	TextDrawColor(PublicTD[9], -16777073);
	TextDrawBackgroundColor(PublicTD[9], 255);
	TextDrawBoxColor(PublicTD[9], 50);
	TextDrawUseBox(PublicTD[9], 1);
	TextDrawSetProportional(PublicTD[9], 1);
	TextDrawSetSelectable(PublicTD[9], 0);

	PublicTD[10] = TextDrawCreate(124.000000, 44.000000, "ld_dual:white");
	TextDrawFont(PublicTD[10], 4);
	TextDrawLetterSize(PublicTD[10], 0.600000, 2.000000);
	TextDrawTextSize(PublicTD[10], 0.500000, 17.000000);
	TextDrawSetOutline(PublicTD[10], 1);
	TextDrawSetShadow(PublicTD[10], 0);
	TextDrawAlignment(PublicTD[10], 1);
	TextDrawColor(PublicTD[10], -16777073);
	TextDrawBackgroundColor(PublicTD[10], 255);
	TextDrawBoxColor(PublicTD[10], 50);
	TextDrawUseBox(PublicTD[10], 1);
	TextDrawSetProportional(PublicTD[10], 1);
	TextDrawSetSelectable(PublicTD[10], 0);

	PublicTD[11] = TextDrawCreate(124.000000, 63.000000, "ld_dual:white");
	TextDrawFont(PublicTD[11], 4);
	TextDrawLetterSize(PublicTD[11], 0.600000, 2.000000);
	TextDrawTextSize(PublicTD[11], 0.500000, 17.000000);
	TextDrawSetOutline(PublicTD[11], 1);
	TextDrawSetShadow(PublicTD[11], 0);
	TextDrawAlignment(PublicTD[11], 1);
	TextDrawColor(PublicTD[11], -16777073);
	TextDrawBackgroundColor(PublicTD[11], 255);
	TextDrawBoxColor(PublicTD[11], 50);
	TextDrawUseBox(PublicTD[11], 1);
	TextDrawSetProportional(PublicTD[11], 1);
	TextDrawSetSelectable(PublicTD[11], 0);

	PublicTD[12] = TextDrawCreate(34.000000, 63.000000, "ld_dual:white");
	TextDrawFont(PublicTD[12], 4);
	TextDrawLetterSize(PublicTD[12], 0.600000, 2.000000);
	TextDrawTextSize(PublicTD[12], 0.500000, 17.000000);
	TextDrawSetOutline(PublicTD[12], 1);
	TextDrawSetShadow(PublicTD[12], 0);
	TextDrawAlignment(PublicTD[12], 1);
	TextDrawColor(PublicTD[12], -16777073);
	TextDrawBackgroundColor(PublicTD[12], 255);
	TextDrawBoxColor(PublicTD[12], 50);
	TextDrawUseBox(PublicTD[12], 1);
	TextDrawSetProportional(PublicTD[12], 1);
	TextDrawSetSelectable(PublicTD[12], 0);

	return 1;
}

public OnFilterScriptExit()
{
	TextDrawDestroy(PublicTD[0]);
	TextDrawDestroy(PublicTD[1]);
	TextDrawDestroy(PublicTD[2]);
	TextDrawDestroy(PublicTD[3]);
	TextDrawDestroy(PublicTD[4]);
	TextDrawDestroy(PublicTD[5]);
	TextDrawDestroy(PublicTD[6]);
	TextDrawDestroy(PublicTD[7]);
	TextDrawDestroy(PublicTD[8]);
	TextDrawDestroy(PublicTD[9]);
	TextDrawDestroy(PublicTD[10]);
	TextDrawDestroy(PublicTD[11]);
	TextDrawDestroy(PublicTD[12]);
	return 1;
}

public OnPlayerConnect(playerid)
{
	return 1;
}

public OnPlayerDisconnect(playerid, reason)
{
	return 1;
}

public OnPlayerCommandText(playerid, cmdtext[])
{
	if(!strcmp(cmdtext, "/tdtest", true))
	{
		TextDrawShowForPlayer(playerid, PublicTD[0]);
		TextDrawShowForPlayer(playerid, PublicTD[1]);
		TextDrawShowForPlayer(playerid, PublicTD[2]);
		TextDrawShowForPlayer(playerid, PublicTD[3]);
		TextDrawShowForPlayer(playerid, PublicTD[4]);
		TextDrawShowForPlayer(playerid, PublicTD[5]);
		TextDrawShowForPlayer(playerid, PublicTD[6]);
		TextDrawShowForPlayer(playerid, PublicTD[7]);
		TextDrawShowForPlayer(playerid, PublicTD[8]);
		TextDrawShowForPlayer(playerid, PublicTD[9]);
		TextDrawShowForPlayer(playerid, PublicTD[10]);
		TextDrawShowForPlayer(playerid, PublicTD[11]);
		TextDrawShowForPlayer(playerid, PublicTD[12]);
		SelectTextDraw(playerid, 0xFF0000FF);
		return 1;
	}
	return 0;
}
