/*
This file was generated by Nickk's TextDraw editor script
Nickk888 is the author of the NTD script
*/

#include <a_samp>

new PlayerText:playertextdraw_0[MAX_PLAYERS];

public OnFilterScriptInit()
{
	return 1;
}

public OnFilterScriptExit()
{
	return 1;
}

public OnPlayerConnect(playerid)
{
	playertextdraw_0[playerid] = CreatePlayerTextDraw(playerid, 170.000000, 350.000000, "~y~NAME:_~g~INFERNUS~n~~y~SPEED:_~b~100KM/h~n~~y~HEALTH:_~r~100~n~~y~FUEL:_~w~64L");
	PlayerTextDrawFont(playerid, playertextdraw_0[playerid], 2);
	PlayerTextDrawLetterSize(playerid, playertextdraw_0[playerid], 0.229166, 1.950000);
	PlayerTextDrawTextSize(playerid, playertextdraw_0[playerid], 604.000000, 17.000000);
	PlayerTextDrawSetOutline(playerid, playertextdraw_0[playerid], 1);
	PlayerTextDrawSetShadow(playerid, playertextdraw_0[playerid], 2);
	PlayerTextDrawAlignment(playerid, playertextdraw_0[playerid], 1);
	PlayerTextDrawColor(playerid, playertextdraw_0[playerid], -1);
	PlayerTextDrawBackgroundColor(playerid, playertextdraw_0[playerid], 255);
	PlayerTextDrawBoxColor(playerid, playertextdraw_0[playerid], 100);
	PlayerTextDrawUseBox(playerid, playertextdraw_0[playerid], 0);
	PlayerTextDrawSetProportional(playerid, playertextdraw_0[playerid], 1);
	PlayerTextDrawSetSelectable(playerid, playertextdraw_0[playerid], 0);

	return 1;
}

public OnPlayerDisconnect(playerid, reason)
{
	PlayerTextDrawDestroy(playerid, playertextdraw_0[playerid]);
	return 1;
}

public OnPlayerCommandText(playerid, cmdtext[])
{
	if(!strcmp(cmdtext, "/tdtest", true))
	{
		PlayerTextDrawShow(playerid, playertextdraw_0[playerid]);
		return 1;
	}
	return 0;
}
