/*
This file was generated by Nickk's TextDraw editor script
Nickk888 is the author of the NTD script
*/

//Variables
new Text:FlyyTD[2];

//Textdraws
FlyyTD[0] = TextDrawCreate(340.000000, 20.000000, "Panile /");
TextDrawFont(FlyyTD[0], 1);
TextDrawLetterSize(FlyyTD[0], 0.699998, 3.000000);
TextDrawTextSize(FlyyTD[0], 400.000000, 17.000000);
TextDrawSetOutline(FlyyTD[0], 1);
TextDrawSetShadow(FlyyTD[0], 0);
TextDrawAlignment(FlyyTD[0], 1);
TextDrawColor(FlyyTD[0], 16777215);
TextDrawBackgroundColor(FlyyTD[0], 255);
TextDrawBoxColor(FlyyTD[0], 50);
TextDrawUseBox(FlyyTD[0], 0);
TextDrawSetProportional(FlyyTD[0], 1);
TextDrawSetSelectable(FlyyTD[0], 0);

FlyyTD[1] = TextDrawCreate(375.000000, 45.000000, "RolePlay");
TextDrawFont(FlyyTD[1], 1);
TextDrawLetterSize(FlyyTD[1], 0.699998, 3.000000);
TextDrawTextSize(FlyyTD[1], 400.000000, 17.000000);
TextDrawSetOutline(FlyyTD[1], 1);
TextDrawSetShadow(FlyyTD[1], 0);
TextDrawAlignment(FlyyTD[1], 1);
TextDrawColor(FlyyTD[1], -16776961);
TextDrawBackgroundColor(FlyyTD[1], 255);
TextDrawBoxColor(FlyyTD[1], 50);
TextDrawUseBox(FlyyTD[1], 0);
TextDrawSetProportional(FlyyTD[1], 1);
TextDrawSetSelectable(FlyyTD[1], 0);


//Player Textdraws

/*Player Progress Bars
Requires "progress2" include by Southclaws
Download: https://github.com/Southclaws/progress2/releases */
